SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[fn_path_depth] ( @path VARCHAR(450) )
RETURNS INT
AS
    BEGIN 
        RETURN DATALENGTH(@path)-DATALENGTH(REPLACE(@path,'/',''));
    END;
GO
