SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION dbo.fn_folder_id_from_path
(
    @path NVARCHAR(450)
)
RETURNS UNIQUEIDENTIFIER
--WITH ENCRYPTION
AS
BEGIN
    DECLARE @id UNIQUEIDENTIFIER;

    SELECT @id = FOLDER_ID
    FROM [dbo].[TB_SEC_FOLDER]
    WHERE PATH = @path;

    RETURN @id;
END;
GO
