SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ap_adm01_get_olap_processed_state]
AS
    SET NOCOUNT ON;
    
    SELECT TABLE_NAME, MIN(LAST_GENERATION_COUNT) AS PROCESSED_THRESHOLD
    FROM dbo.TS_IMP_OLAP_DIMENSION_STATE s
    INNER JOIN dbo.VW_ADM_TABLE_GENERATION_COUNT g
    ON s.TABLE_GENERATION_COUNT_URN = g.TABLE_GENERATION_COUNT_URN
    GROUP BY TABLE_NAME;
GO
GRANT EXECUTE
	ON [dbo].[ap_adm01_get_olap_processed_state]
	TO [portalapp_role]
GO
