SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ap_in01_imp_get_times] AS
SELECT TIME_URN, [HOUR], [MINUTE]
FROM dbo.TB_DIM_TIME
WHERE [MINUTE] = 0
    OR [MINUTE] = 30;
GO
