SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ap_in01_imp_get_resourceid]
(
    @InstanceName nvarchar(50)
) AS
SET NOCOUNT ON;

DECLARE @internalName AS NVARCHAR(50);

SELECT RESOURCE_ID [CLUSTER_RESOURCE_ID]
FROM TB_CLU_RESOURCE res
INNER JOIN TE_ADM_CLUSTER_RESOURCE_TYPE type ON res.RESOURCE_TYPE_ID = type.CLUSTER_RESOURCE_TYPE_ID
WHERE type.[NAME] = 'CRT_IN'
    AND res.NAME = @InstanceName;

RETURN @@ERROR;
GO
