SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ap_in01_imp_get_tlis] AS
SELECT tli.ITEM_URN [TLI_URN], pkey.[DIGITS] [TLI_STRING]
FROM TB_DIM_TLI tli
INNER JOIN TB_DIM_TLI_PKEY_MAP pkey ON pkey.ITEM_BIZ_URN = tli.ITEM_BIZ_URN
    AND pkey.LATEST = 1
WHERE GETUTCDATE() BETWEEN tli.EFFECTIVE_FROM AND tli.EFFECTIVE_TO;
GO
