SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ap_in01_imp_get_call_sources] AS

SELECT i.ITEM_URN [CALL_SOURCE_URN], pkey.[CALL_SOURCE_CODE] [CALL_SOURCE]
FROM TB_DIM_CALL_SOURCE i
INNER JOIN TB_DIM_CALL_SOURCE_PKEY_MAP pkey ON pkey.ITEM_BIZ_URN = i.ITEM_BIZ_URN
WHERE GETUTCDATE() BETWEEN i.EFFECTIVE_FROM AND i.EFFECTIVE_TO AND i.ITEM_URN >= 0;
GO
