SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ap_in01_imp_get_nngs] AS
SELECT nng.MEMBER [NNG_CODE], nng.NNG_URN [NNG_URN]
FROM VW_DIM_NNG nng
WHERE ISNUMERIC(nng.MEMBER) = 1
    AND GETUTCDATE() BETWEEN nng.EFFECTIVE_FROM
        AND nng.EFFECTIVE_TO
ORDER BY NNG_CODE ASC;
GO
