SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Skill_Group_Interval]
AS
SELECT  [skillGroupInterval].[DATE_TIME] AS DateTime,
        CAST([skillGroup].[PKEY1] AS INT) AS SkillTargetID,
        [skillGroupInterval].[TIME_ZONE] AS TimeZone,
        [skillGroupInterval].[CALLBACK_MESSAGES] AS CallbackMessages,
        [skillGroupInterval].[CALLBACK_MESSAGES_TIME] AS CallbackMessagesTime,
        [skillGroupInterval].[AVG_HANDLED_CALLS_TALK_TIME] AS AvgHandledCallsTalkTime,
        [skillGroupInterval].[HOLD_TIME] AS HoldTime,
        [skillGroupInterval].[HANDLED_CALLS_TALK_TIME] AS HandledCallsTalkTime,
        [skillGroupInterval].[INTERNAL_CALLS] AS InternalCalls,
        [skillGroupInterval].[INTERNAL_CALLS_TIME] AS InternalCallsTime,
        [skillGroupInterval].[CALLS_HANDLED] AS CallsHandled,
        [skillGroupInterval].[SUPERV_ASSIST_CALLS] AS SupervAssistCalls,
        [skillGroupInterval].[AVG_HANDLED_CALLS_TIME] AS AvgHandledCallsTime,
        [skillGroupInterval].[SUPERV_ASSIST_CALLS_TIME] AS SupervAssistCallsTime,
        [skillGroupInterval].[HANDLED_CALLS_TIME] AS HandledCallsTime,
        [skillGroupInterval].[PERCENT_UTILIZATION] AS PercentUtilization,
        [skillGroupInterval].[AGENT_OUT_CALLS_TIME] AS AgentOutCallsTime,
        [skillGroupInterval].[TALK_IN_TIME] AS TalkInTime,
        [skillGroupInterval].[LOGGED_ON_TIME] AS LoggedOnTime,
        [skillGroupInterval].[AGENT_OUT_CALLS] AS AgentOutCalls,
        [skillGroupInterval].[TALK_OUT_TIME] AS TalkOutTime,
        [skillGroupInterval].[TALK_OTHER_TIME] AS TalkOtherTime,
        [skillGroupInterval].[AVAIL_TIME] AS AvailTime,
        [skillGroupInterval].[NOT_READY_TIME] AS NotReadyTime,
        [skillGroupInterval].[TRANSFER_IN_CALLS] AS TransferInCalls,
        [skillGroupInterval].[TALK_TIME] AS TalkTime,
        [skillGroupInterval].[TRANSFER_IN_CALLS_TIME] AS TransferInCallsTime,
        [skillGroupInterval].[WORK_READY_TIME] AS WorkReadyTime,
        [skillGroupInterval].[TRANSFER_OUT_CALLS] AS TransferOutCalls,
        [skillGroupInterval].[WORK_NOT_READY_TIME] AS WorkNotReadyTime,
        NULL AS RecoveryDay,
        [skillGroupInterval].[RECOVERY_KEY] AS RecoveryKey,
        [skillGroupInterval].[BUSY_OTHER_TIME] AS BusyOtherTime,
        [skillGroupInterval].[CALLS_ANSWERED] AS CallsAnswered,
        [skillGroupInterval].[RESERVED_STATE_TIME] AS ReservedStateTime,
        [skillGroupInterval].[ANSWER_WAIT_TIME] AS AnswerWaitTime,
        [skillGroupInterval].[ABANDON_RING_CALLS] AS AbandonRingCalls,
        [skillGroupInterval].[ABANDON_RING_TIME] AS AbandonRingTime,
        [skillGroupInterval].[ABANDON_HOLD_CALLS] AS AbandonHoldCalls,
        [skillGroupInterval].[AGENT_OUT_CALLS_TALK_TIME] AS AgentOutCallsTalkTime,
        [skillGroupInterval].[AGENT_OUT_CALLS_ON_HOLD] AS AgentOutCallsOnHold,
        [skillGroupInterval].[AGENT_OUT_CALLS_ON_HOLD_TIME] AS AgentOutCallsOnHoldTime,
        [skillGroupInterval].[AGENT_TERMINATED_CALLS] AS AgentTerminatedCalls,
        [skillGroupInterval].[CONSULTATIVE_CALLS] AS ConsultativeCalls,
        [skillGroupInterval].[CONSULTATIVE_CALLS_TIME] AS ConsultativeCallsTime,
        [skillGroupInterval].[CONFERENCED_IN_CALLS] AS ConferencedInCalls,
        [skillGroupInterval].[CONFERENCED_IN_CALLS_TIME] AS ConferencedInCallsTime,
        [skillGroupInterval].[CONFERENCED_OUT_CALLS] AS ConferencedOutCalls,
        [skillGroupInterval].[CONFERENCED_OUT_CALLS_TIME] AS ConferencedOutCallsTime,
        [skillGroupInterval].[INCOMING_CALLS_ON_HOLD_TIME] AS IncomingCallsOnHoldTime,
        [skillGroupInterval].[INCOMING_CALLS_ON_HOLD] AS IncomingCallsOnHold,
        [skillGroupInterval].[INTERNAL_CALLS_ON_HOLD_TIME] AS InternalCallsOnHoldTime,
        [skillGroupInterval].[INTERNAL_CALLS_ON_HOLD] AS InternalCallsOnHold,
        [skillGroupInterval].[INTERNAL_CALLS_RCVD_TIME] AS InternalCallsRcvdTime,
        [skillGroupInterval].[INTERNAL_CALLS_RCVD] AS InternalCallsRcvd,
        [skillGroupInterval].[REDIRECT_NO_ANS_CALLS] AS RedirectNoAnsCalls,
        [skillGroupInterval].[REDIRECT_NO_ANS_CALLS_TIME] AS RedirectNoAnsCallsTime,
        [skillGroupInterval].[SHORT_CALLS] AS ShortCalls,
        [skillGroupInterval].[ROUTER_CALLS_ABAND_Q] AS RouterCallsAbandQ,
        [skillGroupInterval].[ROUTER_QUEUE_CALLS] AS RouterQueueCalls,
        [skillGroupInterval].[AUTO_OUT_CALLS] AS AutoOutCalls,
        [skillGroupInterval].[AUTO_OUT_CALLS_TIME] AS AutoOutCallsTime,
        [skillGroupInterval].[AUTO_OUT_CALLS_TALK_TIME] AS AutoOutCallsTalkTime,
        [skillGroupInterval].[AUTO_OUT_CALLS_ON_HOLD] AS AutoOutCallsOnHold,
        [skillGroupInterval].[AUTO_OUT_CALLS_ON_HOLD_TIME] AS AutoOutCallsOnHoldTime,
        [skillGroupInterval].[PREVIEW_CALLS_TIME] AS PreviewCalls,
        [skillGroupInterval].[PREVIEW_CALLS] AS PreviewCallsTime,
        [skillGroupInterval].[PREVIEW_CALLS_TALK_TIME] AS PreviewCallsTalkTime,
        [skillGroupInterval].[PREVIEW_CALLS_ON_HOLD] AS PreviewCallsOnHoldTime,
        [skillGroupInterval].[PREVIEW_CALLS_ON_HOLD_TIME] AS PreviewCallsOnHold,
        [skillGroupInterval].[RESERVE_CALLS_TIME] AS ReserveCalls,
        [skillGroupInterval].[RESERVE_CALLS] AS ReserveCallsTime,
        [skillGroupInterval].[RESERVE_CALLS_TALK_TIME] AS ReserveCallsTalkTime,
        [skillGroupInterval].[RESERVE_CALLS_ON_HOLD] AS ReserveCallsOnHoldTime,
        [skillGroupInterval].[RESERVE_CALLS_ON_HOLD_TIME] AS ReserveCallsOnHold,
        [skillGroupInterval].[TALK_AUTO_OUT_TIME] AS TalkAutoOutTime,
        [skillGroupInterval].[TALK_PREVIEW_TIME] AS TalkPreviewTime,
        [skillGroupInterval].[TALK_RESERVE_TIME] AS TalkReserveTime,
        [skillGroupInterval].[BARGE_IN_CALLS] AS BargeInCalls,
        [skillGroupInterval].[INTERCEPT_CALLS] AS InterceptCalls,
        [skillGroupInterval].[MONITOR_CALLS] AS MonitorCalls,
        [skillGroupInterval].[WHISPER_CALLS] AS WhisperCalls,
        [skillGroupInterval].[EMERGENCY_ASSISTS] AS EmergencyAssists,
        [skillGroupInterval].[CALLS_OFFERED] AS CallsOffered,
        [skillGroupInterval].[CALLS_QUEUED] AS CallsQueued,
        [skillGroupInterval].[INTERRUPTED_TIME] AS InterruptedTime,
        [skillGroupInterval].[ABANDON_HOLD_CALLS_OUT] AS AbandonHoldCallsOut,
        [skillGroupInterval].[NET_CONSULTATIVE_CALLS] AS NetConsultativeCalls,
        [skillGroupInterval].[NET_CONSULTATIVE_CALLS_TIME] AS NetConsultativeCallsTime,
        [skillGroupInterval].[NET_CONFERENCED_OUT_CALLS] AS NetConferencedOutCalls,
        [skillGroupInterval].[NET_CONFERENCED_OUT_CALLS_TIME] AS NetConfOutCallsTime,
        [skillGroupInterval].[NET_TRANSFER_OUT_CALLS] AS NetTransferOutCalls,
        [skillGroupInterval].[DB_DATETIME] AS DbDateTime,
        [skillGroupInterval].[ROUTER_CALLS_OFFERED] AS RouterCallsOffered,
        [skillGroupInterval].[ROUTER_CALLS_ABANDON_TO_AGENT] AS RouterCallsAbandToAgent,
        [skillGroupInterval].[ROUTER_CALLS_DEQUEUED] AS RouterCallsDequeued,
        [skillGroupInterval].[ROUTER_ERROR] AS RouterError,
        [skillGroupInterval].[SERVICE_LEVEL] AS ServiceLevel,
        [skillGroupInterval].[SERVICE_LEVEL_CALLS] AS ServiceLevelCalls,
        [skillGroupInterval].[SERVICE_LEVEL_CALLS_ABANDON] AS ServiceLevelCallsAband,
        [skillGroupInterval].[SERVICE_LEVEL_CALLS_DEQUEUED] AS ServiceLevelCallsDequeue,
        [skillGroupInterval].[SERVICE_LEVEL_ERROR] AS ServiceLevelError,
        [skillGroupInterval].[SERVICE_LEVEL_RONA] AS ServiceLevelRONA,
        [skillGroupInterval].[SERVICE_LEVEL_CALLS_OFFERED] AS ServiceLevelCallsOffered,
        NULL AS Reserved1,
        NULL AS Reserved2,
        NULL AS Reserved3,
        NULL AS Reserved4,
        NULL AS Reserved5,
        CAST([campaign].[PKEY1] AS INT) AS CampaignID,
        [skillGroupInterval].[ROUTER_CALLS_ABAND_DEQUEUED] AS RouterCallsAbandDequeued,
        [skillGroupInterval].[REPORTING_HALF_HOUR] AS ReportingHalfHour,
        [skillGroupInterval].[REPORTING_INTERVAL] AS ReportingInterval,
        CAST([bucketInterval].[PKEY1] AS INT) AS BucketIntervalID,
        [skillGroupInterval].[CONSULT_OUT_CALLS] AS ConsultOutCalls,
        [skillGroupInterval].[CONSULT_OUT_CALLS_TIME] AS ConsultOutCallsTime,
        [skillGroupInterval].[ROUTER_DELAY_Q_ABAND_TIME] AS RouterDelayQAbandTime,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_1] AS RouterAbandInterval1,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_2] AS RouterAbandInterval2,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_3] AS RouterAbandInterval3,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_4] AS RouterAbandInterval4,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_5] AS RouterAbandInterval5,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_6] AS RouterAbandInterval6,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_7] AS RouterAbandInterval7,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_8] AS RouterAbandInterval8,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_9] AS RouterAbandInterval9,
        [skillGroupInterval].[ROUTER_ABAND_INTERVAL_10] AS RouterAbandInterval10,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_1] AS RouterAnsInterval1,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_2] AS RouterAnsInterval2,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_3] AS RouterAnsInterval3,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_4] AS RouterAnsInterval4,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_5] AS RouterAnsInterval5,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_6] AS RouterAnsInterval6,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_7] AS RouterAnsInterval7,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_8] AS RouterAnsInterval8,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_9] AS RouterAnsInterval9,
        [skillGroupInterval].[ROUTER_ANS_INTERVAL_10] AS RouterAnsInterval10,
        [skillGroupInterval].[ROUTER_MAX_CALLS_QUEUED] AS RouterMaxCallsQueued,
        [skillGroupInterval].[ROUTER_MAX_CALL_WAIT_TIME] RouterMaxCallWaitTime
FROM    [dbo].[VW_PARTITIONED_SUM_SKILLGROUP_INTERVAL] AS skillGroupInterval
JOIN    [dbo].[VW_DIM_SKILLGROUP_PKEY] AS skillGroup ON [skillGroup].[ITEM_URN] = [skillGroupInterval].[SKILLGROUP_URN]
                                                        AND [skillGroup].[PKEY_LATEST] = 1
LEFT JOIN [dbo].[VW_DIM_CAMPAIGN_PKEY] AS campaign ON [campaign].[ITEM_URN] = [skillGroupInterval].[CAMPAIGN_URN]
                                                      AND [campaign].[PKEY_LATEST] = 1
LEFT JOIN [dbo].[VW_DIM_BUCKET_INTERVAL_PKEY] AS bucketInterval ON [bucketInterval].[ITEM_URN] = [skillGroupInterval].[BUCKET_INTERVAL_URN]
                                                              AND [bucketInterval].[PKEY_LATEST] = 1;
GO
