SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_SLA_CHANNEL_TYPE_CUBE]
AS
-- WHERE POSSIBLE, SLA_CHANNEL_TYPE_URN IS THE PKEY1 FROM TB_DIM_CODE_PKEY_MAP FOR CG_ACTIVITY_TYPE CODE GROUPS
    SELECT  CAST([a].[SLA_CHANNEL_TYPE_URN] AS BIGINT) AS [SLA_CHANNEL_TYPE_URN],
            CAST([a].[CHANNEL_TYPE_NAME] AS NVARCHAR(50)) AS [CHANNEL_TYPE_NAME],
            CAST([a].[CHANNEL_TYPE_DESCRIPTION] AS NVARCHAR(500)) AS [CHANNEL_TYPE_DESCRIPTION],
            CAST([a].[CHANNEL_APPLICATION_ID] AS BIGINT) AS [CHANNEL_APPLICATION_ID]
    FROM    ( VALUES ( -10, 'Amazon Connect', 'Amazon Connect', -1), ( 2000, 'eGain Chat', 'eGain - Covers CHAT and VIDEO_CHAT', 80),
            ( 1, 'eGain Email', 'eGain - Covers MAIL', 90), ( 12000, 'eGain CallTrack', 'eGain - Covers CALL_TRACKING', 180),
            ( 20000, 'eGain Social', 'eGain - Covers SOCIAL and SOCIAL_AGENT', 20000) ) [a] ( [SLA_CHANNEL_TYPE_URN], [CHANNEL_TYPE_NAME], [CHANNEL_TYPE_DESCRIPTION], [CHANNEL_APPLICATION_ID] );
GO
GRANT SELECT
	ON [dbo].[VW_DIM_SLA_CHANNEL_TYPE_CUBE]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[VW_DIM_SLA_CHANNEL_TYPE_CUBE]
	TO [portal_default_mediator_role]
GO
