SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VW_DIM_TIME_CUBE
AS
SELECT  t.TIME_URN,
        HOUR = CONVERT(CHAR(2), r.INTERNAL_NAME),
        t.MINUTE AS MIN,
        HALFHOUR = CONVERT(CHAR(5), h.INTERNAL_NAME),
        QUARTERHOUR = CONVERT(CHAR(5), q.INTERNAL_NAME),
        FIVEMINUTE = CONVERT(CHAR(5), m.INTERNAL_NAME),
        MINUTE = CONVERT(CHAR(5), t.INTERNAL_NAME)
FROM    dbo.TB_DIM_TIME t
JOIN    dbo.TB_DIM_TIME_5M m ON m.FIVE_MINUTE_URN = t.FIVE_MINUTE_URN
JOIN    dbo.TB_DIM_TIME_QH q ON q.QUARTER_HOUR_URN = m.QUARTER_HOUR_URN
JOIN    dbo.TB_DIM_TIME_HH h ON h.HALF_HOUR_URN = q.HALF_HOUR_URN
JOIN    dbo.TB_DIM_TIME_H r ON r.HOUR_URN = h.HOUR_URN;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_TIME_CUBE]
	TO [portalapp_role]
GO
