SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_EMAIL_ACTIVITY_DETAIL_CUBE]
AS
SELECT  [PARTITION_URN],
        [CLUSTER_RESOURCE_URN],
        [ACTIVITY_ID],
        [ACTIVITY_STATE],
        [CASE_ID],
        [CASE_STATE],
        [CASE_SEVERITY],
        [TENANT_URN],
        [ALIAS_URN],
        [CUSTOMER_URN],
        [AGENT_URN],
        [PERSON_URN],
        [QUEUE_URN],
        [AGENT_TEAM_URN],
        [SKILLGROUP_URN],
        [IS_ESCALATED],
        [UNDELIVERABLE_MAIL],
        atc.[ACTIVITY_TYPE_CODE_URN],
        [ACTIVITY_SUB_TYPE_CODE_URN],
        [ACTIVITY_URN],
        [CASE_URN],
        [MANAGER_AGENT_URN],
        [MESSAGE_TYPE_URN],
        x.[DATE_UTC_URN],
        x.[TIME_UTC_URN],
        tzd.[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],
        CAST([ACTIVITY_DURATION] AS BIGINT) AS [Activity Duration],
        CAST([ASSIGNED_TO_QUEUE_CNTR] AS BIGINT) AS [Assigned to Queue Counter],
        CAST([ASSIGNED_TO_USER_CNTR] AS BIGINT) AS [Assigned to User Counter],
        CAST([AUTO_ACK_CNTR] AS BIGINT) AS [Auto ACK Counter],
        CAST([AUTO_REPLY_CNTR] AS BIGINT) AS [Auto Reply Counter],
        CAST([COMPLETED_CNTR] AS BIGINT) AS [Completed Counter],
        CAST([COMPLETED_METSLA_CNTR] AS BIGINT) AS [Completed SLA Met Counter],
        CAST([COMPLETED_NOTMETSLA_CNTR] AS BIGINT) AS [Completed SLA Not Met Counter],
        CAST([COMPOSE_CNTR] AS BIGINT) AS [Compose Counter],
        CAST([COMPOSE_SENT_CNTR] AS BIGINT) AS [Compose Sent Counter],
        CAST([EXISTING_CASE_CNTR] AS BIGINT) AS [Existing Case Counter],
        CAST([EXISTINGCASE_UNDELIVERABL_CNTR] AS BIGINT) AS [Existing Case Undeliverable Counter],
        CAST([FIRST_MANUAL_REPLY_CNTR] AS BIGINT) AS [First Manual Reply Counter],
        CAST([FIRST_MANUAL_REPLY_METSLA_CNTR] AS BIGINT) AS [First Manual Reply SLA Met Counter],
        CAST([FIRST_MAN_REPLY_NOTMETSLA_CNTR] AS BIGINT) AS [First Manual Reply SLA Not Met Counter],
        CAST([FIRST_MANUAL_REPLY_TIME] AS BIGINT) AS [First Manual Reply Time],
        CAST([MANUAL_REPLY_CNTR] AS BIGINT) AS [Manual Reply Counter],
        CAST([NEW_CASE_CNTR] AS BIGINT) AS [New Case Counter],
        CAST([NEWCASE_UNDELIVERABL_CNTR] AS BIGINT) AS [New Undeliverable Counter],
        CAST([TURNAROUND_TIME] AS BIGINT) AS [Turn Around Time],
        CAST([UNDISPATCHABL_MANUALREPLY_CNTR] AS BIGINT) AS [Undispatchable Manual Reply Counter],
        CAST([WORK_TIME] AS BIGINT) AS [Work Time],
        CAST([AUTHORIZED_CUSTOMER_REP_CNTR] AS BIGINT) AS [Authorized Customer Reply Counter], 
        CAST([NOTIFICATION_GENERATION_CNTR] AS BIGINT) AS [Notification Generation Counter], 
        CAST([TURNAROUND_CNTR] AS BIGINT) AS [Turn Around Counter], 
        CAST([HANDLED_CNTR] AS BIGINT) AS [Handled Counter], 
        CAST([HANDLED_TIME] AS BIGINT) AS [Handled Time],
        CAST([MANUAL_REPLY_TIME] AS BIGINT) AS [Manual Reply Time],
        CAST([WORK_STATE_TIME] AS BIGINT) AS [Work State Time],
        CAST([ACCEPTED_CNTR] AS BIGINT) AS [Accepted Counter],
        CAST([REJECTED_CNTR] AS BIGINT) AS [Rejected Counter],
        CAST([RESUBMITTED_CNTR] AS BIGINT) AS [Resubmitted Counter],
        CAST([REWORK_TIME] AS BIGINT) AS [ReWork Time],
        CAST([SUP_ACCEPTED_CNTR] AS BIGINT) AS [Supervisor Accepted Counter],
        CAST([SUP_REJECTED_CNTR] AS BIGINT) AS [Supervisor Rejected Counter],
        CAST([FIRST_MANUAL_REPLY_TIME_BIZCAL] AS BIGINT) AS [First Manual Reply Time BizCal],
        CAST([TURNAROUND_TIME_BIZCAL] AS BIGINT) AS [Turnaround Time BizCal],
        CAST([MANUAL_REPLY_TIME_BIZCAL] AS BIGINT) AS [Manual Reply Time BizCal],
        CAST([ACTIVITY_DURATION_BIZCAL] AS BIGINT) AS [Activity Duration BizCal],
        CAST([TURNAROUND_TIME_MET] AS BIGINT) AS [Turnaround Time Met],
        CAST([TURNAROUND_TIME_NOT_MET] AS BIGINT) AS [Turnaround Time Not Met],
        CAST([TURNAROUND_TIME_MET_BIZCAL] AS BIGINT) AS [Turnaround Time Met BizCal],
        CAST([TURNAROUND_TIME_NOT_MET_BIZCAL] AS BIGINT) AS [Turnaround Time Not Met BizCal],
        CAST([FORWARD_CNTR] AS BIGINT) AS [Forward Counter],
        CAST([REDIRECT_CNTR] AS BIGINT) AS [Redirect Counter],
        CAST([UNDISPATCHABLE_FORWARD_CNTR] AS BIGINT) AS [Undispatchable Forward Counter],
        CAST([UNDISPATCHABLE_REDIRECT_CNTR] AS BIGINT) AS [Undispatchable Redirect Counter],
        CAST([SECURE_REPLY_CNTR] AS BIGINT) AS [Secure Reply Counter],
        [PARTITION_ID],
        [Row Count],
       
        -- Custom Dimension columns
        [CUSTOM_DIMENSION_0] AS [CUSTOM_DIMENSION_0],
        [CUSTOM_DIMENSION_1] AS [CUSTOM_DIMENSION_1],
        [CUSTOM_DIMENSION_2] AS [CUSTOM_DIMENSION_2],
        [CUSTOM_DIMENSION_3] AS [CUSTOM_DIMENSION_3],
        [CUSTOM_DIMENSION_4] AS [CUSTOM_DIMENSION_4],
        [CUSTOM_DIMENSION_5] AS [CUSTOM_DIMENSION_5],
        [CUSTOM_DIMENSION_6] AS [CUSTOM_DIMENSION_6],
        [CUSTOM_DIMENSION_7] AS [CUSTOM_DIMENSION_7],
        [CUSTOM_DIMENSION_8] AS [CUSTOM_DIMENSION_8],
        [CUSTOM_DIMENSION_9] AS [CUSTOM_DIMENSION_9],
        CAST([CUSTOM_MEASURE_0] AS BIGINT) AS [Custom Measure 0],
        CAST([CUSTOM_MEASURE_1] AS BIGINT) AS [Custom Measure 1],
        CAST([CUSTOM_MEASURE_2] AS BIGINT) AS [Custom Measure 2],
        CAST([CUSTOM_MEASURE_3] AS BIGINT) AS [Custom Measure 3],
        CAST([CUSTOM_MEASURE_4] AS BIGINT) AS [Custom Measure 4],
        CAST([CUSTOM_MEASURE_5] AS BIGINT) AS [Custom Measure 5],
        CAST([CUSTOM_MEASURE_6] AS BIGINT) AS [Custom Measure 6],
        CAST([CUSTOM_MEASURE_7] AS BIGINT) AS [Custom Measure 7],
        CAST([CUSTOM_MEASURE_8] AS BIGINT) AS [Custom Measure 8],
        CAST([CUSTOM_MEASURE_9] AS BIGINT) AS [Custom Measure 9]
FROM    [dbo].[VW_FCT_EMAIL_ACTIVITY_DETAIL] x
INNER JOIN [dbo].[VW_DIM_TIME_STD_CUBE] tt ON x.[TIME_UTC_URN] = tt.[TIME_URN]
INNER JOIN [dbo].[TS_ADM_TIME_ZONE_DATA] tzd ON tzd.[DATE_UTC_URN] = x.[DATE_UTC_URN]
                                                AND tzd.[TIME_UTC_URN] = tt.[QUARTER_HOUR_URN]
CROSS APPLY ( SELECT TOP 1
                        c.[ITEM_BIZ_URN] AS [ACTIVITY_TYPE_CODE_URN]
              FROM      [dbo].[TB_DIM_CODE_GROUP] AS cg
              INNER JOIN [dbo].[TB_DIM_CODE_CODE_GROUP_MEMBER] AS m ON m.[PARENT_ITEM_BIZ_URN] = cg.[ITEM_BIZ_URN]
              INNER JOIN [dbo].[TB_DIM_CODE] AS c ON c.[ITEM_BIZ_URN] = m.[CHILD_ITEM_BIZ_URN]
              WHERE     cg.[INTERNAL_NAME] = 'CG_ACTIVITY_TYPE'
                        AND UPPER(c.[INTERNAL_NAME]) = 'EMAIL'
              ORDER BY c.[ITEM_URN]
            ) atc;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_EMAIL_ACTIVITY_DETAIL_CUBE]
	TO [portalapp_role]
GO
