SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_PROVISIONING_REQUEST]
AS
SELECT 
    [ID],
    [BATCH_ID],
    [CLUSTER_RESOURCE_ID],
    [RESOURCE_TYPE_ID],
    [RESOURCE_KEY_1],
    [RESOURCE_KEY_2],
    [OPERATION],
    [RECORD_NUMBER],
    [TOTAL_RECORDS],
    [COMPLETION_DATE],
    [RETRY_COUNT],
    [STATUS],
    [STATUS_MESSAGE],
    [CREATED_BY_ID],
    [MODIFIED_BY_ID],
    [CREATION_DATE],
    [MODIFIED_DATE],
    CONVERT(XML, [XML_DATA]) AS [XML_DATA],
    [PARTITION_URN],
    [PARTITION_GLOBAL_URN],
    [PARTITION_ID]    
FROM dbo.VW_PARTITIONED_FCT_PROVISIONING_REQUEST_ARCHIVE
UNION ALL
SELECT  
    [ID],
    [BATCH_ID],
    [CLUSTER_RESOURCE_ID],
    [RESOURCE_TYPE_ID],
    [RESOURCE_KEY_1],
    [RESOURCE_KEY_2],
    [OPERATION],
    [RECORD_NUMBER],
    [TOTAL_RECORDS],
    [COMPLETION_DATE],
    [RETRY_COUNT],
    [STATUS],
    [STATUS_MESSAGE],
    [CREATED_BY_ID],
    [MODIFIED_BY_ID],
    [CREATION_DATE],
    [MODIFIED_DATE],
    CONVERT(XML, [XML_DATA]) AS [XML_DATA],
    -1 AS [PARTITION_URN],
    -1 AS [PARTITION_GLOBAL_URN],
    0 AS [PARTITION_ID]
FROM dbo.TB_ADM_PROVISIONING_REQUEST;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_PROVISIONING_REQUEST]
	TO [portalreporting_role]
GO
