SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].VW_PARTITIONED_FCT_CUCM_CDR
AS
SELECT  *
FROM    dbo.TB_FCT_CUCM_CDR;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_CUCM_CDR]
	TO [portalreporting_role]
GO
