SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_SCL_ACTIVITY_DETAIL_CUBE]
AS
    SELECT  [x].[PARTITION_URN],
            [x].[CLUSTER_RESOURCE_URN],
            [x].[ACTIVITY_ID],
            [x].[CASE_ID],
            [x].[ACTIVITY_URN],
            [x].[CASE_URN],
            
            [x].[AGENT_URN],
            [x].[AGENT_TEAM_URN],
            [x].[PERSON_URN],
            [x].[QUEUE_URN],
            [x].[TENANT_URN],
            [x].[SCL_ADAPTER_URN],
            [x].[SCL_SEARCH_URN],
            [x].[SCL_ADAPTER_TYPE_CODE_URN],
            [x].[SCL_ADAPTER_TYPE_SUB_CODE_URN],
            [x].[MANAGER_AGENT_URN],
            [x].[DATE_UTC_URN],
            [x].[TIME_UTC_URN],
            [tzd].[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
            [tzd].[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],

            CAST([x].[ACTIVITY_DURATION] AS BIGINT) AS [Activity Duration],
            CAST([x].[ASSIGNED_TO_QUEUE_CNTR] AS BIGINT) AS [Assigned To Queue Counter],
            CAST([x].[ASSIGNED_TO_USER_CNTR] AS BIGINT) AS [Assigned To User Counter],
            CAST([x].[COMPLETED_CNTR] AS BIGINT) AS [Completed Counter],
            CAST([x].[COMPLETED_MET_SLA_CNTR] AS BIGINT) AS [Completed Met SLA Counter],
            CAST([x].[COMPLETED_NOT_MET_SLA_CNTR] AS BIGINT) AS [Completed Not Met SLA Counter],
            CAST([x].[COMPOSE_SENT_CNTR] AS BIGINT) AS [Compose Sent Counter],
            CAST([x].[COMPOSE_SENT_FOLLOW_UP_CNTR] AS BIGINT) AS [Compose Sent Follow Up Counter],
            CAST([x].[EXISTING_CASE_CNTR] AS BIGINT) AS [Existing Case Counter],
            CAST([x].[EXISTING_CASE_FOLLOW_UP_CNTR] AS BIGINT) AS [Existing Case Follow Up Counter],
            CAST([x].[FIRST_REPLY_TIME] AS BIGINT) AS [First Reply Time],
            CAST([x].[MANUAL_REPLY_CNTR] AS BIGINT) AS [Manual Reply Counter],
            CAST([x].[MANUAL_REPLY_FOLLOW_UP_CNTR] AS BIGINT) AS [Manual Reply Follow Up Counter],
            CAST([x].[MANUAL_REPLY_MET_SLA_CNTR] AS BIGINT) AS [Manual Reply Met SLA Counter],
            CAST([x].[MANUAL_REPLY_NOT_MET_SLA_CNTR] AS BIGINT) AS [Manual Reply Not Met SLA Counter],
            CAST([x].[NEW_CASE_CNTR] AS BIGINT) AS [New Case Counter],
            CAST([x].[PUBLISH_SENT_CNTR] AS BIGINT) AS [Publish Sent Counter],
            CAST([x].[PUBLISH_SENT_FOLLOW_UP_CNTR] AS BIGINT) AS [Publish Sent Follow Up Counter],
            CAST([x].[WORK_TIME] AS BIGINT) AS [Work Time],
            CAST([x].[TURNAROUND_CNTR] AS BIGINT) AS [Turnaround Counter],
            CAST([x].[TURNAROUND_TIME] AS BIGINT) AS [Turnaround Time],
            CAST([x].[WORK_STATE_TIME] AS BIGINT) AS [Work State Time],
            CAST([x].[FIRST_REPLY_TIME_BIZCAL] AS BIGINT) AS [First Reply Time BizCal],
            CAST([x].[TURNAROUND_TIME_BIZCAL] AS BIGINT) AS [Turnaround Time BizCal],
            CAST([x].[ACTIVITY_DURATION_BIZCAL] AS BIGINT) AS [Activity Duration BizCal],
            CAST([x].[TURNAROUND_TIME_MET] AS BIGINT) AS [Turnaround Time Met],
            CAST([x].[TURNAROUND_TIME_NOT_MET] AS BIGINT) AS [Turnaround Time Not Met],
            CAST([x].[TURNAROUND_TIME_MET_BIZCAL] AS BIGINT) AS [Turnaround Time Met BizCal],
            CAST([x].[TURNAROUND_TIME_NOT_MET_BIZCAL] AS BIGINT) AS [Turnaround Time Not Met BizCal],

            [x].[PARTITION_ID],
            [x].[Row Count],
            
            -- Custom Dimension columns
            [CUSTOM_ATTRIBUTE_0] AS [CUSTOM_ATTRIBUTE_0],
            [CUSTOM_ATTRIBUTE_1] AS [CUSTOM_ATTRIBUTE_1],
            [CUSTOM_ATTRIBUTE_2] AS [CUSTOM_ATTRIBUTE_2],
            [CUSTOM_ATTRIBUTE_3] AS [CUSTOM_ATTRIBUTE_3],
            [CUSTOM_ATTRIBUTE_4] AS [CUSTOM_ATTRIBUTE_4],
            [CUSTOM_ATTRIBUTE_5] AS [CUSTOM_ATTRIBUTE_5],
            [CUSTOM_ATTRIBUTE_6] AS [CUSTOM_ATTRIBUTE_6],
            [CUSTOM_ATTRIBUTE_7] AS [CUSTOM_ATTRIBUTE_7],
            [CUSTOM_ATTRIBUTE_8] AS [CUSTOM_ATTRIBUTE_8],
            [CUSTOM_ATTRIBUTE_9] AS [CUSTOM_ATTRIBUTE_9],
            CAST([CUSTOM_MEASURE_0] AS BIGINT) AS [Custom Measure 0],
            CAST([CUSTOM_MEASURE_1] AS BIGINT) AS [Custom Measure 1],
            CAST([CUSTOM_MEASURE_2] AS BIGINT) AS [Custom Measure 2],
            CAST([CUSTOM_MEASURE_3] AS BIGINT) AS [Custom Measure 3],
            CAST([CUSTOM_MEASURE_4] AS BIGINT) AS [Custom Measure 4],
            CAST([CUSTOM_MEASURE_5] AS BIGINT) AS [Custom Measure 5],
            CAST([CUSTOM_MEASURE_6] AS BIGINT) AS [Custom Measure 6],
            CAST([CUSTOM_MEASURE_7] AS BIGINT) AS [Custom Measure 7],
            CAST([CUSTOM_MEASURE_8] AS BIGINT) AS [Custom Measure 8],
            CAST([CUSTOM_MEASURE_9] AS BIGINT) AS [Custom Measure 9]
    FROM    [dbo].[VW_FCT_SCL_ACTIVITY_DETAIL] [x]
    INNER JOIN [dbo].[VW_DIM_TIME_STD_CUBE] [tt] ON [x].[TIME_UTC_URN] = [tt].[TIME_URN]
    INNER JOIN [dbo].[TS_ADM_TIME_ZONE_DATA] [tzd] ON [tzd].[DATE_UTC_URN] = [x].[DATE_UTC_URN]
                                                    AND [tzd].[TIME_UTC_URN] = [tt].[QUARTER_HOUR_URN];
GO
GRANT SELECT
	ON [dbo].[VW_FCT_SCL_ACTIVITY_DETAIL_CUBE]
	TO [portalapp_role]
GO
