SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VW_DIM_DATE_STD_CUBE
AS
SELECT  d.DATE_URN,
        d.INTERNAL_NAME AS DATE_KEY,
        d.NAME AS DATE_NAME,
        d.YEAR,
        d.MONTH,
        d.DAY,
        DATENAME(MONTH, d.DATE_VALUE) AS MONTH_NAME,
        DATENAME(WEEKDAY, d.DATE_VALUE) AS WEEKDAY_NAME,
        DATEPART(DAYOFYEAR, d.DATE_VALUE) AS DAY_OF_YEAR,
        DATEPART(WEEKDAY, d.DATE_VALUE) AS DAY_OF_WEEK,
        d.DATE_VALUE,
        d.DATE_FORMULA,
        d.DATE_OPTIONS,
        m.INTERNAL_NAME AS MONTH_KEY,
        m.NAME AS MONTH_KEY_NAME,
        DATEDIFF(DAY, m.PERIOD_START, m.PERIOD_END) + 1 AS DAYS_IN_MONTH,
        DATEDIFF(WEEK, m.PERIOD_START, m.PERIOD_END) AS WEEKS_IN_MONTH,
        m.PERIOD_START AS MONTH_START,
        m.PERIOD_END AS MONTH_END,
        m.DATE_FORMULA AS MONTH_FORMULA,
        m.DATE_OPTIONS AS MONTH_OPTIONS,
        q.INTERNAL_NAME AS QUARTER_KEY,
        q.NAME AS QUARTER_NAME,
        DATEDIFF(DAY, q.PERIOD_START, q.PERIOD_END) + 1 AS DAYS_IN_QUARTER,
        DATEDIFF(WEEK, q.PERIOD_START, q.PERIOD_END) AS WEEKS_IN_QUARTER,
        DATEDIFF(MONTH, q.PERIOD_START, q.PERIOD_END) + 1 AS MONTHS_IN_QUARTER,
        q.PERIOD_START AS QUARTER_START,
        q.PERIOD_END AS QUARTER_END,
        q.DATE_FORMULA AS QUARTER_FORMULA,
        q.DATE_OPTIONS AS QUARTER_OPTIONS,
        y.INTERNAL_NAME AS YEAR_KEY,
        y.NAME AS YEAR_NAME,
        DATEDIFF(DAY, y.PERIOD_START, y.PERIOD_END) + 1 AS DAYS_IN_YEAR,
        DATEDIFF(WEEK, y.PERIOD_START, y.PERIOD_END) AS WEEKS_IN_YEAR,
        DATEDIFF(MONTH, y.PERIOD_START, y.PERIOD_END) + 1 AS MONTHS_IN_YEAR,
        y.PERIOD_START AS YEAR_START,
        y.PERIOD_END AS YEAR_END,
        y.DATE_FORMULA AS YEAR_FORMULA,
        y.DATE_OPTIONS AS YEAR_OPTIONS,
        w.INTERNAL_NAME AS WEEK_KEY,
        w.NAME AS WEEK_NAME,
        w.PERIOD_START AS WEEK_START,
        w.PERIOD_END AS WEEK_END,
        w.DATE_FORMULA AS WEEK_FORMULA,
        w.DATE_OPTIONS AS WEEK_OPTIONS
FROM    dbo.TB_DIM_DATE d
JOIN    dbo.TB_DIM_DATE_STD_MONTH m ON m.MONTH_ID = d.STD_MONTH_ID
JOIN    dbo.TB_DIM_DATE_STD_QUARTER q ON q.QUARTER_ID = m.QUARTER_ID
JOIN    dbo.TB_DIM_DATE_STD_YEAR y ON y.YEAR_ID = q.YEAR_ID
JOIN    dbo.TB_DIM_DATE_STD_WEEK w ON w.WEEK_ID = d.STD_WEEK_ID;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_DATE_STD_CUBE]
	TO [portalapp_role]
GO
