SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_KNOWLEDGE_SS_SESSION_SUMMARY]
AS
   SELECT * FROM [dbo].[TB_FCT_KNOWLEDGE_SS_SESSION_SUMMARY];
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_KNOWLEDGE_SS_SESSION_SUMMARY]
	TO [portalreporting_role]
GO
