SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_ETL_AUDIT_PROPERTY]
--WITH ENCRYPTION
AS
SELECT  *
FROM    dbo.TB_FCT_ETL_AUDIT_PROPERTY;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_ETL_AUDIT_PROPERTY]
	TO [portalreporting_role]
GO
