SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_PRECISION_QUEUE_STEPS_ICM_PROV]
AS
SELECT  pqsm.CLUSTER_RESOURCE_ID,    
    
    -- Precision Queue Step -> Precision Queue member data
        pqsm.PKEY1 AS PQSPQ_PKEY1,
        pqsm.PKEY2 AS PQSPQ_PKEY2,
        pqsm.MEMBER_URN AS PQSPQ_MEMBER_URN,
        pqsm.PARENT_ITEM_BIZ_URN AS PQSPQ_PARENT_ITEM_BIZ_URN,
        pqsm.CHILD_ITEM_BIZ_URN AS PQSPQ_CHILD_ITEM_BIZ_URN,
        pqsm.MEMBER_BIZ_URN AS PQSPQ_BUSINESS_URN,
        pqsm.PKEY_MAP_URN AS PQSPQ_PKEY_MAP_URN,
        pqsm.PKEY_CHANGE_STAMP AS PQSPQ_PKEY_CHANGE_STAMP,
        CASE WHEN pqsm.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > pqsm.PKEY_EFFECTIVE_TO THEN 'P'
             ELSE pqsm.STATUS
        END AS PQSPQ_STATUS,
        CASE WHEN pqsm.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > pqsm.PKEY_EFFECTIVE_TO
             THEN CAST(1 AS BIT)
             ELSE CAST(0 AS BIT)
        END AS PQSPQ_EXPIRED,
        COALESCE(pqsm.SOURCE_CHANGE_STAMP, 0) AS PQSPQ_SOURCE_CHANGE_STAMP,

    -- Precision Queue Step data
        step.PKEY1 AS STEP_PKEY1,
        step.PKEY2 AS STEP_PKEY2,
        step.ITEM_URN AS STEP_ITEM_URN,
        step.ITEM_BIZ_URN AS STEP_BUSINESS_URN,
        step.DESCRIPTION AS STEP_DESCRIPTION,
        step.STEP_ORDER AS STEP_STEP_ORDER,
        step.WAIT_TIME AS STEP_WAIT_TIME,
        step.CONSIDER_IF AS STEP_CONSIDER_IF,
        step.NEXT_STEP AS STEP_NEXT_STEP,
        step.PKEY_MAP_URN AS STEP_PKEY_MAP_URN,
        step.PKEY_CHANGE_STAMP AS STEP_PKEY_CHANGE_STAMP,
        CASE WHEN step.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > step.PKEY_EFFECTIVE_TO THEN 'P'
             ELSE step.STATUS
        END AS STEP_STATUS,
        CASE WHEN step.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > step.PKEY_EFFECTIVE_TO
             THEN CAST(1 AS BIT)
             ELSE CAST(0 AS BIT)
        END AS STEP_EXPIRED,
        COALESCE(step.SOURCE_CHANGE_STAMP, 0) AS STEP_SOURCE_CHANGE_STAMP,

    -- Precision Queue Step -> Precision Attribute member data (Terms)
        pam.PKEY1 AS QSPA_PKEY1,
        pam.PKEY2 AS QSPA_PKEY2,
        pam.MEMBER_URN AS QSPA_MEMBER_URN,
        pam.PARENT_ITEM_BIZ_URN AS QSPA_PARENT_ITEM_BIZ_URN,
        pam.CHILD_ITEM_BIZ_URN AS QSPA_CHILD_ITEM_BIZ_URN,
        pam.MEMBER_BIZ_URN AS QSPA_BUSINESS_URN,
        pam.TERM_ORDER AS QSPA_TERM_ORDER,
        pam.PARENTHESES_COUNT AS QSPA_PARENTHESES_COUNT,
        pam.TERM_RELATION AS QSPA_TERM_RELATION,
        pam.ATTRIBUTE_RELATION AS QSPA_ATTRIBUTE_RELATION,
        pam.VALUE_1 AS QSPA_VALUE_1,
        pam.VALUE_2 AS QSPA_VALUE_2,
        pam.PKEY_MAP_URN AS QSPA_PKEY_MAP_URN,
        pam.PKEY_CHANGE_STAMP AS QSPA_PKEY_CHANGE_STAMP,
        CASE WHEN pam.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > pam.PKEY_EFFECTIVE_TO THEN 'P'
             ELSE pam.STATUS
        END AS QSPA_STATUS,
        CASE WHEN pam.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > pam.PKEY_EFFECTIVE_TO THEN CAST(1 AS BIT)
             ELSE CAST(0 AS BIT)
        END AS QSPA_EXPIRED,
        COALESCE(pam.SOURCE_CHANGE_STAMP, 0) AS QSPA_SOURCE_CHANGE_STAMP,
        pa.PKEY1 AS ATTRIBUTE_PKEY1
FROM    VW_DIM_PRECISION_QUEUE_STEP_PRECISION_QUEUE_MEMBER_PKEY pqsm
JOIN    VW_DIM_PRECISION_QUEUE_STEP_PKEY step ON pqsm.CHILD_ITEM_BIZ_URN = step.ITEM_BIZ_URN
JOIN    VW_DIM_PRECISION_QUEUE_STEP_PRECISION_ATTRIBUTE_MEMBER_PKEY pam ON pam.CHILD_ITEM_BIZ_URN = step.ITEM_BIZ_URN
JOIN    VW_DIM_PRECISION_ATTRIBUTE_PKEY pa ON pam.PARENT_ITEM_BIZ_URN = pa.ITEM_BIZ_URN
WHERE   pqsm.STATUS <> 'D'
        AND step.STATUS <> 'D'
        AND pam.STATUS <> 'D'
        AND pa.STATUS <> 'D';
GO
GRANT SELECT
	ON [dbo].[VW_DIM_PRECISION_QUEUE_STEPS_ICM_PROV]
	TO [portalapp_role]
GO
