SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_IVR_CALL_DAILY]
AS
SELECT  *
FROM    dbo.VW_PARTITIONED_SUM_IVR_CALL_DAILY;
GO
GRANT SELECT
	ON [dbo].[VW_SUM_IVR_CALL_DAILY]
	TO [portalreporting_role]
GO
