SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_SUB_CODE_PKEY_MAP_GC]
AS
SELECT  datagc.[PKEY_MAP_URN] AS [RESOURCE_ID],
        pkey.[ITEM_BIZ_URN] AS [CHILD_RESOURCE_ID],
        pkey.[CLUSTER_RESOURCE_ID] AS [PARENT_RESOURCE_ID],
        crt.[INTERNAL_NAME] AS CLUSTER_RESOURCE_TYPE_INTERNAL_NAME,
        CAST('0BD86837-0E52-4116-B8FD-857F6BE3CBD6' AS UNIQUEIDENTIFIER) AS [PARENT_RESOURCE_TYPE_ID], -- IT_CLUSTER_RESOURCE
        CAST('24fb83b4-a581-4642-a847-0ab90f78be38' AS UNIQUEIDENTIFIER) AS [CHILD_RESOURCE_TYPE_ID],
        pkey.[CLUSTER_VERSION],
        pkey.[STATUS],
        pkey.[CHANGE_STAMP],
        pkey.[PKEY1],
        pkey.[PKEY2],
        pkey.[EFFECTIVE_FROM],
        pkey.[EFFECTIVE_TO],
        pkey.[MODIFIED_DATE],
        pkey.[MODIFIED_BY_ID],
        pkey.[CREATION_DATE],
        pkey.[CREATED_BY_ID],
        pkey.[PURGED],
        pkey.[SYSTEM],
        pkey.[LATEST],
        pkey.[XML_DATA],
        pkey.[CUSTOM_XML_DATA],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_DIM_SUB_CODE_PKEY_MAP_GC] datagc
LEFT JOIN [dbo].[TB_DIM_SUB_CODE_PKEY_MAP] pkey ON pkey.PKEY_MAP_URN = datagc.PKEY_MAP_URN
LEFT JOIN [dbo].[TE_ADM_CLUSTER_RESOURCE_TYPE] crt ON crt.CLUSTER_RESOURCE_TYPE_ID = pkey.CLUSTER_RESOURCE_TYPE_ID;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_SUB_CODE_PKEY_MAP_GC]
	TO [portalapp_role]
GO
