SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_EMAIL_CASE_SNAPSHOT_CUBE]
--WITH ENCRYPTION
AS
   SELECT [PARTITION_URN],
          [CLUSTER_RESOURCE_URN],
          [TENANT_URN],
          [ALIAS_URN],
          [AGENT_URN],
          [MANAGER_AGENT_URN],
          [QUEUE_URN],

          x.[EVENT_DATE_UTC_URN],
          x.[EVENT_TIME_UTC_URN],
          tzd.[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
          tzd.[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],

          CAST([ASSIGNED_COUNT] AS BIGINT) AS [Assigned Count],
          CAST([AUTO_ACK_COUNT] AS BIGINT) AS [Auto ACK Count],
          CAST([AUTO_REPLY_COUNT] AS BIGINT) AS [Auto Reply Count],
          CAST([COMPLETED_COUNT] AS BIGINT) AS [Completed Count],
          CAST([COMPOSE_COUNT] AS BIGINT) AS [Compose Count],
          CAST([EMAIL_OPEN_COUNT] AS BIGINT) AS [Email Open Count],
          CAST([EMAIL_UNASSIGNED_COUNT] AS BIGINT) AS [Email Unassigned Count],
          CAST([EXISTING_CASE_COUNT] AS BIGINT) AS [Existing Case Counter],
          CAST([HANDLE_TIME] AS BIGINT) AS [Handle Time],
          CAST([MANUAL_REPLY_COUNT] AS BIGINT) AS [Manual Reply Count],
          CAST([NEW_CASE_COUNT] AS BIGINT) AS [New Case Count],
          CAST([RESPONDED_IN_SLA_COUNT] AS BIGINT) AS [Responded In SLA Count],
          CAST([RESPONSE_COUNT] AS BIGINT) AS [Response Count],
          CAST([RESPONSE_TIME] AS BIGINT) AS [Response Time],
          CAST([UNDELIVERED_MAIL_COUNT] AS BIGINT) AS [Undelivered Mail Count],
          [PARTITION_ID],
          [Row Count]
    FROM [dbo].[VW_FCT_EMAIL_CASE_SNAPSHOT] x 
    INNER JOIN [dbo].[VW_DIM_TIME_STD_CUBE] tt ON x.[EVENT_TIME_UTC_URN] = tt.[TIME_URN]
    INNER JOIN [dbo].[TS_ADM_TIME_ZONE_DATA] tzd ON tzd.[DATE_UTC_URN] = x.[EVENT_DATE_UTC_URN] AND tzd.[TIME_UTC_URN] = tt.[QUARTER_HOUR_URN];
GO
GRANT SELECT
	ON [dbo].[VW_FCT_EMAIL_CASE_SNAPSHOT_CUBE]
	TO [portalapp_role]
GO
