SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Agent_Skill_Group_Interval]
AS
SELECT  [agentSkillGroup].[DATE_TIME] AS [DateTime],
        CAST([agent].[PKEY1] AS INT) AS [SkillTargetID],
        CAST([skillGroup].[PKEY1] AS INT) AS [SkillGroupSkillTargetID],
        [agentSkillGroup].[TIME_ZONE] AS [TimeZone],
        [agentSkillGroup].[RECOVERY_KEY] AS [RecoveryKey],
        [agentSkillGroup].[ABANDON_RING_CALLS] AS [AbandonRingCalls],
        [agentSkillGroup].[ABANDON_RING_TIME] AS [AbandonRingTime],
        [agentSkillGroup].[ABANDON_HOLD_CALLS] AS [AbandonHoldCalls],
        [agentSkillGroup].[AGENT_OUT_CALLS_TIME] AS [AgentOutCallsTime],
        [agentSkillGroup].[AGENT_OUT_CALLS_TALK_TIME] AS [AgentOutCallsTalkTime],
        [agentSkillGroup].[AGENT_OUT_CALLS] AS [AgentOutCalls],
        [agentSkillGroup].[AGENT_OUT_CALLS_ON_HOLD] AS [AgentOutCallsOnHold],
        [agentSkillGroup].[AGENT_OUT_CALLS_ON_HOLD_TIME] AS [AgentOutCallsOnHoldTime],
        [agentSkillGroup].[AGENT_TERMINATED_CALLS] AS [AgentTerminatedCalls],
        [agentSkillGroup].[ANSWER_WAIT_TIME] AS [AnswerWaitTime],
        [agentSkillGroup].[AVAIL_TIME] AS [AvailTime],
        [agentSkillGroup].[BUSY_OTHER_TIME] AS [BusyOtherTime],
        [agentSkillGroup].[CALLBACK_MESSAGES_TIME] AS [CallbackMessagesTime],
        [agentSkillGroup].[CALLBACK_MESSAGES] AS [CallbackMessages],
        [agentSkillGroup].[CALLS_ANSWERED] AS [CallsAnswered],
        [agentSkillGroup].[CALLS_HANDLED] AS [CallsHandled],
        [agentSkillGroup].[CONSULTATIVE_CALLS] AS [ConsultativeCalls],
        [agentSkillGroup].[CONSULTATIVE_CALLS_TIME] AS [ConsultativeCallsTime],
        [agentSkillGroup].[CONFERENCED_IN_CALLS] AS [ConferencedInCalls],
        [agentSkillGroup].[CONFERENCED_IN_CALLS_TIME] AS [ConferencedInCallsTime],
        [agentSkillGroup].[CONFERENCED_OUT_CALLS] AS [ConferencedOutCalls],
        [agentSkillGroup].[CONFERENCED_OUT_CALLS_TIME] AS [ConferencedOutCallsTime],
        [agentSkillGroup].[HANDLED_CALLS_TALK_TIME] AS [HandledCallsTalkTime],
        [agentSkillGroup].[HANDLED_CALLS_TIME] AS [HandledCallsTime],
        [agentSkillGroup].[HOLD_TIME] AS [HoldTime],
        [agentSkillGroup].[INCOMING_CALLS_ON_HOLD_TIME] AS [IncomingCallsOnHoldTime],
        [agentSkillGroup].[INCOMING_CALLS_ON_HOLD] AS [IncomingCallsOnHold],
        [agentSkillGroup].[INTERNAL_CALLS_ON_HOLD_TIME] AS [InternalCallsOnHoldTime],
        [agentSkillGroup].[INTERNAL_CALLS_ON_HOLD] AS [InternalCallsOnHold],
        [agentSkillGroup].[INTERNAL_CALLS_RCVD_TIME] AS [InternalCallsRcvdTime],
        [agentSkillGroup].[INTERNAL_CALLS_RCVD] AS [InternalCallsRcvd],
        [agentSkillGroup].[INTERNAL_CALLS_TIME] AS [InternalCallsTime],
        [agentSkillGroup].[INTERNAL_CALLS] AS [InternalCalls],
        [agentSkillGroup].[LOGGED_ON_TIME] AS [LoggedOnTime],
        [agentSkillGroup].[NOT_READY_TIME] AS [NotReadyTime],
        [agentSkillGroup].[REDIRECT_NO_ANS_CALLS] AS [RedirectNoAnsCalls],
        [agentSkillGroup].[REDIRECT_NO_ANS_CALLS_TIME] AS [RedirectNoAnsCallsTime],
        [agentSkillGroup].[RESERVED_STATE_TIME] AS [ReservedStateTime],
        [agentSkillGroup].[SHORT_CALLS] AS [ShortCalls],
        [agentSkillGroup].[SUPERV_ASSIST_CALLS_TIME] AS [SupervAssistCallsTime],
        [agentSkillGroup].[SUPERV_ASSIST_CALLS] AS [SupervAssistCalls],
        [agentSkillGroup].[TALK_IN_TIME] AS [TalkInTime],
        [agentSkillGroup].[TALK_OTHER_TIME] AS [TalkOtherTime],
        [agentSkillGroup].[TALK_OUT_TIME] AS [TalkOutTime],
        [agentSkillGroup].[TRANSFERRED_IN_CALLS_TIME] AS [TransferredInCallsTime],
        [agentSkillGroup].[TRANSFERRED_IN_CALLS] AS [TransferredInCalls],
        [agentSkillGroup].[TRANSFERRED_OUT_CALLS] AS [TransferredOutCalls],
        [agentSkillGroup].[WORK_NOT_READY_TIME] AS [WorkNotReadyTime],
        [agentSkillGroup].[WORK_READY_TIME] AS [WorkReadyTime],
        [agentSkillGroup].[AUTO_OUT_CALLS] AS [AutoOutCalls],
        [agentSkillGroup].[AUTO_OUT_CALLS_TIME] AS [AutoOutCallsTime],
        [agentSkillGroup].[AUTO_OUT_CALLS_TALK_TIME] AS [AutoOutCallsTalkTime],
        [agentSkillGroup].[AUTO_OUT_CALLS_ON_HOLD] AS [AutoOutCallsOnHold],
        [agentSkillGroup].[AUTO_OUT_CALLS_ON_HOLD_TIME] AS [AutoOutCallsOnHoldTime],
        [agentSkillGroup].[PREVIEW_CALLS] AS [PreviewCalls],
        [agentSkillGroup].[PREVIEW_CALLS_TIME] AS [PreviewCallsTime],
        [agentSkillGroup].[PREVIEW_CALLS_TALK_TIME] AS [PreviewCallsTalkTime],
        [agentSkillGroup].[PREVIEW_CALLS_ON_HOLD] AS [PreviewCallsOnHold],
        [agentSkillGroup].[PREVIEW_CALLS_ON_HOLD_TIME] AS [PreviewCallsOnHoldTime],
        [agentSkillGroup].[RESERVE_CALLS] AS [ReserveCalls],
        [agentSkillGroup].[RESERVE_CALLS_TIME] AS [ReserveCallsTime],
        [agentSkillGroup].[RESERVE_CALLS_TALK_TIME] AS [ReserveCallsTalkTime],
        [agentSkillGroup].[RESERVE_CALLS_ON_HOLD] AS [ReserveCallsOnHold],
        [agentSkillGroup].[RESERVE_CALLS_ON_HOLD_TIME] AS [ReserveCallsOnHoldTime],
        [agentSkillGroup].[TALK_AUTO_OUT_TIME] AS [TalkAutoOutTime],
        [agentSkillGroup].[TALK_PREVIEW_TIME] AS [TalkPreviewTime],
        [agentSkillGroup].[TALK_RESERVE_TIME] AS [TalkReserveTime],
        [agentSkillGroup].[BARGE_IN_CALLS] AS [BargeInCalls],
        [agentSkillGroup].[INTERCEPT_CALLS] AS [InterceptCalls],
        [agentSkillGroup].[MONITOR_CALLS] AS [MonitorCalls],
        [agentSkillGroup].[WHISPER_CALLS] AS [WhisperCalls],
        [agentSkillGroup].[EMERGENCY_ASSISTS] AS [EmergencyAssists],
        [agentSkillGroup].[INTERRUPTED_TIME] AS [InterruptedTime],
        [agentSkillGroup].[ABANDON_HOLD_OUT_CALLS] AS [AbandonHoldOutCalls],
        [agentSkillGroup].[NET_CONSULTATIVE_CALLS] AS [NetConsultativeCalls],
        [agentSkillGroup].[NET_CONSULTATIVE_CALLS_TIME] AS [NetConsultativeCallsTime],
        [agentSkillGroup].[NET_CONFERENCED_OUT_CALLS] AS [NetConferencedOutCalls],
        [agentSkillGroup].[NET_CONFERENCED_OUT_CALLS_TIME] AS [NetConfOutCallsTime],
        [agentSkillGroup].[NET_TRANSFERED_OUT_CALLS] AS [NetTransferredOutCalls],
        [agentSkillGroup].[DB_DATETIME] AS [DbDateTime],
        NULL AS Reserved1,
        NULL AS Reserved2,
        NULL AS Reserved3,
        NULL AS Reserved4,
        NULL AS Reserved5,
        [agentSkillGroup].[REPORTING_HALF_HOUR] AS ReportingHalfHour,
        [agentSkillGroup].[REPORTING_INTERVAL] AS ReportingInterval
FROM    [dbo].[VW_PARTITIONED_SUM_AGENT_SKILLGROUP_INTERVAL] AS agentSkillGroup
        WITH ( NOLOCK )
JOIN    [dbo].[VW_DIM_AGENT_PKEY] AS agent WITH ( NOLOCK ) ON [agent].[ITEM_URN] = [agentSkillGroup].[AGENT_URN]
                                                              AND [agent].[PKEY_LATEST] = 1
JOIN    [dbo].[VW_DIM_SKILLGROUP_PKEY] AS skillGroup WITH ( NOLOCK ) ON [skillGroup].[ITEM_URN] = [agentSkillGroup].[SKILLGROUP_URN]
                                                              AND [skillGroup].[PKEY_LATEST] = 1;
GO
