SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_ADM_GADGET_SET_MAPPING_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS [RESOURCE_ID],
        map.GADGET_SET_ID AS PARENT_RESOURCE_ID,
        map.GADGET_ID AS CHILD_RESOURCE_ID,
        map.[GADGET_SET_MAPPING_JSON],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION],
        CAST('8AED4C24-0ABC-4BFA-8B41-7F5E78C3FF2B' AS UNIQUEIDENTIFIER) AS CHILD_RESOURCE_TYPE_ID, -- IT_GADGET
        CAST('E764A3A0-72EA-4B2A-8170-209F01D786A9' AS UNIQUEIDENTIFIER) AS PARENT_RESOURCE_TYPE_ID -- IT_GADGET_SET            
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
INNER JOIN [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT OUTER JOIN [dbo].[TB_ADM_GADGET_SET_MAPPING] map ON map.GADGET_SET_MAPPING_ID = datagc.GUID_KEY
WHERE   tablegc.TABLE_NAME = 'TB_ADM_GADGET_SET_MAPPING';
GO
GRANT SELECT
	ON [dbo].[VW_ADM_GADGET_SET_MAPPING_GC]
	TO [portalapp_role]
GO
