SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_IVR_CALLBACK]
AS
SELECT  *
FROM    dbo.TB_FCT_IVR_CALLBACK;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_IVR_CALLBACK]
	TO [portalreporting_role]
GO
