SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_ADM_TIME_ZONE_DATA_CHUNK]
AS
    SELECT TOP 5000
            *
    FROM    [dbo].[TS_ADM_TIME_ZONE_DATA]
    ORDER BY [DATETIME_UTC];
GO
