SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_EMAIL_DETAIL_CUBE]
AS
SELECT  [PARTITION_URN],
        [CLUSTER_RESOURCE_URN],
        [ACTIVITY_ID],
        [CASE_ID],
        [CASE_URN],
        [TENANT_URN],
        [AGENT_URN],
        [QUEUE_URN],
        [ALIAS_URN],
        [CASE_TYPE],
        [CUSTOMER_URN],
        [CONTACT_POINT_URN],
        [MESSAGE_TYPE_URN],
        atc.[ACTIVITY_TYPE_CODE_URN],
        [ACTIVITY_SUB_TYPE_CODE_URN],
        [ACTIVITY_PRIORITY],
        x.[COMPLETED_DATE_UTC_URN],
        x.[COMPLETED_TIME_UTC_URN],
        tzd.[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],
        [CREATED_TIME] AS [CREATED_DATE_TIME_UTC],
        [COMPLETED_DATE_TIME_UTC],
        CAST([AUTO_ACK_CNTR] AS BIGINT) AS [Auto Ack Counter],
        CAST([AUTO_REPLY_CNTR] AS BIGINT) AS [Auto Reply Counter],
        CAST([MANUAL_REPLY_CNTR] AS BIGINT) AS [Manual Reply Counter],
        CAST([FIRST_MANUAL_REPLY_TIME] AS BIGINT) AS [First Manual Reply Time],
        CAST([FIRST_MANUAL_REPLY_METSLA_CNTR] AS BIGINT) AS [First Manual Reply Met SLA Counter],
        CAST([COMPOSE_SENT_CNTR] AS BIGINT) AS [Compose Sent Counter],
        CAST([COMPLETED_CNTR] AS BIGINT) AS [Completed Counter],
        CAST([ACTIVITY_DURATION] AS BIGINT) AS [Activity Duration],
        CAST([COMPLETED_METSLA_CNTR] AS BIGINT) AS [Completed Met SLA Counter],
        CAST([HANDLED_TIME] AS BIGINT) AS [Handled Time],
        CAST([FORWARD_CNTR] AS BIGINT) AS [Forward Counter],
        CAST([REDIRECT_CNTR] AS BIGINT) AS [Redirect Counter],
        CAST([SECURE_REPLY_CNTR] AS BIGINT) AS [Secure Reply Counter],
        [PARTITION_ID],
        [Row Count]
FROM    [dbo].[VW_FCT_EMAIL_DETAIL] x
INNER JOIN [dbo].[VW_DIM_TIME_STD_CUBE] tt ON x.[COMPLETED_TIME_UTC_URN] = tt.[TIME_URN]
INNER JOIN [dbo].[TS_ADM_TIME_ZONE_DATA] tzd ON tzd.[DATE_UTC_URN] = x.[COMPLETED_DATE_UTC_URN]
                                                AND tzd.[TIME_UTC_URN] = tt.[QUARTER_HOUR_URN]
CROSS APPLY ( SELECT TOP 1
                        c.[ITEM_BIZ_URN] AS [ACTIVITY_TYPE_CODE_URN]
              FROM      [dbo].[TB_DIM_CODE_GROUP] AS cg
              INNER JOIN [dbo].[TB_DIM_CODE_CODE_GROUP_MEMBER] AS m ON m.[PARENT_ITEM_BIZ_URN] = cg.[ITEM_BIZ_URN]
              INNER JOIN [dbo].[TB_DIM_CODE] AS c ON c.[ITEM_BIZ_URN] = m.[CHILD_ITEM_BIZ_URN]
              WHERE     cg.[INTERNAL_NAME] = 'CG_ACTIVITY_TYPE'
                        AND UPPER(c.[INTERNAL_NAME]) = 'EMAIL'
              ORDER BY c.[ITEM_URN]
            ) atc;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_EMAIL_DETAIL_CUBE]
	TO [portalapp_role]
GO
