SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_VOICE_AGENT_STATE_INTERVAL_CUBE]
AS
SELECT 
    x.[PARTITION_URN],
    x.[CLUSTER_RESOURCE_URN],
    x.[AGENT_URN],
    x.[PERSON_URN],
    x.[QUEUE_URN],
    x.[CALL_DIRECTION_URN],
    x.[REASON_CODE_URN],
    x.[SERVICE_LEVEL_TYPE],

    x.[DATE_UTC_URN],
    x.[TIME_UTC_URN],
    tzd.[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],  
    tzd.[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
    tzd.[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],

    CAST(x.[AVAILABLE_STATE_TIME] AS BIGINT) AS [Available State Time],
    CAST(x.[HOLD_STATE_TIME] AS BIGINT) AS [Hold State Time],
    CAST(x.[LOGGED_ON_TIME] AS BIGINT) AS [Logged State Time],
    CAST(x.[RING_STATE_TIME] AS BIGINT) AS [Ring State Time],
    CAST(x.[TALK_STATE_TIME] AS BIGINT) AS [Talk State Time],
    CAST(x.[UNAVAILABLE_STATE_TIME] AS BIGINT) AS [Unavailable State Time],
    CAST(x.[WRAP_STATE_TIME] AS BIGINT) AS [Wrap State Time],

    x.[CUSTOM_DIMENSION_0] AS [CUSTOM_DIMENSION_0],
    x.[CUSTOM_DIMENSION_1] AS [CUSTOM_DIMENSION_1],
    x.[CUSTOM_DIMENSION_2] AS [CUSTOM_DIMENSION_2],
    x.[CUSTOM_DIMENSION_3] AS [CUSTOM_DIMENSION_3],
    x.[CUSTOM_DIMENSION_4] AS [CUSTOM_DIMENSION_4],
    x.[CUSTOM_DIMENSION_5] AS [CUSTOM_DIMENSION_5],
    x.[CUSTOM_DIMENSION_6] AS [CUSTOM_DIMENSION_6],
    x.[CUSTOM_DIMENSION_7] AS [CUSTOM_DIMENSION_7],
    x.[CUSTOM_DIMENSION_8] AS [CUSTOM_DIMENSION_8],
    x.[CUSTOM_DIMENSION_9] AS [CUSTOM_DIMENSION_9],
    CAST(x.[CUSTOM_MEASURE_0] AS BIGINT) AS [Custom Measure 0],  
    CAST(x.[CUSTOM_MEASURE_1] AS BIGINT) AS [Custom Measure 1],  
    CAST(x.[CUSTOM_MEASURE_2] AS BIGINT) AS [Custom Measure 2],  
    CAST(x.[CUSTOM_MEASURE_3] AS BIGINT) AS [Custom Measure 3],  
    CAST(x.[CUSTOM_MEASURE_4] AS BIGINT) AS [Custom Measure 4],  
    CAST(x.[CUSTOM_MEASURE_5] AS BIGINT) AS [Custom Measure 5],  
    CAST(x.[CUSTOM_MEASURE_6] AS BIGINT) AS [Custom Measure 6],  
    CAST(x.[CUSTOM_MEASURE_7] AS BIGINT) AS [Custom Measure 7],  
    CAST(x.[CUSTOM_MEASURE_8] AS BIGINT) AS [Custom Measure 8],  
    CAST(x.[CUSTOM_MEASURE_9] AS BIGINT) AS [Custom Measure 9],
    
    x.[PARTITION_ID],
    x.[Row Count]
FROM [dbo].[VW_SUM_VOICE_AGENT_STATE_INTERVAL] x
INNER JOIN [dbo].[VW_DIM_TIME_STD_CUBE] tt ON x.[TIME_UTC_URN] = tt.[TIME_URN]  
INNER JOIN [dbo].[TS_ADM_TIME_ZONE_DATA] tzd ON tzd.[DATE_UTC_URN] = x.[DATE_UTC_URN] AND tzd.[TIME_UTC_URN] = tt.[QUARTER_HOUR_URN];
GO
GRANT SELECT
	ON [dbo].[VW_SUM_VOICE_AGENT_STATE_INTERVAL_CUBE]
	TO [portalapp_role]
GO
