SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_CHAT]
--WITH ENCRYPTION
AS
SELECT  *
FROM    dbo.TB_FCT_CHAT;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_CHAT]
	TO [portalreporting_role]
GO
