SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[VW_DIM_AGENT_DESKTOP_PKEY]
WITH SCHEMABINDING
AS
    SELECT di.[ITEM_URN],
           di.[ITEM_BIZ_URN],
           di.[FOLDER_ID],
           fl.[PARENT_ID] AS [FOLDER_PARENT_ID],
           fl.[FOLDER_TYPE],
           fl.[DEPTH] AS [FOLDER_DEPTH],
           fl.[NAME] AS [FOLDER_NAME],
           fl.[PATH] AS [FOLDER_PATH],
           fl.[FOLDER_URN],
           di.[OWNER_ID],
           CAST('00009100-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID],
           di.[ITEM_SUBTYPE_ID],
           di.[NAME],    
           di.[DESCRIPTION] AS [BASE_DESCRIPTION],           
           di.[EFFECTIVE_FROM],
           di.[EFFECTIVE_TO],
           di.[XML_DATA],
           pk.[EFFECTIVE_FROM] AS [PKEY_EFFECTIVE_FROM],
           pk.[EFFECTIVE_TO] AS [PKEY_EFFECTIVE_TO],          
           pk.[INTERNAL_NAME],
           pk.[DESCRIPTION],
           pk.[AVAILABLE_AFTER_INCOMING],
           pk.[AVAILABLE_AFTER_OUTGOING],
           pk.[WRAPUP_DATA_INCOMING_MODE],
           pk.[WRAPUP_DATA_OUTGOING_MODE],
           pk.[AUTO_ANSWER_ENABLED],
           pk.[IDLE_REASON_REQUIRED],
           pk.[LOGOUT_NON_ACTIVITY_TIME],
           pk.[LOGOUT_REASON_REQUIRED],
           pk.[SUPERVISOR_CALLS_ALLOWED],
           pk.[SUPERVISOR_ASSIST_CALL_METHOD],
           pk.[EMERGENCY_CALL_METHOD],
           pk.[AUTO_RECORD_ON_EMERGENCY],
           pk.[AGENT_TO_AGENT_CALLS_ALLOWED],
           pk.[OUTBOUND_ACCESS_INTERNATIONAL],
           pk.[OUTBOUND_ACCESS_PUBLIC_NETWORK],
           pk.[OUTBOUND_ACCESS_PRIVATE_NETWORK],
           pk.[OUTBOUND_ACCESS_OPERATOR_ASSISTED],
           pk.[OUTBOUND_ACCESS_PBX],
           pk.[NON_ACD_CALLS_ALLOWED],
           pk.[QUALITY_RECORDING_RATE],
           pk.[RECORDING_MODE],
           pk.[WORK_MODE_TIMER],
           pk.[RING_NO_ANSWER_TIME],
           pk.[SILENT_MONITOR_WARNING_MESSAGE],
           pk.[SILENT_MONITOR_AUDIBLE_INDICATION],
           pk.[DEFAULT_DEVICE_PORT_ADDRESS],
           pk.[AGENT_CAN_SELECT_GROUP],
           pk.[REMOTE_AGENT_TYPE],
           pk.[REMOTE_LOGIN_WITHOUT_DESKTOP],
           di.[DEPARTMENT_BIZ_URN],
           pk.[PLAY_ZIP_TONE],
           pk.[ACD_SHARED_LINE_USAGE],
           di.[TIME_ZONE_URN],
           di.[TENANT_BIZ_URN],
           di.[HIERARCHY_PARENT_URN],
           di.[DELETED],
           di.[HIDDEN],
           di.[SYSTEM],
           di.[LATEST],
           di.[CHANGE_STAMP] AS [BASE_CHANGE_STAMP],
           pk.[PKEY_MAP_URN],
           pk.[CLUSTER_RESOURCE_ID],
           pk.[STATUS],
           pk.[PKEY1],
           pk.[PKEY2], 
           pk.[SOURCE_CHANGE_STAMP],
           pk.[PURGED],
           pk.[LATEST] AS [PKEY_LATEST],
           pk.[MODIFIED_DATE],
           pk.[CHANGE_STAMP] AS [PKEY_CHANGE_STAMP],
           pk.[XML_DATA] AS [PKEY_XML_DATA]
    FROM [dbo].[TB_DIM_AGENT_DESKTOP] di
    JOIN [dbo].[TB_DIM_AGENT_DESKTOP_PKEY_MAP] pk ON di.[ITEM_BIZ_URN] = pk.[ITEM_BIZ_URN]
    JOIN [dbo].[TB_SEC_FOLDER] fl ON fl.[FOLDER_ID] = di.[FOLDER_ID];
GO
GRANT SELECT
	ON [dbo].[VW_DIM_AGENT_DESKTOP_PKEY]
	TO [portalapp_role]
GO
