SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VW_DIM_RESERVED_DIRECTORY_NUMBER
AS
SELECT  CASE ISNUMERIC(dn.[DIRECTORY_NUMBER_OR_PATTERN])
          WHEN 1
          THEN CAST(LEFT(dn.[DIRECTORY_NUMBER_OR_PATTERN], 18) AS BIGINT)
          ELSE 0
        END AS DIRECTORY_NUMBER_OR_PATTERN,
        dn.[CLUSTER_RESOURCE_ID],
        dn.[OWNER_ID]
FROM    dbo.VW_DIM_DIRECTORY_NUMBER_PKEY dn
WHERE   ISNUMERIC([DIRECTORY_NUMBER_OR_PATTERN]) = 1
        AND dn.[ITEM_URN] > 0
        AND dn.[LATEST] = 1
UNION
SELECT  CAST([RESERVED_NAME] AS BIGINT) AS DIRECTORY_NUMBER_OR_PATTERN,
        [CLUSTER_RESOURCE_ID],
        [OWNER_ID]
FROM    dbo.TB_DIM_RESERVED_NAME
WHERE   [COLUMN_NAME] = 'DIRECTORY_NUMBER_OR_PATTERN'
        AND [ITEM_TYPE_ID] = '00011100-1000-0000-0000-000000000010';
GO
GRANT SELECT
	ON [dbo].[VW_DIM_RESERVED_DIRECTORY_NUMBER]
	TO [portalapp_role]
GO
