SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_DIALER_INTERVAL]
AS
SELECT  [PARTITION_URN],
        [DIALER_URN],
        [CLUSTER_RESOURCE_URN],
        [DATE_URN],
        [TIME_URN],
        [DATE_UTC_URN],
        [TIME_UTC_URN],
        [DATE_TIME],
        [TIME_ZONE],
        [ABANDON_DETECT],
        [ABANDON_TO_IVR],
        [AGENT_CLOSED_DETECT],
        [AGENT_REJECTED_DETECT],
        [ANSWERING_MACHINE_DETECT],
        [BUSY_DETECT],
        [CALLBACK_COUNT],
        [CANCELLED_DETECT],
        [CONTACTS_DIALED],
        [CUSTOMER_ABANDON_DETECT],
        [CUSTOMER_NOT_HOME],
        [FAX_DETECT],
        [NETWORK_ANS_MACHINE_DETECT],
        [NO_ANSWER_DETECT],
        [NO_DIAL_TONE_DETECT],
        [NO_RINGBACK_DETECT],
        [PERSONAL_CALLBACK_COUNT],
        [WRONG_NUMBER_COUNT],
        [VOICE_DETECT],
        [SIT_TONE_DETECT],
        [DIALING_TIME],
        [IDLE_PORT_TIME],
        [RESERVE_PORT_TIME],
        [LOW_NOISE_VOLUME],
        [ALL_PORTS_BUSY_COUNT],
        [REPORTING_HALF_HOUR],
        [REPORTING_INTERVAL],
        [PARTITION_ID],
        1 AS [Row Count]
FROM    dbo.VW_PARTITIONED_SUM_DIALER_INTERVAL;
GO
GRANT SELECT
	ON [dbo].[VW_SUM_DIALER_INTERVAL]
	TO [portalreporting_role]
GO
