SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_EMAIL_CASE_SNAPSHOT]
--WITH ENCRYPTION
AS
    SELECT *, 1 AS [Row Count] FROM VW_PARTITIONED_FCT_EMAIL_CASE_SNAPSHOT;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_EMAIL_CASE_SNAPSHOT]
	TO [portalreporting_role]
GO
