SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_AGENT_INTERVAL]
AS
SELECT  [SUMMARIZED_URN],
        [DATE_URN],
        [TIME_URN],
        [DATE_UTC_URN],
        [TIME_UTC_URN],
        [AGENT_URN],
        [AGENT_TEAM_URN],
        [SUPERVISOR_AGENT_URN],
        [PERIPHERAL_URN],
        [PERSON_URN],
        [MEDIA_ROUTING_DOMAIN_URN],
        [CLUSTER_RESOURCE_URN],
        [DATE_TIME],
        [TIME_ZONE],
        [LOGGED_ON_TIME],
        [AVAIL_TIME],
        [NOT_READY_TIME],
        [TALK_OTHER_TIME],
        [AVAILABLE_IN_MRD_TIME],
        [ROUTABLE_IN_MRD_TIME],
        [ROUTER_CALLS_ABAND_Q],
        [ROUTER_CALLS_ABAND],
        [ROUTER_CALLS_ANSWERED],
        [ROUTER_CALLS_DEQUEUED],
        [ROUTER_CALLS_HANDLED],
        [ROUTER_CALLS_OFFERED],
        [ROUTER_CALLS_REDIRECTED],
        [ROUTER_ERROR],
        [ROUTER_Q_CALLS],
        [NON_ACD_LINE_CALLS_IN_COUNT],
        [NON_ACD_LINE_CALLS_OUT_COUNT],
        [NON_ACD_LINE_CALLS_IN_TIME],
        [NON_ACD_LINE_CALLS_OUT_TIME],
        [REPORTING_HALF_HOUR],
        [REPORTING_INTERVAL],
        [PARTITION_ID],
        1 AS [Row Count]
FROM    dbo.VW_PARTITIONED_SUM_AGENT_INTERVAL;
GO
GRANT SELECT
	ON [dbo].[VW_SUM_AGENT_INTERVAL]
	TO [portalreporting_role]
GO
