SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_VOICE_CDR_INTERVAL_CUBE]
AS
SELECT  [PARTITION_URN],
        [CLUSTER_RESOURCE_URN],
        [TENANT_URN],
        [CUSTOMER_URN],
        [DIALED_NUMBER_URN],
        [SCRIPT_URN],
        [QUEUE_URN],
        [SL_THRESHOLD],
        [SOURCE_QUEUE_URN],
        [ACTIVITY_QUEUE_URN],
        [AGENT_URN],
        [SOURCE_AGENT_URN],
        [PERSON_URN],
        [SOURCE_PERSON_URN],
        [AGENT_TEAM_URN],
        [SOURCE_AGENT_TEAM_URN],
        [ROUTING_PROFILE_URN],
        [SOURCE_ROUTING_PROFILE_URN],
        [ACTIVITY_SUB_TYPE_CODE_URN],
        [CAMPAIGN_URN],
        [IVR_SCRIPT_URN],
        [IVR_EXIT_POINT_URN],
        [CALL_ORIGIN_URN],
        [SERVICE_LEVEL_TYPE],
        x.[START_DATE_UTC_URN],
        CAST(x.[START_TIME_UTC_URN] AS SMALLINT) AS [START_TIME_UTC_URN],
        tzd.[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],
        
        CAST([NEW_CASES] AS BIGINT) AS [New Cases],
        CAST([EXISTING_CASES] AS BIGINT) AS [Existing Cases],
        CAST([CONTACTS] AS BIGINT) AS [Contacts],
        CAST([OFFERED_IVR] AS BIGINT) AS [Offered Ivr],
        CAST([TERMINATED_IVR] AS BIGINT) AS [Terminated Ivr],
        CAST([COMPLETED_IVR] AS BIGINT) AS [Completed Ivr],
        CAST([ABANDONED_IVR] AS BIGINT) AS [Abandoned Ivr],
        CAST([SUCCESSFUL_IVR] AS BIGINT) AS [Successful Ivr],
        CAST([OFFERED_QUEUE] AS BIGINT) AS [Offered Queue],
        CAST([CALLBACK_ACCEPTED] AS BIGINT) AS [Callback Accepted],
        CAST([OFFERED_CALLBACK] AS BIGINT) AS [Offered Callback],
        CAST([OFFERED_AGENT] AS BIGINT) AS [Offered Agent],
        CAST([ABANDONED_QUEUE] AS BIGINT) AS [Abandoned Queue],
        CAST([ABANDONED_AGENT] AS BIGINT) AS [Abandoned Agent],
        CAST([RONA] AS BIGINT) AS [Rona],
        CAST([MISSED] AS BIGINT) AS [Missed],
        CAST([ANSWERED] AS BIGINT) AS [Answered],
        CAST([HANDLED] AS BIGINT) AS [Handled],
        CAST([HOLD] AS BIGINT) AS [Hold],
        CAST([ABANDONED_HOLD] AS BIGINT) AS [Abandoned Hold],
        CAST([HOLD_COUNT] AS BIGINT) AS [Hold Count],
        CAST([SHORT_HANDLED] AS BIGINT) AS [Short Handled],
        CAST([AGENT_HUNG_UP] AS BIGINT) AS [Agent Hung Up],
        CAST([SL_OFFERED] AS BIGINT) AS [Service Level Offered],
        CAST([SL_HANDLED] AS BIGINT) AS [Service Level Handled],
        CAST([SL_ABANDONED] AS BIGINT) AS [Service Level Abandoned],
        CAST([SL_HANDLED_INCL_RONA] AS BIGINT) AS [Service Level Handled Incl Rona],
        CAST([SL_ABANDONED_INCL_RONA] AS BIGINT) AS [Service Level Abandoned Incl Rona],
        CAST([SL_RONA] AS BIGINT) AS [Service Level Rona],
        CAST([SL_ERROR] AS BIGINT) AS [Service Level Error],
        CAST([SHORT_ABANDONED] AS BIGINT) AS [Short Abandoned],
        CAST([ERROR] AS BIGINT) AS [Error],
        CAST([IVR_TIME] AS BIGINT) AS [Ivr Time],
        CAST([QUEUE_TIME] AS BIGINT) AS [Queue Time],
        CAST([RING_TIME] AS BIGINT) AS [Ring Time],
        CAST([ANSWER_WAIT_TIME] AS BIGINT) AS [Answer Wait Time],
        CAST([ABANDON_TIME] AS BIGINT) AS [Abandon Time],
        CAST([ANSWER_WAIT_TIME_INCL_RONA] AS BIGINT) AS [Answer Wait Time Incl Rona],
        CAST([ABANDON_TIME_INCL_RONA] AS BIGINT) AS [Abandon Time Incl Rona],
        CAST([TALK_TIME] AS BIGINT) AS [Talk Time],
        CAST([HOLD_TIME] AS BIGINT) AS [Hold Time],
        CAST([LONGEST_HOLD_TIME] AS BIGINT) AS [Longest Hold Time],
        CAST([WRAP_TIME] AS BIGINT) AS [Wrap Time],
        CAST([CONSULT_TIME] AS BIGINT) AS [Consult Time],
        CAST([CONFERENCE_TIME] AS BIGINT) AS [Conference Time],
        CAST([WORK_TIME] AS BIGINT) AS [Work Time],
        CAST([COLD_XFER_OUT] AS BIGINT) AS [Cold Xfer Out],
        CAST([COLD_XFER_IN] AS BIGINT) AS [Cold Xfer In],
        CAST([WARM_XFER_OUT] AS BIGINT) AS [Warm Xfer Out],
        CAST([WARM_XFER_IN] AS BIGINT) AS [Warm Xfer In],
        CAST([CONSULT_OUT] AS BIGINT) AS [Consult Out],
        CAST([CALLS_CONSULT_OUT] AS BIGINT) AS [Calls Consult Out],
        CAST([CONSULT_IN] AS BIGINT) AS [Consult In],
        CAST([CONFERENCE_OUT] AS BIGINT) AS [Conference Out],
        CAST([CALLS_CONFERENCE_OUT] AS BIGINT) AS [Calls Conference Out],
        CAST([CONFERENCE_IN] AS BIGINT) AS [Conference In],
        CAST([TRANSFER_OUT_ALL] AS BIGINT) AS [Transfer Out All],
        CAST([ANS_INTERVAL_1] AS BIGINT) AS [Answer Interval 1],
        CAST([ANS_INTERVAL_2] AS BIGINT) AS [Answer Interval 2],
        CAST([ANS_INTERVAL_3] AS BIGINT) AS [Answer Interval 3],
        CAST([ANS_INTERVAL_4] AS BIGINT) AS [Answer Interval 4],
        CAST([ANS_INTERVAL_5] AS BIGINT) AS [Answer Interval 5],
        CAST([ANS_INTERVAL_6] AS BIGINT) AS [Answer Interval 6],
        CAST([ANS_INTERVAL_7] AS BIGINT) AS [Answer Interval 7],
        CAST([ANS_INTERVAL_8] AS BIGINT) AS [Answer Interval 8],
        CAST([ANS_INTERVAL_9] AS BIGINT) AS [Answer Interval 9],
        CAST([ANS_INTERVAL_10] AS BIGINT) AS [Answer Interval 10],
        CAST([ABN_INTERVAL_1] AS BIGINT) AS [Abandon Interval 1],
        CAST([ABN_INTERVAL_2] AS BIGINT) AS [Abandon Interval 2],
        CAST([ABN_INTERVAL_3] AS BIGINT) AS [Abandon Interval 3],
        CAST([ABN_INTERVAL_4] AS BIGINT) AS [Abandon Interval 4],
        CAST([ABN_INTERVAL_5] AS BIGINT) AS [Abandon Interval 5],
        CAST([ABN_INTERVAL_6] AS BIGINT) AS [Abandon Interval 6],
        CAST([ABN_INTERVAL_7] AS BIGINT) AS [Abandon Interval 7],
        CAST([ABN_INTERVAL_8] AS BIGINT) AS [Abandon Interval 8],
        CAST([ABN_INTERVAL_9] AS BIGINT) AS [Abandon Interval 9],
        CAST([ABN_INTERVAL_10] AS BIGINT) AS [Abandon Interval 10],
        CAST([KNOWLEDGE_USED] AS BIGINT) AS [Knowledge Used],
        CAST([ARTICLES_USED] AS BIGINT) AS [Articles Used],
        CAST([COMPLETED] AS BIGINT) AS [Completed],
        CAST([COMPLETED_OUTSIDE_SLA] AS BIGINT) AS [Completed Outside Sla],
        CAST([COMPLETED_WITHIN_SLA] AS BIGINT) AS [Completed Within Sla],
        CAST([ACTIVITY_DURATION] AS BIGINT) AS [Activity Duration],
        CAST([WORKFLOW_ASSIGNED] AS BIGINT) AS [Workflow Assigned],
        CAST([QUEUE_ASSIGNED] AS BIGINT) AS [Queue Assigned],
        CAST([USER_ASSIGNED] AS BIGINT) AS [User Assigned],
        CAST([CALL_LOGS_IN] AS BIGINT) AS [Call Logs In],
        CAST([CALL_LOGS_OUT] AS BIGINT) AS [Call Logs Out],
        CAST([EXTERNAL_XFER_OUT] AS BIGINT) AS [External Transfer Out],
        CAST([CONSULT_IN_TIME] AS BIGINT) AS [Consult In Time],
        CAST([ANSWERED_ABANDONED] AS BIGINT) AS [Answered Abandoned],
        CAST([OVERFLOW_IN] AS BIGINT) AS [Overflow In],
        CAST([OVERFLOW_OUT] AS BIGINT) AS [Overflow Out],
        CAST([QUEUED] AS BIGINT) AS [Queued],
        CAST([CONSULT_IN_HANDLED] AS BIGINT) AS [Consult In Handled],
                
        [PARTITION_ID],
        [Row Count],
       
        -- Custom Dimension columns
        [CUSTOM_DIMENSION_0] AS [CUSTOM_DIMENSION_0],
        [CUSTOM_DIMENSION_1] AS [CUSTOM_DIMENSION_1],
        [CUSTOM_DIMENSION_2] AS [CUSTOM_DIMENSION_2],
        [CUSTOM_DIMENSION_3] AS [CUSTOM_DIMENSION_3],
        [CUSTOM_DIMENSION_4] AS [CUSTOM_DIMENSION_4],
        [CUSTOM_DIMENSION_5] AS [CUSTOM_DIMENSION_5],
        [CUSTOM_DIMENSION_6] AS [CUSTOM_DIMENSION_6],
        [CUSTOM_DIMENSION_7] AS [CUSTOM_DIMENSION_7],
        [CUSTOM_DIMENSION_8] AS [CUSTOM_DIMENSION_8],
        [CUSTOM_DIMENSION_9] AS [CUSTOM_DIMENSION_9],
        CAST([CUSTOM_MEASURE_0] AS BIGINT) AS [Custom Measure 0],
        CAST([CUSTOM_MEASURE_1] AS BIGINT) AS [Custom Measure 1],
        CAST([CUSTOM_MEASURE_2] AS BIGINT) AS [Custom Measure 2],
        CAST([CUSTOM_MEASURE_3] AS BIGINT) AS [Custom Measure 3],
        CAST([CUSTOM_MEASURE_4] AS BIGINT) AS [Custom Measure 4],
        CAST([CUSTOM_MEASURE_5] AS BIGINT) AS [Custom Measure 5],
        CAST([CUSTOM_MEASURE_6] AS BIGINT) AS [Custom Measure 6],
        CAST([CUSTOM_MEASURE_7] AS BIGINT) AS [Custom Measure 7],
        CAST([CUSTOM_MEASURE_8] AS BIGINT) AS [Custom Measure 8],
        CAST([CUSTOM_MEASURE_9] AS BIGINT) AS [Custom Measure 9]
FROM    [dbo].[VW_SUM_VOICE_CDR_INTERVAL] x
INNER JOIN [dbo].[VW_DIM_TIME_STD_CUBE] tt ON x.[START_TIME_UTC_URN] = tt.[TIME_URN]
INNER JOIN [dbo].[TS_ADM_TIME_ZONE_DATA] tzd ON tzd.[DATE_UTC_URN] = x.[START_DATE_UTC_URN]
                                                AND tzd.[TIME_UTC_URN] = tt.[QUARTER_HOUR_URN]
GO
GRANT SELECT
	ON [dbo].[VW_SUM_VOICE_CDR_INTERVAL_CUBE]
	TO [portalapp_role]
GO
