SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_KNOWLEDGE_ARTICLE_READ_CONFIRMATION_CUBE]
AS
SELECT [PARTITION_URN],
       [CLUSTER_RESOURCE_URN],
       [SKEY],
       [SESSION_ID],
       [TENANT_URN],
       [CUSTOMER_URN],
       [AGENT_URN],
       [PERSON_URN],
       [AGENT_TEAM_URN],
       [LANGUAGE_URN],
       [KB_FOLDER_URN],
       [KB_ARTICLE_URN],
       [KB_ACCESS_TYPE] AS [KB_ACCESS_TYPE_URN],
       [MANAGER_AGENT_URN],
       [KB_ARTICLE_TYPE_URN],
       [ARTICLE_TYPE_URN],

       x.[DATE_UTC_URN],
       x.[TIME_UTC_URN],
       tzd.[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
       tzd.[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],
       
       CAST([READ_CONFIRMATION_CNTR] AS BIGINT) AS [Read Confirmation Counter],
       
       [PARTITION_ID],
       [Row Count]
FROM [dbo].[VW_FCT_KNOWLEDGE_ARTICLE_READ_CONFIRMATION] x
INNER JOIN [dbo].[VW_DIM_TIME_STD_CUBE] tt ON x.[TIME_UTC_URN] = tt.[TIME_URN]
INNER JOIN [dbo].[TS_ADM_TIME_ZONE_DATA] tzd ON tzd.[DATE_UTC_URN] = x.[DATE_UTC_URN] AND tzd.[TIME_UTC_URN] = tt.[QUARTER_HOUR_URN];
GO
GRANT SELECT
	ON [dbo].[VW_FCT_KNOWLEDGE_ARTICLE_READ_CONFIRMATION_CUBE]
	TO [portalapp_role]
GO
