SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_ADM_GADGET_SET_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS RESOURCE_ID,
        gs.[FOLDER_ID] AS [CONTAINER_ID],
        gs.[NAME],
        gs.[GADGET_SET_JSON],
        gs.[SYSTEM],
        gs.[CHANGE_STAMP],
        gs.[CREATION_DATE],
        gs.[MODIFIED_DATE],
        gs.[CREATED_BY_ID],
        gs.[MODIFIED_BY_ID],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_ADM_GADGET_SET] gs ON gs.GADGET_SET_ID = datagc.GUID_KEY
WHERE   tablegc.TABLE_NAME = 'TB_ADM_GADGET_SET';
GO
GRANT SELECT
	ON [dbo].[VW_ADM_GADGET_SET_GC]
	TO [portalapp_role]
GO
