SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_ITEM_HIERARCHY_NODE_MEMBER_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[INT_KEY] AS RESOURCE_ID,
        hierarchyMember.[ITEM_URN] AS CHILD_RESOURCE_ID,
        childItemType.[ITEM_TYPE_ID] AS CHILD_RESOURCE_TYPE_ID,
        hierarchyMember.[HIERARCHY_NODE_URN] AS PARENT_RESOURCE_ID,
        CAST('00039552-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [PARENT_RESOURCE_TYPE_ID], -- IT_HIERARCHY_NODE
        hierarchyMember.[PRECEDENCE],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_DIM_ITEM_HIERARCHY_NODE_MEMBER] hierarchyMember ON hierarchyMember.MEMBER_URN = datagc.INT_KEY
LEFT JOIN [dbo].[TE_DIM_ITEM_TYPE] childItemType ON childItemType.ITEM_TYPE_URN = hierarchyMember.ITEM_TYPE_URN
WHERE   tablegc.TABLE_NAME = 'TB_DIM_ITEM_HIERARCHY_NODE_MEMBER';
GO
GRANT SELECT
	ON [dbo].[VW_DIM_ITEM_HIERARCHY_NODE_MEMBER_GC]
	TO [portalapp_role]
GO
