SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_ACTIVITY_ORIGIN_CUBE]
AS
SELECT  CAST(0 AS INT) AS ACTIVITY_ORIGIN_URN,
        'Reactive' AS [NAME],
        'Reactive Activity' AS [DESCRIPTION]
UNION
SELECT  CAST(1 AS INT) AS ACTIVITY_ORIGIN_URN,
        'Proactive' AS [NAME],
        'Proactive Activity' AS [DESCRIPTION];
GO
GRANT SELECT
	ON [dbo].[VW_DIM_ACTIVITY_ORIGIN_CUBE]
	TO [portalapp_role]
GO
