SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_KB_SEARCH_STRING]
WITH SCHEMABINDING
AS
SELECT  it.[ITEM_URN],
        it.[TENANT_BIZ_URN],
        tn.[NAME] AS [TENANT_NAME],
        it.[SEARCH_STRING]
FROM    [dbo].[TB_DIM_KB_SEARCH_STRING] it
JOIN    [dbo].[TB_DIM_TENANT] tn ON tn.[ITEM_URN] = it.[TENANT_BIZ_URN];
GO
GRANT SELECT
	ON [dbo].[VW_DIM_KB_SEARCH_STRING]
	TO [portalapp_role]
GO
