SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_EVNT_HIST_CASE_MGMT]
AS
   SELECT *, 1 AS [Row Count] FROM [dbo].[VW_PARTITIONED_FCT_EVNT_HIST_CASE_MGMT];
GO
GRANT SELECT
	ON [dbo].[VW_FCT_EVNT_HIST_CASE_MGMT]
	TO [portalreporting_role]
GO
