SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_ADM_DATA_GENERATION_COUNT]
WITH SCHEMABINDING
AS
    SELECT [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_ADM_DATA_GENERATION_COUNT]
    UNION ALL    
    SELECT 5000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_CLU_CONNECTION_GC]
    UNION ALL
    SELECT 1 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_GC]
    UNION ALL
    SELECT 1000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_PKEY_MAP_GC]
    UNION ALL
    SELECT 2 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_DESKTOP_GC]
    UNION ALL
    SELECT 2000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_DESKTOP_PKEY_MAP_GC]
    UNION ALL
    SELECT 3 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_TEAM_GC]
    UNION ALL
    SELECT 3000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_TEAM_PKEY_MAP_GC]
    UNION ALL
    SELECT 116 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ALIAS_GC]
    UNION ALL
    SELECT 116000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ALIAS_PKEY_MAP_GC]
    UNION ALL
    SELECT 4 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ANNOUNCEMENT_GC]
    UNION ALL
    SELECT 4000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ANNOUNCEMENT_PKEY_MAP_GC]
    UNION ALL
    SELECT 5 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_APPLICATION_GATEWAY_GC]
    UNION ALL
    SELECT 5000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_APPLICATION_GATEWAY_PKEY_MAP_GC]
    UNION ALL
    SELECT 6 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_APPLICATION_INSTANCE_GC]
    UNION ALL
    SELECT 6000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_APPLICATION_INSTANCE_PKEY_MAP_GC]
    UNION ALL
    SELECT 7 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_APPLICATION_USER_GC]
    UNION ALL
    SELECT 7000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_APPLICATION_USER_PKEY_MAP_GC]
    UNION ALL
    SELECT 8 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_BUCKET_INTERVAL_GC]
    UNION ALL
    SELECT 8000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_BUCKET_INTERVAL_PKEY_MAP_GC]
    UNION ALL
    SELECT 10 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_MANAGER_GROUP_GC]
    UNION ALL
    SELECT 10000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_MANAGER_GROUP_PKEY_MAP_GC]
    UNION ALL
    SELECT 11 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_SOURCE_GC]
    UNION ALL
    SELECT 11000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_SOURCE_PKEY_MAP_GC]
    UNION ALL
    SELECT 12 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_TYPE_GC]
    UNION ALL
    SELECT 12000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_TYPE_PKEY_MAP_GC]
    UNION ALL
    SELECT 9 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALLING_SEARCH_SPACE_GC]
    UNION ALL
    SELECT 9000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALLING_SEARCH_SPACE_PKEY_MAP_GC]
    UNION ALL
    SELECT 13 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CAMPAIGN_GC]
    UNION ALL
    SELECT 13000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CAMPAIGN_PKEY_MAP_GC]
    UNION ALL
    SELECT 14 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CATEGORY_GC]
    UNION ALL
    SELECT 14000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CATEGORY_PKEY_MAP_GC]
    UNION ALL
    SELECT 127 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CBR_RELEASE_GC]
    UNION ALL
    SELECT 127000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CBR_RELEASE_PKEY_MAP_GC]
    UNION ALL
    SELECT 15 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CHARGEBAND_GC]
    UNION ALL
    SELECT 15000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CHARGEBAND_PKEY_MAP_GC]
    UNION ALL
    SELECT 162 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CHAT_REFERRER_NAME_GC]
    UNION ALL
    SELECT 162000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CHAT_REFERRER_NAME_PKEY_MAP_GC]
    UNION ALL
    SELECT 163 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CHAT_REFERRER_URL_GC]
    UNION ALL
    SELECT 163000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CHAT_REFERRER_URL_PKEY_MAP_GC]
    UNION ALL
    SELECT 16 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CLI_GC]
    UNION ALL
    SELECT 16000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CLI_PKEY_MAP_GC]
    UNION ALL
    SELECT 161 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_COBROWSE_PAGE_GC]
    UNION ALL
    SELECT 161000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_COBROWSE_PAGE_PKEY_MAP_GC]
    UNION ALL
    SELECT 17 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CODE_GC]
    UNION ALL
    SELECT 17000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CODE_PKEY_MAP_GC]
    UNION ALL
    SELECT 18 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CODE_GROUP_GC]
    UNION ALL
    SELECT 18000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CODE_GROUP_PKEY_MAP_GC]
    UNION ALL
    SELECT 120 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CONTENT_URL_GC]
    UNION ALL
    SELECT 120000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CONTENT_URL_PKEY_MAP_GC]
    UNION ALL
    SELECT 19 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_GC]
    UNION ALL
    SELECT 19000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_PKEY_MAP_GC]
    UNION ALL
    SELECT 132 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE0_GC]
    UNION ALL
    SELECT 132000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE0_PKEY_MAP_GC]
    UNION ALL
    SELECT 133 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE1_GC]
    UNION ALL
    SELECT 133000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE1_PKEY_MAP_GC]
    UNION ALL
    SELECT 134 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE2_GC]
    UNION ALL
    SELECT 134000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE2_PKEY_MAP_GC]
    UNION ALL
    SELECT 135 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE3_GC]
    UNION ALL
    SELECT 135000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE3_PKEY_MAP_GC]
    UNION ALL
    SELECT 136 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE4_GC]
    UNION ALL
    SELECT 136000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE4_PKEY_MAP_GC]
    UNION ALL
    SELECT 137 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE5_GC]
    UNION ALL
    SELECT 137000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE5_PKEY_MAP_GC]
    UNION ALL
    SELECT 138 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE6_GC]
    UNION ALL
    SELECT 138000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE6_PKEY_MAP_GC]
    UNION ALL
    SELECT 139 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE7_GC]
    UNION ALL
    SELECT 139000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE7_PKEY_MAP_GC]
    UNION ALL
    SELECT 140 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE8_GC]
    UNION ALL
    SELECT 140000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE8_PKEY_MAP_GC]
    UNION ALL
    SELECT 141 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE9_GC]
    UNION ALL
    SELECT 141000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ATTRIBUTE9_PKEY_MAP_GC]
    UNION ALL
    SELECT 30 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ENTRY_GC]
    UNION ALL
    SELECT 30000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ENTRY_PKEY_MAP_GC]
    UNION ALL
    SELECT 20 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM0_GC]
    UNION ALL
    SELECT 20000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM0_PKEY_MAP_GC]
    UNION ALL
    SELECT 21 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM1_GC]
    UNION ALL
    SELECT 21000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM1_PKEY_MAP_GC]
    UNION ALL
    SELECT 22 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM2_GC]
    UNION ALL
    SELECT 22000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM2_PKEY_MAP_GC]
    UNION ALL
    SELECT 23 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM3_GC]
    UNION ALL
    SELECT 23000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM3_PKEY_MAP_GC]
    UNION ALL
    SELECT 24 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM4_GC]
    UNION ALL
    SELECT 24000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM4_PKEY_MAP_GC]
    UNION ALL
    SELECT 25 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM5_GC]
    UNION ALL
    SELECT 25000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM5_PKEY_MAP_GC]
    UNION ALL
    SELECT 26 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM6_GC]
    UNION ALL
    SELECT 26000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM6_PKEY_MAP_GC]
    UNION ALL
    SELECT 27 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM7_GC]
    UNION ALL
    SELECT 27000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM7_PKEY_MAP_GC]
    UNION ALL
    SELECT 28 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM8_GC]
    UNION ALL
    SELECT 28000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM8_PKEY_MAP_GC]
    UNION ALL
    SELECT 29 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM9_GC]
    UNION ALL
    SELECT 29000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM9_PKEY_MAP_GC]
    UNION ALL
    SELECT 31 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DATE_TIME_SETTING_GC]
    UNION ALL
    SELECT 31000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DATE_TIME_SETTING_PKEY_MAP_GC]
    UNION ALL
    SELECT 111 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEPARTMENT_GC]
    UNION ALL
    SELECT 111000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEPARTMENT_PKEY_MAP_GC]
    UNION ALL
    SELECT 32 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_POOL_GC]
    UNION ALL
    SELECT 32000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_POOL_PKEY_MAP_GC]
    UNION ALL
    SELECT 33 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_PROFILE_GC]
    UNION ALL
    SELECT 33000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_PROFILE_PKEY_MAP_GC]
    UNION ALL
    SELECT 34 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_TARGET_GC]
    UNION ALL
    SELECT 34000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_TARGET_PKEY_MAP_GC]
    UNION ALL
    SELECT 37 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIAL_NUMBER_PLAN_GC]
    UNION ALL
    SELECT 37000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIAL_NUMBER_PLAN_PKEY_MAP_GC]
    UNION ALL
    SELECT 35 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALED_NUMBER_GC]
    UNION ALL
    SELECT 35000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALED_NUMBER_PKEY_MAP_GC]
    UNION ALL
    SELECT 36 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALER_GC]
    UNION ALL
    SELECT 36000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALER_PKEY_MAP_GC]
    UNION ALL
    SELECT 38 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIRECTORY_NUMBER_GC]
    UNION ALL
    SELECT 38000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIRECTORY_NUMBER_PKEY_MAP_GC]
    UNION ALL
    SELECT 112 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DOCUMENT_GC]
    UNION ALL
    SELECT 157 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ECC_PAYLOAD_GC]
    UNION ALL
    SELECT 157000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ECC_PAYLOAD_PKEY_MAP_GC]
    UNION ALL
    SELECT 39 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_EMAIL_GC]
    UNION ALL
    SELECT 39000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_EMAIL_PKEY_MAP_GC]
    UNION ALL
    SELECT 40 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ENTERPRISE_ROUTE_GC]
    UNION ALL
    SELECT 40000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ENTERPRISE_ROUTE_PKEY_MAP_GC]
    UNION ALL
    SELECT 41 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ENTERPRISE_SERVICE_GC]
    UNION ALL
    SELECT 41000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ENTERPRISE_SERVICE_PKEY_MAP_GC]
    UNION ALL
    SELECT 42 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ENTERPRISE_SKILLGROUP_GC]
    UNION ALL
    SELECT 42000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ENTERPRISE_SKILLGROUP_PKEY_MAP_GC]
    UNION ALL
    SELECT 115 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ENTRY_POINT_GC]
    UNION ALL
    SELECT 115000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ENTRY_POINT_PKEY_MAP_GC]
    UNION ALL
    SELECT 43 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_EXPANDED_CALL_VARIABLE_GC]
    UNION ALL
    SELECT 43000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_EXPANDED_CALL_VARIABLE_PKEY_MAP_GC]
    UNION ALL
    SELECT 44 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_FILESHARE_GC]
    UNION ALL
    SELECT 44000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_FILESHARE_PKEY_MAP_GC]
    UNION ALL
    SELECT 46 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GATEWAY_FUNCTION_GC]
    UNION ALL
    SELECT 46000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GATEWAY_FUNCTION_PKEY_MAP_GC]
    UNION ALL
    SELECT 47 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GATEWAY_RESULT_GC]
    UNION ALL
    SELECT 47000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GATEWAY_RESULT_PKEY_MAP_GC]
    UNION ALL
    SELECT 48 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GATEWAY_SERVER_GC]
    UNION ALL
    SELECT 48000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GATEWAY_SERVER_PKEY_MAP_GC]
    UNION ALL
    SELECT 130 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_ANSWER_GC]
    UNION ALL
    SELECT 130000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_ANSWER_PKEY_MAP_GC]
    UNION ALL
    SELECT 164 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_CLUSTER_GC]
    UNION ALL
    SELECT 164000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_CLUSTER_PKEY_MAP_GC]
    UNION ALL
    SELECT 165 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_CLUSTER_GROUP_GC]
    UNION ALL
    SELECT 165000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_CLUSTER_GROUP_PKEY_MAP_GC]
    UNION ALL
    SELECT 129 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_QUESTION_GC]
    UNION ALL
    SELECT 129000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_QUESTION_PKEY_MAP_GC]
    UNION ALL
    SELECT 49 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_HIERARCHY_GC]
    UNION ALL
    SELECT 49000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_HIERARCHY_PKEY_MAP_GC]
    UNION ALL
    SELECT 50 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_HIERARCHY_NODE_GC]
    UNION ALL
    SELECT 50000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_HIERARCHY_NODE_PKEY_MAP_GC]
    UNION ALL
    SELECT 107 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_HUNT_PILOT_GC]
    UNION ALL
    SELECT 107000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_HUNT_PILOT_PKEY_MAP_GC]
    UNION ALL
    SELECT 51 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ICR_INSTANCE_GC]
    UNION ALL
    SELECT 51000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ICR_INSTANCE_PKEY_MAP_GC]
    UNION ALL
    SELECT 52 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IMPORT_RULE_GC]
    UNION ALL
    SELECT 52000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IMPORT_RULE_PKEY_MAP_GC]
    UNION ALL
    SELECT 53 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_GC]
    UNION ALL
    SELECT 53000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_PKEY_MAP_GC]
    UNION ALL
    SELECT 54 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_BUTTON_TEMPLATE_GC]
    UNION ALL
    SELECT 54000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_BUTTON_TEMPLATE_PKEY_MAP_GC]
    UNION ALL
    SELECT 55 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ENTRY_POINT_GC]
    UNION ALL
    SELECT 55000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ENTRY_POINT_PKEY_MAP_GC]
    UNION ALL
    SELECT 56 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_MODULE_GC]
    UNION ALL
    SELECT 56000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_MODULE_PKEY_MAP_GC]
    UNION ALL
    SELECT 57 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_QUEUE_GC]
    UNION ALL
    SELECT 57000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_QUEUE_PKEY_MAP_GC]
    UNION ALL
    SELECT 58 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ROUTING_TARGET_GC]
    UNION ALL
    SELECT 58000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ROUTING_TARGET_PKEY_MAP_GC]
    UNION ALL
    SELECT 59 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SCRIPT_GC]
    UNION ALL
    SELECT 59000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SCRIPT_PKEY_MAP_GC]
    UNION ALL
    SELECT 60 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SCRIPT_NODE_GC]
    UNION ALL
    SELECT 60000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SCRIPT_NODE_PKEY_MAP_GC]
    UNION ALL
    SELECT 61 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SCRIPT_NODE_EXIT_STATE_GC]
    UNION ALL
    SELECT 61000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SCRIPT_NODE_EXIT_STATE_PKEY_MAP_GC]
    UNION ALL
    SELECT 62 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SERVER_GC]
    UNION ALL
    SELECT 62000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SERVER_PKEY_MAP_GC]
    UNION ALL
    SELECT 123 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_ARTICLE_GC]
    UNION ALL
    SELECT 123000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_ARTICLE_PKEY_MAP_GC]
    UNION ALL
    SELECT 172 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_ARTICLE_REVIEW_STAGE_GC]
    UNION ALL
    SELECT 172000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_ARTICLE_REVIEW_STAGE_PKEY_MAP_GC]
    UNION ALL
    SELECT 158 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_ARTICLE_WORKFLOW_GC]
    UNION ALL
    SELECT 158000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_ARTICLE_WORKFLOW_PKEY_MAP_GC]
    UNION ALL
    SELECT 171 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_COMPLIANCE_POLICY_GC]
    UNION ALL
    SELECT 171000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_COMPLIANCE_POLICY_PKEY_MAP_GC]
    UNION ALL
    SELECT 124 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_FOLDER_GC]
    UNION ALL
    SELECT 124000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_FOLDER_PKEY_MAP_GC]
    UNION ALL
    SELECT 121 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_PORTAL_GC]
    UNION ALL
    SELECT 121000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_PORTAL_PKEY_MAP_GC]
    UNION ALL
    SELECT 122 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_TOPIC_GC]
    UNION ALL
    SELECT 122000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_TOPIC_PKEY_MAP_GC]
    UNION ALL
    SELECT 63 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_LABEL_GC]
    UNION ALL
    SELECT 63000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_LABEL_PKEY_MAP_GC]
    UNION ALL
    SELECT 64 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_LOGICAL_INTERFACE_CONTROLLER_GC]
    UNION ALL
    SELECT 64000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_LOGICAL_INTERFACE_CONTROLLER_PKEY_MAP_GC]
    UNION ALL
    SELECT 65 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MACHINE_GC]
    UNION ALL
    SELECT 65000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MACHINE_PKEY_MAP_GC]
    UNION ALL
    SELECT 66 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MACHINE_RESOURCE_GC]
    UNION ALL
    SELECT 66000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MACHINE_RESOURCE_PKEY_MAP_GC]
    UNION ALL
    SELECT 67 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIA_CLASS_GC]
    UNION ALL
    SELECT 67000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIA_CLASS_PKEY_MAP_GC]
    UNION ALL
    SELECT 68 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIA_ROUTING_DOMAIN_GC]
    UNION ALL
    SELECT 68000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIA_ROUTING_DOMAIN_PKEY_MAP_GC]
    UNION ALL
    SELECT 108 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIAFILE_GC]
    UNION ALL
    SELECT 108000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIAFILE_PKEY_MAP_GC]
    UNION ALL
    SELECT 109 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIAFILE_SERVER_GC]
    UNION ALL
    SELECT 109000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIAFILE_SERVER_PKEY_MAP_GC]
    UNION ALL
    SELECT 69 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NETWORK_TRUNK_GROUP_GC]
    UNION ALL
    SELECT 69000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NETWORK_TRUNK_GROUP_PKEY_MAP_GC]
    UNION ALL
    SELECT 70 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NETWORK_VRU_GC]
    UNION ALL
    SELECT 70000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NETWORK_VRU_PKEY_MAP_GC]
    UNION ALL
    SELECT 71 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NETWORK_VRU_SCRIPT_GC]
    UNION ALL
    SELECT 71000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NETWORK_VRU_SCRIPT_PKEY_MAP_GC]
    UNION ALL
    SELECT 125 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NOTIFY_CATEGORY_GC]
    UNION ALL
    SELECT 125000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NOTIFY_CATEGORY_PKEY_MAP_GC]
    UNION ALL
    SELECT 159 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NOTIFY_CHANNEL_GC]
    UNION ALL
    SELECT 159000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NOTIFY_CHANNEL_PKEY_MAP_GC]
    UNION ALL
    SELECT 128 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NOTIFY_MESSAGE_TYPE_GC]
    UNION ALL
    SELECT 128000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NOTIFY_MESSAGE_TYPE_PKEY_MAP_GC]
    UNION ALL
    SELECT 160 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NOTIFY_ORIGIN_GC]
    UNION ALL
    SELECT 160000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NOTIFY_ORIGIN_PKEY_MAP_GC]
    UNION ALL
    SELECT 72 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_OBJECT_TYPE_GC]
    UNION ALL
    SELECT 72000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_OBJECT_TYPE_PKEY_MAP_GC]
    UNION ALL
    SELECT 118 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_OFFER_GC]
    UNION ALL
    SELECT 118000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_OFFER_PKEY_MAP_GC]
    UNION ALL
    SELECT 119 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_OFFER_BANNER_GC]
    UNION ALL
    SELECT 119000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_OFFER_BANNER_PKEY_MAP_GC]
    UNION ALL
    SELECT 73 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PERIPHERAL_GC]
    UNION ALL
    SELECT 73000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PERIPHERAL_PKEY_MAP_GC]
    UNION ALL
    SELECT 74 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PERSON_GC]
    UNION ALL
    SELECT 74000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PERSON_PKEY_MAP_GC]
    UNION ALL
    SELECT 75 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PHYSICAL_INTERFACE_CONTROLLER_GC]
    UNION ALL
    SELECT 75000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PHYSICAL_INTERFACE_CONTROLLER_PKEY_MAP_GC]
    UNION ALL
    SELECT 76 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PORT_GC]
    UNION ALL
    SELECT 76000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PORT_PKEY_MAP_GC]
    UNION ALL
    SELECT 77 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_ATTRIBUTE_GC]
    UNION ALL
    SELECT 77000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_ATTRIBUTE_PKEY_MAP_GC]
    UNION ALL
    SELECT 78 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_GC]
    UNION ALL
    SELECT 78000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_PKEY_MAP_GC]
    UNION ALL
    SELECT 79 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_STEP_GC]
    UNION ALL
    SELECT 79000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_STEP_PKEY_MAP_GC]
    UNION ALL
    SELECT 81 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_QUERY_RULE_GC]
    UNION ALL
    SELECT 81000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_QUERY_RULE_PKEY_MAP_GC]
    UNION ALL
    SELECT 113 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_QUEUE_GC]
    UNION ALL
    SELECT 113000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_QUEUE_PKEY_MAP_GC]
    UNION ALL
    SELECT 83 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_RATING_PERIOD_GC]
    UNION ALL
    SELECT 83000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_RATING_PERIOD_PKEY_MAP_GC]
    UNION ALL
    SELECT 84 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_REASON_CODE_GC]
    UNION ALL
    SELECT 84000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_REASON_CODE_PKEY_MAP_GC]
    UNION ALL
    SELECT 85 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_REGION_GC]
    UNION ALL
    SELECT 85000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_REGION_PKEY_MAP_GC]
    UNION ALL
    SELECT 86 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_GC]
    UNION ALL
    SELECT 86000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_PKEY_MAP_GC]
    UNION ALL
    SELECT 87 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_PARTITION_GC]
    UNION ALL
    SELECT 87000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_PARTITION_PKEY_MAP_GC]
    UNION ALL
    SELECT 88 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTING_CLIENT_GC]
    UNION ALL
    SELECT 88000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTING_CLIENT_PKEY_MAP_GC]
    UNION ALL
    SELECT 547 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTING_PROFILE_GC]
    UNION ALL
    SELECT 547000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTING_PROFILE_PKEY_MAP_GC]
    UNION ALL
    SELECT 89 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTING_SCRIPT_GC]
    UNION ALL
    SELECT 89000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTING_SCRIPT_PKEY_MAP_GC]
    UNION ALL
    SELECT 90 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCHEDULE_GC]
    UNION ALL
    SELECT 90000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCHEDULE_PKEY_MAP_GC]
    UNION ALL
    SELECT 91 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCHEDULED_TARGET_GC]
    UNION ALL
    SELECT 91000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCHEDULED_TARGET_PKEY_MAP_GC]
    UNION ALL
    SELECT 142 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCL_ADAPTER_GC]
    UNION ALL
    SELECT 142000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCL_ADAPTER_PKEY_MAP_GC]
    UNION ALL
    SELECT 143 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCL_SEARCH_GC]
    UNION ALL
    SELECT 143000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCL_SEARCH_PKEY_MAP_GC]
    UNION ALL
    SELECT 92 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCRIPT_GC]
    UNION ALL
    SELECT 92000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCRIPT_PKEY_MAP_GC]
    UNION ALL
    SELECT 93 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCRIPT_NODE_GC]
    UNION ALL
    SELECT 93000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCRIPT_NODE_PKEY_MAP_GC]
    UNION ALL
    SELECT 94 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SERVICE_GC]
    UNION ALL
    SELECT 94000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SERVICE_PKEY_MAP_GC]
    UNION ALL
    SELECT 95 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_GC]
    UNION ALL
    SELECT 95000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_PKEY_MAP_GC]
    UNION ALL
    SELECT 131 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SLA_BUCKET_INTERVAL_GC]
    UNION ALL
    SELECT 131000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SLA_BUCKET_INTERVAL_PKEY_MAP_GC]
    UNION ALL
    SELECT 96 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_STRATEGY_GC]
    UNION ALL
    SELECT 96000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_STRATEGY_PKEY_MAP_GC]
    UNION ALL
    SELECT 117 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SUB_CODE_GC]
    UNION ALL
    SELECT 117000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SUB_CODE_PKEY_MAP_GC]
    UNION ALL
    SELECT 97 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TENANT_GC]
    UNION ALL
    SELECT 97000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TENANT_PKEY_MAP_GC]
    UNION ALL
    SELECT 98 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TIMEBAND_GC]
    UNION ALL
    SELECT 98000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TIMEBAND_PKEY_MAP_GC]
    UNION ALL
    SELECT 99 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TLI_GC]
    UNION ALL
    SELECT 99000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TLI_PKEY_MAP_GC]
    UNION ALL
    SELECT 106 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRANSLATION_ROUTE_GC]
    UNION ALL
    SELECT 106000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRANSLATION_ROUTE_PKEY_MAP_GC]
    UNION ALL
    SELECT 100 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRUNK_GC]
    UNION ALL
    SELECT 100000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRUNK_PKEY_MAP_GC]
    UNION ALL
    SELECT 101 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRUNK_GROUP_GC]
    UNION ALL
    SELECT 101000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRUNK_GROUP_PKEY_MAP_GC]
    UNION ALL
    SELECT 167 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_UC_SERVICE_PROFILE_GC]
    UNION ALL
    SELECT 167000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_UC_SERVICE_PROFILE_PKEY_MAP_GC]
    UNION ALL
    SELECT 114 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_USER_GROUP_GC]
    UNION ALL
    SELECT 114000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_USER_GROUP_PKEY_MAP_GC]
    UNION ALL
    SELECT 102 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_USER_VARIABLE_GC]
    UNION ALL
    SELECT 102000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_USER_VARIABLE_PKEY_MAP_GC]
    UNION ALL
    SELECT 144 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_ASSISTANT_GC]
    UNION ALL
    SELECT 144000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_ASSISTANT_PKEY_MAP_GC]
    UNION ALL
    SELECT 145 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_ATTRIBUTE_GC]
    UNION ALL
    SELECT 145000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_ATTRIBUTE_PKEY_MAP_GC]
    UNION ALL
    SELECT 147 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_CASE_GC]
    UNION ALL
    SELECT 147000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_CASE_PKEY_MAP_GC]
    UNION ALL
    SELECT 149 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_CATEGORY_GC]
    UNION ALL
    SELECT 149000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_CATEGORY_PKEY_MAP_GC]
    UNION ALL
    SELECT 168 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_CLASSIFIER_GC]
    UNION ALL
    SELECT 168000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_CLASSIFIER_PKEY_MAP_GC]
    UNION ALL
    SELECT 170 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_CUSTOMER_GC]
    UNION ALL
    SELECT 170000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_CUSTOMER_PKEY_MAP_GC]
    UNION ALL
    SELECT 151 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_DOMAIN_GC]
    UNION ALL
    SELECT 151000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_DOMAIN_PKEY_MAP_GC]
    UNION ALL
    SELECT 166 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_INTENT_GC]
    UNION ALL
    SELECT 166000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_INTENT_PKEY_MAP_GC]
    UNION ALL
    SELECT 153 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_KEYWORD_GC]
    UNION ALL
    SELECT 153000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_KEYWORD_PKEY_MAP_GC]
    UNION ALL
    SELECT 169 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_SCORE_GC]
    UNION ALL
    SELECT 169000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_SCORE_PKEY_MAP_GC]
    UNION ALL
    SELECT 155 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_URL_GC]
    UNION ALL
    SELECT 155000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VA_URL_PKEY_MAP_GC]
    UNION ALL
    SELECT 103 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VECTOR_GC]
    UNION ALL
    SELECT 103000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VECTOR_PKEY_MAP_GC]
    UNION ALL
    SELECT 104 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VECTOR_DIRECTORY_NUMBER_GC]
    UNION ALL
    SELECT 104000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VECTOR_DIRECTORY_NUMBER_PKEY_MAP_GC]
    UNION ALL
    SELECT 110 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VXMLAPPLICATION_SERVER_GC]
    UNION ALL
    SELECT 110000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_VXMLAPPLICATION_SERVER_PKEY_MAP_GC]
    UNION ALL
    SELECT 105 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_WRAPUP_CODE_GC]
    UNION ALL
    SELECT 105000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_WRAPUP_CODE_PKEY_MAP_GC]
 
    UNION ALL
    SELECT 200 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_AGENT_DESKTOP_MEMBER_GC]
    UNION ALL
    SELECT 200000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_AGENT_DESKTOP_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 201 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_AGENT_TEAM_MEMBER_GC]
    UNION ALL
    SELECT 201000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_AGENT_TEAM_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 202 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_DESKTOP_DIALED_NUMBER_MEMBER_GC]
    UNION ALL
    SELECT 202000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_DESKTOP_DIALED_NUMBER_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 203 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_PERIPHERAL_MEMBER_GC]
    UNION ALL
    SELECT 203000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_PERIPHERAL_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 204 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_PERSON_MEMBER_GC]
    UNION ALL
    SELECT 204000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_PERSON_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 205 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_PRECISION_ATTRIBUTE_MEMBER_GC]
    UNION ALL
    SELECT 205000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_PRECISION_ATTRIBUTE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 206 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_SKILLGROUP_MEMBER_GC]
    UNION ALL
    SELECT 206000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_SKILLGROUP_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 207 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_TEAM_DIALED_NUMBER_MEMBER_GC]
    UNION ALL
    SELECT 207000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_TEAM_DIALED_NUMBER_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 208 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_TEAM_PERIPHERAL_MEMBER_GC]
    UNION ALL
    SELECT 208000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_TEAM_PERIPHERAL_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 257 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_USER_GROUP_MEMBER_GC]
    UNION ALL
    SELECT 257000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_AGENT_USER_GROUP_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 209 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_TYPE_BUCKET_INTERVAL_MEMBER_GC]
    UNION ALL
    SELECT 209000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_TYPE_BUCKET_INTERVAL_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 210 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_TYPE_ROUTING_SCRIPT_MEMBER_GC]
    UNION ALL
    SELECT 210000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CALL_TYPE_ROUTING_SCRIPT_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 211 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CODE_CODE_GROUP_MEMBER_GC]
    UNION ALL
    SELECT 211000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CODE_CODE_GROUP_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 212 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ENTRY_CUSTOM_MEMBER_GC]
    UNION ALL
    SELECT 212000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_CUSTOM_ENTRY_CUSTOM_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 213 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_POOL_CALL_MANAGER_GROUP_MEMBER_GC]
    UNION ALL
    SELECT 213000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_POOL_CALL_MANAGER_GROUP_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 214 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_POOL_DATE_TIME_SETTING_MEMBER_GC]
    UNION ALL
    SELECT 214000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_POOL_DATE_TIME_SETTING_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 215 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_PROFILE_DIRECTORY_NUMBER_MEMBER_GC]
    UNION ALL
    SELECT 215000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_PROFILE_DIRECTORY_NUMBER_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 216 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_PROFILE_IP_ENDPOINT_BUTTON_TEMPLATE_MEMBER_GC]
    UNION ALL
    SELECT 216000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_PROFILE_IP_ENDPOINT_BUTTON_TEMPLATE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 217 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_PROFILE_PERSON_MEMBER_GC]
    UNION ALL
    SELECT 217000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DEVICE_PROFILE_PERSON_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 218 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALED_NUMBER_CALL_TYPE_MEMBER_GC]
    UNION ALL
    SELECT 218000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALED_NUMBER_CALL_TYPE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 219 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALED_NUMBER_MEDIA_ROUTING_DOMAIN_MEMBER_GC]
    UNION ALL
    SELECT 219000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALED_NUMBER_MEDIA_ROUTING_DOMAIN_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 220 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALED_NUMBER_ROUTING_CLIENT_MEMBER_GC]
    UNION ALL
    SELECT 220000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_DIALED_NUMBER_ROUTING_CLIENT_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 267 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_EXPANDED_CALL_VARIABLE_ECC_PAYLOAD_MEMBER_GC]
    UNION ALL
    SELECT 267000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_EXPANDED_CALL_VARIABLE_ECC_PAYLOAD_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 268 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_CLUSTER_GHE_CLUSTER_GROUP_MEMBER_GC]
    UNION ALL
    SELECT 268000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_CLUSTER_GHE_CLUSTER_GROUP_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 260 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_QUESTION_GHE_ANSWER_MEMBER_GC]
    UNION ALL
    SELECT 260000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_GHE_QUESTION_GHE_ANSWER_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 221 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_CALLING_SEARCH_SPACE_MEMBER_GC]
    UNION ALL
    SELECT 221000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_CALLING_SEARCH_SPACE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 222 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_DEVICE_POOL_MEMBER_GC]
    UNION ALL
    SELECT 222000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_DEVICE_POOL_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 223 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_DIRECTORY_NUMBER_MEMBER_GC]
    UNION ALL
    SELECT 223000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_DIRECTORY_NUMBER_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 224 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_IP_ENDPOINT_BUTTON_TEMPLATE_MEMBER_GC]
    UNION ALL
    SELECT 224000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_IP_ENDPOINT_BUTTON_TEMPLATE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 225 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_PERIPHERAL_MEMBER_GC]
    UNION ALL
    SELECT 225000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IP_ENDPOINT_PERIPHERAL_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 226 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ENTRY_POINT_DIALED_NUMBER_MEMBER_GC]
    UNION ALL
    SELECT 226000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ENTRY_POINT_DIALED_NUMBER_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 227 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ENTRY_POINT_IVR_SCRIPT_MEMBER_GC]
    UNION ALL
    SELECT 227000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ENTRY_POINT_IVR_SCRIPT_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 228 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ROUTING_TARGET_IVR_SCRIPT_MEMBER_GC]
    UNION ALL
    SELECT 228000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_ROUTING_TARGET_IVR_SCRIPT_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 229 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SCRIPT_NODE_IVR_MODULE_MEMBER_GC]
    UNION ALL
    SELECT 229000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_IVR_SCRIPT_NODE_IVR_MODULE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 258 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_ARTICLE_KB_TOPIC_MEMBER_GC]
    UNION ALL
    SELECT 258000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_KB_ARTICLE_KB_TOPIC_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 230 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_LABEL_DIALED_NUMBER_MEMBER_GC]
    UNION ALL
    SELECT 230000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_LABEL_DIALED_NUMBER_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 231 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_LABEL_ROUTING_CLIENT_MEMBER_GC]
    UNION ALL
    SELECT 231000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_LABEL_ROUTING_CLIENT_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 232 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIA_ROUTING_DOMAIN_MEDIA_CLASS_MEMBER_GC]
    UNION ALL
    SELECT 232000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_MEDIA_ROUTING_DOMAIN_MEDIA_CLASS_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 233 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NETWORK_VRU_SCRIPT_NETWORK_VRU_MEMBER_GC]
    UNION ALL
    SELECT 233000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_NETWORK_VRU_SCRIPT_NETWORK_VRU_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 234 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PERIPHERAL_LOGICAL_INTERFACE_CONTROLLER_MEMBER_GC]
    UNION ALL
    SELECT 234000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PERIPHERAL_LOGICAL_INTERFACE_CONTROLLER_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 235 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PHYSICAL_CONTROLLER_LOGICAL_CONTROLLER_MEMBER_GC]
    UNION ALL
    SELECT 235000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PHYSICAL_CONTROLLER_LOGICAL_CONTROLLER_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 236 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_BUCKET_INTERVAL_MEMBER_GC]
    UNION ALL
    SELECT 236000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_BUCKET_INTERVAL_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 259 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_MEDIA_ROUTING_DOMAIN_MEMBER_GC]
    UNION ALL
    SELECT 259000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_MEDIA_ROUTING_DOMAIN_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 237 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_STEP_PRECISION_ATTRIBUTE_MEMBER_GC]
    UNION ALL
    SELECT 237000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_STEP_PRECISION_ATTRIBUTE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 238 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_STEP_PRECISION_QUEUE_MEMBER_GC]
    UNION ALL
    SELECT 238000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_PRECISION_QUEUE_STEP_PRECISION_QUEUE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 239 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_QUERY_RULE_CAMPAIGN_MEMBER_GC]
    UNION ALL
    SELECT 239000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_QUERY_RULE_CAMPAIGN_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 240 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_QUERY_RULE_IMPORT_RULE_MEMBER_GC]
    UNION ALL
    SELECT 240000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_QUERY_RULE_IMPORT_RULE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 241 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_ENTERPRISE_ROUTE_MEMBER_GC]
    UNION ALL
    SELECT 241000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_ENTERPRISE_ROUTE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 242 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_PARTITION_CALLING_SEARCH_SPACE_MEMBER_GC]
    UNION ALL
    SELECT 242000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_PARTITION_CALLING_SEARCH_SPACE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 243 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_SKILLGROUP_MEMBER_GC]
    UNION ALL
    SELECT 243000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTE_SKILLGROUP_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 244 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTING_CLIENT_PERIPHERAL_MEMBER_GC]
    UNION ALL
    SELECT 244000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_ROUTING_CLIENT_PERIPHERAL_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 246 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCRIPT_ROUTING_SCRIPT_MEMBER_GC]
    UNION ALL
    SELECT 246000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SCRIPT_ROUTING_SCRIPT_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 247 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SERVICE_ENTERPRISE_SERVICE_MEMBER_GC]
    UNION ALL
    SELECT 247000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SERVICE_ENTERPRISE_SERVICE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 248 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SERVICE_MEDIA_ROUTING_DOMAIN_MEMBER_GC]
    UNION ALL
    SELECT 248000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SERVICE_MEDIA_ROUTING_DOMAIN_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 249 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SERVICE_PERIPHERAL_MEMBER_GC]
    UNION ALL
    SELECT 249000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SERVICE_PERIPHERAL_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 250 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_CAMPAIGN_MEMBER_GC]
    UNION ALL
    SELECT 250000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_CAMPAIGN_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 251 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_ENTERPRISE_SKILLGROUP_MEMBER_GC]
    UNION ALL
    SELECT 251000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_ENTERPRISE_SKILLGROUP_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 252 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_MEDIA_ROUTING_DOMAIN_MEMBER_GC]
    UNION ALL
    SELECT 252000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_MEDIA_ROUTING_DOMAIN_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 253 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_PERIPHERAL_MEMBER_GC]
    UNION ALL
    SELECT 253000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_PERIPHERAL_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 254 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_SERVICE_MEMBER_GC]
    UNION ALL
    SELECT 254000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_SKILLGROUP_SERVICE_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 255 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRUNK_GROUP_NETWORK_TRUNK_GROUP_MEMBER_GC]
    UNION ALL
    SELECT 255000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRUNK_GROUP_NETWORK_TRUNK_GROUP_MEMBER_PKEY_MAP_GC] 
    UNION ALL
    SELECT 256 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRUNK_TRUNK_GROUP_MEMBER_GC]
    UNION ALL
    SELECT 256000 AS [TABLE_GENERATION_COUNT_URN], [GENERATION_COUNT], [CREATE_GENERATION_COUNT], [LAST_OPERATION] 
    FROM [dbo].[TS_DIM_TRUNK_TRUNK_GROUP_MEMBER_PKEY_MAP_GC];
GO
GRANT SELECT
	ON [dbo].[VW_ADM_DATA_GENERATION_COUNT]
	TO [portalapp_role]
GO
