SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].VW_PARTITIONED_SUM_CMS_TRUNK_INTERVAL
AS
SELECT  *
FROM    dbo.TB_SUM_CMS_TRUNK_INTERVAL;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_SUM_CMS_TRUNK_INTERVAL]
	TO [portalreporting_role]
GO
