SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
-------------------------------------------------------------------------------
--
-------------------------------------------------------------------------------
CREATE VIEW [dbo].[VW_FCT_IVR_LEG]
--WITH ENCRYPTION
AS
SELECT  [PARTITION_URN],
        [PARTITION_ID],
        [PARTITION_GLOBAL_URN],
        [DATE_TIME],
        [UTC_TIMEZONE],
        [DATE_URN],
        [TIME_URN],
        [DATE_UTC_URN],
        [TIME_UTC_URN],
        [CALL_DETAIL_URN],
        [DIALED_NUMBER_URN],
        [IVR_SCRIPT_URN],
        [CALL_OUTCOME_URN],
        [INITIAL_IVR_SCRIPT_NODE_URN],
        [FINAL_IVR_SCRIPT_NODE_URN],
        [IVR_ROUTING_TARGET_URN],
        [DEFLECTION_LEVEL_URN],
        [TRANSFER_TARGET_URN],
        [TRANSFER_STATUS_URN],
        [SECURITY_STATUS_URN],
        [TERMINATION_REASON_URN],
        [DESTINATION_ANI_URN],
        [ORGANIZATION_URN],
        [LOCATION_URN],
        [DURATION_TIMEBAND_URN],
        [NETWORK_TIME_TIMEBAND_URN],
        [RING_TIME_TIMEBAND_URN],
        [HOLD_TIME_TIMEBAND_URN],
        [TALK_TIME_TIMEBAND_URN],
        [QUEUE_TIME_TIMEBAND_URN],
        [CALL_TYPE_URN],
        [PERIPHERAL_URN],
        [CALL_SOURCE_URN],
        [CALL_REASON_URN],
        [CLI_NNG_URN],
        [CLI_URN],
        [VALUE_URN],
        [SATISFACTION_URN],
        [CUSTOM_DIMENSION_0],
        [CUSTOM_DIMENSION_1],
        [CUSTOM_DIMENSION_2],
        [CUSTOM_DIMENSION_3],
        [CUSTOM_DIMENSION_4],
        [CUSTOM_DIMENSION_5],
        [CUSTOM_DIMENSION_6],
        [CUSTOM_DIMENSION_7],
        [CUSTOM_DIMENSION_8],
        [CUSTOM_DIMENSION_9],
        [IVR_SCRIPT_NODE_COUNT],
        [DEFLECTION_COUNT],
        [DESTINATION_ANI],
        [DURATION],
        [NETWORK_TIME],
        [RING_TIME],
        [HOLD_TIME],
        [TALK_TIME],
        [QUEUE_TIME],
        [CALL_REC_LINK],
        [SEQUENCE_NUMBER],
        [PORT],
        [DIRECTION],
        [CLI],
        [VERSION],
        [GRAMMAR_REJECTS],
        [INPUT_TIMEOUTS],
        [REPEAT_REQUESTS],
        [LOST_INFO],
        [COST],
        [CUSTOM_MEASURE_0],
        [CUSTOM_MEASURE_1],
        [CUSTOM_MEASURE_2],
        [CUSTOM_MEASURE_3],
        [CUSTOM_MEASURE_4],
        [CUSTOM_MEASURE_5],
        [CUSTOM_MEASURE_6],
        [CUSTOM_MEASURE_7],
        [CUSTOM_MEASURE_8],
        [CUSTOM_MEASURE_9],
        [IVR_SOURCE_SESSION_ID],
        1 AS [Call Volume Total]
FROM    dbo.VW_PARTITIONED_FCT_IVR_LEG;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_IVR_LEG]
	TO [portalreporting_role]
GO
