SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_ACTIVITY_CLASSIFICATION]
AS
    SELECT  *
    FROM    [dbo].[TB_FCT_ACTIVITY_CLASSIFICATION];
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_ACTIVITY_CLASSIFICATION]
	TO [portalreporting_role]
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_ACTIVITY_CLASSIFICATION]
	TO [portal_default_mediator_role]
GO
