SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_VA_SESSION_EXCHANGE]
AS
   SELECT * FROM [dbo].[TB_FCT_VA_SESSION_EXCHANGE];
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_VA_SESSION_EXCHANGE]
	TO [portalreporting_role]
GO
