SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_ADM_CUSTOM_ATTRIBUTE_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[INT_KEY] AS RESOURCE_ID,
        [gc].[CUSTOM_ATTRIBUTE_URN],
        [gc].[CLUSTER_RESOURCE_ID],
        crt.[INTERNAL_NAME] AS [CLUSTER_TYPE_INTERNAL_NAME],
        [gc].[OWNER_ID],
        [gc].[ATTRIBUTE_TYPE],
        [gc].[OBJ_TYPE],
        [gc].[OBJ_INDEX],
        [gc].[SOURCE_OBJ_NAME],
        [gc].[SOURCE_ATT_NAME],
        [gc].[CREATED_BY_ID],
        [gc].[MODIFIED_BY_ID],
        [gc].[CREATION_DATE],
        [gc].[MODIFIED_DATE],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_ADM_CUSTOM_ATTRIBUTE] gc ON gc.[CUSTOM_ATTRIBUTE_URN] = datagc.[INT_KEY]
INNER JOIN [dbo].[TB_CLU_RESOURCE] clu ON clu.RESOURCE_ID = gc.[CLUSTER_RESOURCE_ID]
LEFT JOIN [dbo].[TE_ADM_CLUSTER_RESOURCE_TYPE] crt ON clu.RESOURCE_TYPE_ID = crt.CLUSTER_RESOURCE_TYPE_ID
WHERE   tablegc.TABLE_NAME = 'TB_ADM_CUSTOM_ATTRIBUTE';
GO
GRANT SELECT
	ON [dbo].[VW_ADM_CUSTOM_ATTRIBUTE_GC]
	TO [portalapp_role]
GO
