SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_ETL_AUDIT]
--WITH ENCRYPTION
AS
SELECT  *
FROM    dbo.VW_PARTITIONED_FCT_ETL_AUDIT;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_ETL_AUDIT]
	TO [portalreporting_role]
GO
