SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_FISCAL_MONTH_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[INT_KEY] AS RESOURCE_ID,
        dimFiscalMonth.[FISCAL_QUARTER_URN],
        dimFiscalMonth.[NAME],
        dimFiscalMonth.[START_DATE_TIME],
        dimFiscalMonth.[END_DATE_TIME],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_DIM_FISCAL_MONTH] dimFiscalMonth ON dimFiscalMonth.FISCAL_MONTH_URN = datagc.INT_KEY
WHERE   tablegc.TABLE_NAME = 'TB_DIM_FISCAL_MONTH';
GO
GRANT SELECT
	ON [dbo].[VW_DIM_FISCAL_MONTH_GC]
	TO [portalapp_role]
GO
