SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_WFM_FORECAST_CUBE]
--WITH ENCRYPTION
AS
    SELECT * FROM VW_FCT_WFM_FORECAST;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_WFM_FORECAST_CUBE]
	TO [portalapp_role]
GO
