SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE     VIEW dbo.VW_SEC_GLOBAL_ROLE_TASK_MAPPING
--WITH SCHEMABINDING
AS
SELECT DISTINCT
        t.TASK_ID,
        r.ROLE_ID,
        t.CODE,
        t.INTERNAL_NAME
FROM    dbo.TE_SEC_TASK t
JOIN    dbo.TB_SEC_ROLE_MAPPING rm ON rm.TASK_ID = t.TASK_ID
JOIN    dbo.TB_SEC_ROLE r ON r.ROLE_ID = rm.ROLE_ID
WHERE   t.DELETED = 0
        AND t.ENABLED = 1
        AND r.ENABLED = 1
        AND r.GLOBAL_ROLE = 1;
GO
GRANT SELECT
	ON [dbo].[VW_SEC_GLOBAL_ROLE_TASK_MAPPING]
	TO [portalapp_role]
GO
