SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_COBROWSE_SESSION]
AS
SELECT  *
FROM    [dbo].[TB_FCT_COBROWSE_SESSION];
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_COBROWSE_SESSION]
	TO [portalreporting_role]
GO
