SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_AGENT_PERSON_COMBINED]
AS
SELECT  P.ITEM_URN AS PERSON_URN,
        P.LOGIN_NAME,
        P.PASS_PHRASE,
        P.PASS_PHRASE_SHA,
        a.ITEM_URN AS AGENT_URN,
        a.INTERNAL_NAME AS AGENT_INTERNAL_NAME,
        a.PERIPHERAL_NUMBER
FROM    VW_DIM_PERSON_PKEY P
JOIN    VW_DIM_AGENT_PERSON_MEMBER member ON member.PARENT_ITEM_BIZ_URN = P.ITEM_BIZ_URN
                                             AND member.LATEST = 1
JOIN    VW_DIM_AGENT_PKEY a ON member.CHILD_ITEM_BIZ_URN = a.ITEM_BIZ_URN
                               AND a.LATEST = 1
JOIN    TB_CLU_RESOURCE clu ON P.CLUSTER_RESOURCE_ID = clu.RESOURCE_ID
JOIN    TE_ADM_CLUSTER_RESOURCE_TYPE cluT ON clu.RESOURCE_TYPE_ID = cluT.CLUSTER_RESOURCE_TYPE_ID
WHERE   cluT.INTERNAL_NAME = 'CRT_CISCO_CICM'
        AND P.LATEST = 1
        AND member.DELETED = 0
        AND a.DELETED = 0
        AND P.DELETED = 0;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_AGENT_PERSON_COMBINED]
	TO [portalapp_role]
GO
