SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VW_DIM_KB_ACCESS_SUB_TYPE_CUBE
AS
SELECT CAST(1 AS INT) AS ACCESS_SUB_TYPE_URN, 'Other' AS ACCESS_SUB_TYPE_NAME, 'Other' AS ACCESS_SUB_TYPE_DESCRIPTION  
UNION ALL 
SELECT CAST(2 AS INT) AS ACCESS_SUB_TYPE_URN, 'Self Service Inactive' AS ACCESS_SUB_TYPE_NAME, 'Self Service Inactive' AS ACCESS_SUB_TYPE_DESCRIPTION  
UNION ALL  
SELECT CAST(3 AS INT) AS ACCESS_SUB_TYPE_URN, 'Self Service Active' AS ACCESS_SUB_TYPE_NAME, 'Self Service Active' AS ACCESS_SUB_TYPE_DESCRIPTION 
UNION ALL
SELECT CAST(4 AS INT) AS ACCESS_SUB_TYPE_URN, 'Secure Messaging' AS ACCESS_SUB_TYPE_NAME, 'Secure Messaging' AS ACCESS_SUB_TYPE_DESCRIPTION 
UNION ALL
SELECT CAST(5 AS INT) AS ACCESS_SUB_TYPE_URN, 'Mixed' AS ACCESS_SUB_TYPE_NAME, 'Mixed' AS ACCESS_SUB_TYPE_DESCRIPTION
GO
GRANT SELECT
	ON [dbo].[VW_DIM_KB_ACCESS_SUB_TYPE_CUBE]
	TO [portalapp_role]
GO
