SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[VW_DIM_ITEM_PKEY_MAP]
WITH SCHEMABINDING
AS
    SELECT CAST('00001100-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 1 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_AGENT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009100-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 2 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_AGENT_DESKTOP_PKEY_MAP]
    UNION ALL
    SELECT CAST('00001200-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 3 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_AGENT_TEAM_PKEY_MAP]
    UNION ALL
    SELECT CAST('d681b841-a1d4-4be8-8538-f75c40f524eb' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 116 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ALIAS_PKEY_MAP]
    UNION ALL
    SELECT CAST('00001300-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 4 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ANNOUNCEMENT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009200-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 5 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_APPLICATION_GATEWAY_PKEY_MAP]
    UNION ALL
    SELECT CAST('00001400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 6 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_APPLICATION_INSTANCE_PKEY_MAP]
    UNION ALL
    SELECT CAST('56e734bc-473a-46a8-ad35-54a0cd39b963' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 7 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_APPLICATION_USER_PKEY_MAP]
    UNION ALL
    SELECT CAST('00008400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 8 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_BUCKET_INTERVAL_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009900-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 10 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CALL_MANAGER_GROUP_PKEY_MAP]
    UNION ALL
    SELECT CAST('00001440-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 11 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CALL_SOURCE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00001500-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 12 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CALL_TYPE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00010700-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 9 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CALLING_SEARCH_SPACE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00001600-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 13 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CAMPAIGN_PKEY_MAP]
    UNION ALL
    SELECT CAST('00001700-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 14 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CATEGORY_PKEY_MAP]
    UNION ALL
    SELECT CAST('8af98ba5-936d-40a0-b7aa-f98163f18c9c' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 127 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CBR_RELEASE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00001900-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 15 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CHARGEBAND_PKEY_MAP]
    UNION ALL
    SELECT CAST('0348a177-ea2f-4191-8597-cc02dacea8e2' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 162 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CHAT_REFERRER_NAME_PKEY_MAP]
    UNION ALL
    SELECT CAST('d12cd7df-e5b4-48c3-9129-b1d1c00325fd' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 163 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CHAT_REFERRER_URL_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002100-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 16 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CLI_PKEY_MAP]
    UNION ALL
    SELECT CAST('516ff4e5-cbb6-4745-ad0f-a926ee0ad23e' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 161 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_COBROWSE_PAGE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002110-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 17 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CODE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00010550-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 18 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CODE_GROUP_PKEY_MAP]
    UNION ALL
    SELECT CAST('12f8f3fd-b2d4-4d48-aee6-52ed6c359ac9' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 120 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CONTENT_URL_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002200-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 19 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_PKEY_MAP]
    UNION ALL
    SELECT CAST('460a7f59-f897-4d3b-bdf3-53ed8662ceab' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 132 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE0_PKEY_MAP]
    UNION ALL
    SELECT CAST('f3f53a92-07f5-478f-b357-313fc4aebbdf' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 133 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE1_PKEY_MAP]
    UNION ALL
    SELECT CAST('6521fffa-dbed-4b9e-af54-58e190c2c621' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 134 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE2_PKEY_MAP]
    UNION ALL
    SELECT CAST('137c55f7-2121-4fe1-ab53-4b8188696255' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 135 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE3_PKEY_MAP]
    UNION ALL
    SELECT CAST('37f22a98-583d-4e52-b4a0-ce6a78fdabc2' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 136 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE4_PKEY_MAP]
    UNION ALL
    SELECT CAST('c641d289-bf05-44ae-8057-e06e165715d4' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 137 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE5_PKEY_MAP]
    UNION ALL
    SELECT CAST('0e659f10-7bd2-4642-8eea-6a0c0ff2bc3b' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 138 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE6_PKEY_MAP]
    UNION ALL
    SELECT CAST('33912e67-a457-4260-a0b5-82117debe1ef' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 139 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE7_PKEY_MAP]
    UNION ALL
    SELECT CAST('871f2fd5-ccde-42c4-8907-0beec4e18c7d' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 140 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE8_PKEY_MAP]
    UNION ALL
    SELECT CAST('8cacf82e-d83b-4759-accd-5cdf25b2557b' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 141 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ATTRIBUTE9_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002250-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 30 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM_ENTRY_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002200-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 20 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM0_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002201-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 21 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM1_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002202-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 22 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM2_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002203-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 23 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM3_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002204-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 24 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM4_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002205-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 25 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM5_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002206-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 26 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM6_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002207-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 27 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM7_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002208-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 28 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM8_PKEY_MAP]
    UNION ALL
    SELECT CAST('99002209-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 29 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_CUSTOM9_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002000-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 31 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_DATE_TIME_SETTING_PKEY_MAP]
    UNION ALL
    SELECT CAST('20001000-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 111 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_DEPARTMENT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00010900-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 32 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_DEVICE_POOL_PKEY_MAP]
    UNION ALL
    SELECT CAST('00005000-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 33 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_DEVICE_PROFILE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002300-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 34 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_DEVICE_TARGET_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009300-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 37 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_DIAL_NUMBER_PLAN_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 35 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_DIALED_NUMBER_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002600-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 36 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_DIALER_PKEY_MAP]
    UNION ALL
    SELECT CAST('00011100-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 38 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_DIRECTORY_NUMBER_PKEY_MAP]
    UNION ALL
    SELECT CAST('10fb2472-bf84-4cf8-a8bb-cc7dc9147df7' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 157 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ECC_PAYLOAD_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002800-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 39 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_EMAIL_PKEY_MAP]
    UNION ALL
    SELECT CAST('00003200-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 40 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ENTERPRISE_ROUTE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00003300-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 41 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ENTERPRISE_SERVICE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00003400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 42 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ENTERPRISE_SKILLGROUP_PKEY_MAP]
    UNION ALL
    SELECT CAST('9d660b17-9af3-43ec-a6b8-ec8e0d74c2a0' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 115 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ENTRY_POINT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 43 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_EXPANDED_CALL_VARIABLE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00002700-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 44 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_FILESHARE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00003600-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 46 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_GATEWAY_FUNCTION_PKEY_MAP]
    UNION ALL
    SELECT CAST('00003650-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 47 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_GATEWAY_RESULT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00003800-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 48 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_GATEWAY_SERVER_PKEY_MAP]
    UNION ALL
    SELECT CAST('b1dc6b14-72cf-4c51-876e-1da1e1f63b74' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 130 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_GHE_ANSWER_PKEY_MAP]
    UNION ALL
    SELECT CAST('36fee03e-be37-43d3-a3e9-4b13f6ccae5d' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 164 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_GHE_CLUSTER_PKEY_MAP]
    UNION ALL
    SELECT CAST('81674c53-6785-4f4f-a6d7-27f180c520f8' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 165 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_GHE_CLUSTER_GROUP_PKEY_MAP]
    UNION ALL
    SELECT CAST('95009762-fc8e-4303-8096-86fb24ec0cb3' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 129 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_GHE_QUESTION_PKEY_MAP]
    UNION ALL
    SELECT CAST('00039551-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 49 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_HIERARCHY_PKEY_MAP]
    UNION ALL
    SELECT CAST('00039552-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 50 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_HIERARCHY_NODE_PKEY_MAP]
    UNION ALL
    SELECT CAST('af9964c7-68c8-42c3-9813-b9919cbb6874' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 107 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_HUNT_PILOT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009500-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 51 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ICR_INSTANCE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00008000-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 52 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IMPORT_RULE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00004500-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 53 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IP_ENDPOINT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00011000-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 54 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IP_ENDPOINT_BUTTON_TEMPLATE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00011200-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 55 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IVR_ENTRY_POINT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00011400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 56 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IVR_MODULE_PKEY_MAP]
    UNION ALL
    SELECT CAST('864531e7-3fba-4284-9ad9-d18aa7c6027f' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 57 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IVR_QUEUE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00011300-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 58 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IVR_ROUTING_TARGET_PKEY_MAP]
    UNION ALL
    SELECT CAST('00004600-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 59 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IVR_SCRIPT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00004610-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 60 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IVR_SCRIPT_NODE_PKEY_MAP]
    UNION ALL
    SELECT CAST('7b7acf0f-bf74-46de-b8f6-65b46e94f80c' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 61 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IVR_SCRIPT_NODE_EXIT_STATE_PKEY_MAP]
    UNION ALL
    SELECT CAST('6368bd5b-e59d-4c8f-875b-82a117e8b7fc' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 62 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_IVR_SERVER_PKEY_MAP]
    UNION ALL
    SELECT CAST('e349b610-402f-4a1a-b555-ba26abdc6f30' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 123 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_KB_ARTICLE_PKEY_MAP]
    UNION ALL
    SELECT CAST('a25e34b9-79e9-4601-9fd8-51a638940e4c' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 172 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_KB_ARTICLE_REVIEW_STAGE_PKEY_MAP]
    UNION ALL
    SELECT CAST('140ae2b9-c3ba-42bb-8508-0240e45b95c1' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 158 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_KB_ARTICLE_WORKFLOW_PKEY_MAP]
    UNION ALL
    SELECT CAST('555644c0-afa2-498d-b7fa-038a00f821f0' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 171 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_KB_COMPLIANCE_POLICY_PKEY_MAP]
    UNION ALL
    SELECT CAST('1efc44cf-d313-4bf5-9be7-a4a893d68d2c' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 124 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_KB_FOLDER_PKEY_MAP]
    UNION ALL
    SELECT CAST('81e33d5a-42f6-4a6d-9753-561cefe6136f' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 121 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_KB_PORTAL_PKEY_MAP]
    UNION ALL
    SELECT CAST('d82c0660-b9ee-4da4-8b19-2861120ca90a' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 122 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_KB_TOPIC_PKEY_MAP]
    UNION ALL
    SELECT CAST('00004700-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 63 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_LABEL_PKEY_MAP]
    UNION ALL
    SELECT CAST('00005100-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 64 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_LOGICAL_INTERFACE_CONTROLLER_PKEY_MAP]
    UNION ALL
    SELECT CAST('dd962dbf-c1fb-4637-985d-81c710d19e15' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 65 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_MACHINE_PKEY_MAP]
    UNION ALL
    SELECT CAST('780dad0d-aac3-4fba-8d10-8664e254e088' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 66 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_MACHINE_RESOURCE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009550-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 67 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_MEDIA_CLASS_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009600-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 68 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_MEDIA_ROUTING_DOMAIN_PKEY_MAP]
    UNION ALL
    SELECT CAST('d500e079-8a45-44b3-8068-f5dfe64297d5' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 108 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_MEDIAFILE_PKEY_MAP]
    UNION ALL
    SELECT CAST('0b124149-1348-4eae-8699-a5ebe43d4d15' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 109 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_MEDIAFILE_SERVER_PKEY_MAP]
    UNION ALL
    SELECT CAST('00005600-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 69 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_NETWORK_TRUNK_GROUP_PKEY_MAP]
    UNION ALL
    SELECT CAST('00005700-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 70 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_NETWORK_VRU_PKEY_MAP]
    UNION ALL
    SELECT CAST('aaf3357b-5222-416d-887f-2e6678c73910' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 71 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_NETWORK_VRU_SCRIPT_PKEY_MAP]
    UNION ALL
    SELECT CAST('b85aa2b4-6c2a-44e8-b103-8e0bf64749b7' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 125 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_NOTIFY_CATEGORY_PKEY_MAP]
    UNION ALL
    SELECT CAST('10f7f60a-f120-49e5-9ea1-5adc5a66371f' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 159 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_NOTIFY_CHANNEL_PKEY_MAP]
    UNION ALL
    SELECT CAST('a1a245cd-acce-4d76-9839-7a589515601a' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 128 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_NOTIFY_MESSAGE_TYPE_PKEY_MAP]
    UNION ALL
    SELECT CAST('da79488a-e823-4675-aa30-89f3847874ea' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 160 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_NOTIFY_ORIGIN_PKEY_MAP]
    UNION ALL
    SELECT CAST('00001450-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 72 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_OBJECT_TYPE_PKEY_MAP]
    UNION ALL
    SELECT CAST('dbc2a99b-996e-4c94-be3b-af3ce1e7341d' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 118 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_OFFER_PKEY_MAP]
    UNION ALL
    SELECT CAST('ac9eba20-25f8-44fb-8252-c4e65fa05ef0' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 119 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_OFFER_BANNER_PKEY_MAP]
    UNION ALL
    SELECT CAST('00006200-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 73 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_PERIPHERAL_PKEY_MAP]
    UNION ALL
    SELECT CAST('00003150-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 74 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_PERSON_PKEY_MAP]
    UNION ALL
    SELECT CAST('00006400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 75 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_PHYSICAL_INTERFACE_CONTROLLER_PKEY_MAP]
    UNION ALL
    SELECT CAST('00006500-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 76 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_PORT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00039602-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 77 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_PRECISION_ATTRIBUTE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00039562-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 78 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_PRECISION_QUEUE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00039572-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 79 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_PRECISION_QUEUE_STEP_PKEY_MAP]
    UNION ALL
    SELECT CAST('00006700-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 81 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_QUERY_RULE_PKEY_MAP]
    UNION ALL
    SELECT CAST('61a20821-ae86-4d50-b6a9-502d89453907' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 113 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_QUEUE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00005110-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 83 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_RATING_PERIOD_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009800-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 84 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_REASON_CODE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00010600-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 85 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_REGION_PKEY_MAP]
    UNION ALL
    SELECT CAST('00005400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 86 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ROUTE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00010800-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 87 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ROUTE_PARTITION_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007300-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 88 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ROUTING_CLIENT_PKEY_MAP]
    UNION ALL
    SELECT CAST('1122ca7e-928b-4710-9af0-082b915fd495' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 547 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ROUTING_PROFILE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007200-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 89 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_ROUTING_SCRIPT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00009700-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 90 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SCHEDULE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 91 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SCHEDULED_TARGET_PKEY_MAP]
    UNION ALL
    SELECT CAST('9ce7c8c9-76f1-4ffc-b809-861517f609f2' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 142 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SCL_ADAPTER_PKEY_MAP]
    UNION ALL
    SELECT CAST('b2a289a1-f613-4d0d-8f57-f83e04521155' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 143 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SCL_SEARCH_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007410-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 92 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SCRIPT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007420-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 93 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SCRIPT_NODE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007500-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 94 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SERVICE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007600-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 95 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SKILLGROUP_PKEY_MAP]
    UNION ALL
    SELECT CAST('2be66c38-5592-4dba-bc11-81d3395163b0' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 131 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SLA_BUCKET_INTERVAL_PKEY_MAP]
    UNION ALL
    SELECT CAST('00039550-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 96 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_STRATEGY_PKEY_MAP]
    UNION ALL
    SELECT CAST('24fb83b4-a581-4642-a847-0ab90f78be38' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 117 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_SUB_CODE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007800-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 97 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_TENANT_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007810-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 98 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_TIMEBAND_PKEY_MAP]
    UNION ALL
    SELECT CAST('00007900-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 99 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_TLI_PKEY_MAP]
    UNION ALL
    SELECT CAST('89139453-b23b-44e1-a61e-0c72dbae5e91' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 106 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_TRANSLATION_ROUTE_PKEY_MAP]
    UNION ALL
    SELECT CAST('00008200-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 100 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_TRUNK_PKEY_MAP]
    UNION ALL
    SELECT CAST('00008300-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 101 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_TRUNK_GROUP_PKEY_MAP]
    UNION ALL
    SELECT CAST('c79483bb-ad3d-4135-83ce-bb3cf92bb765' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 167 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_UC_SERVICE_PROFILE_PKEY_MAP]
    UNION ALL
    SELECT CAST('c95a5f46-9dec-4cf3-80bc-f6943f3cf0c0' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 114 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_USER_GROUP_PKEY_MAP]
    UNION ALL
    SELECT CAST('00010400-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 102 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_USER_VARIABLE_PKEY_MAP]
    UNION ALL
    SELECT CAST('18a81360-359d-4922-91d7-98b0e903db18' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 144 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_ASSISTANT_PKEY_MAP]
    UNION ALL
    SELECT CAST('4ded5469-18cd-4817-96db-6e73b7c69656' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 145 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_ATTRIBUTE_PKEY_MAP]
    UNION ALL
    SELECT CAST('bc92cc12-300f-442c-83de-1a8bcd86d28f' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 147 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_CASE_PKEY_MAP]
    UNION ALL
    SELECT CAST('533f3ee4-334c-4d8b-a04c-a88efc120b55' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 149 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_CATEGORY_PKEY_MAP]
    UNION ALL
    SELECT CAST('88fefca3-3fc1-4718-bc4d-8cfbc53ddfd7' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 168 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_CLASSIFIER_PKEY_MAP]
    UNION ALL
    SELECT CAST('a5575cc4-ab5c-4af9-a650-88b746c48f46' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 170 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_CUSTOMER_PKEY_MAP]
    UNION ALL
    SELECT CAST('cca73037-399c-4e7d-a53c-6527a62e8b1e' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 151 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_DOMAIN_PKEY_MAP]
    UNION ALL
    SELECT CAST('1792bcc6-de73-4bb5-96ab-9ca671dc4245' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 166 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_INTENT_PKEY_MAP]
    UNION ALL
    SELECT CAST('d1901408-b687-4d03-88fa-02d542c04dc8' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 153 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_KEYWORD_PKEY_MAP]
    UNION ALL
    SELECT CAST('579e33cc-95e5-4fe9-bc4c-3ff3045d4eee' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 169 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_SCORE_PKEY_MAP]
    UNION ALL
    SELECT CAST('be47e0e6-c335-4e2f-8586-c31a164afbfa' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 155 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VA_URL_PKEY_MAP]
    UNION ALL
    SELECT CAST('02d90779-bea4-48c7-ac7f-2df4bc9da230' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 103 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VECTOR_PKEY_MAP]
    UNION ALL
    SELECT CAST('39c95ad6-8271-4494-9702-03066abcc02b' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 104 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VECTOR_DIRECTORY_NUMBER_PKEY_MAP]
    UNION ALL
    SELECT CAST('e8df41b0-854c-421d-9c6d-1eaa8fdc9dce' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 110 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], NULL AS [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_VXMLAPPLICATION_SERVER_PKEY_MAP]
    UNION ALL
    SELECT CAST('00010500-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [ITEM_TYPE_ID], 105 AS [ITEM_TYPE_URN], [PKEY_MAP_URN], [PKEY_MAP_BIZ_URN], [ITEM_BIZ_URN], [CLUSTER_RESOURCE_ID], [STATUS], [PKEY1], [PKEY2], [EFFECTIVE_FROM], 
           [EFFECTIVE_TO], [CREATION_DATE], [MODIFIED_DATE], [CREATED_BY_ID], [MODIFIED_BY_ID], [PURGED], [SYSTEM], [LATEST], [CHANGE_STAMP], [SOURCE_CHANGE_STAMP], [XML_DATA], [CUSTOM_XML_DATA], [INTERNAL_NAME] 
    FROM [dbo].[TB_DIM_WRAPUP_CODE_PKEY_MAP];
GO
GRANT SELECT
	ON [dbo].[VW_DIM_ITEM_PKEY_MAP]
	TO [portalapp_role]
GO
