SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_SCL_SEARCH]
AS
   SELECT * FROM [dbo].[TB_FCT_SCL_SEARCH];
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_SCL_SEARCH]
	TO [portalreporting_role]
GO
