SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_CATEGORY_SUB_CATEGORY_MEMBER_GC]
WITH SCHEMABINDING
AS
SELECT member.[ITEM_URN] AS [RESOURCE_ID], 
       member.[ITEM_BIZ_URN] AS [MEMBER_BIZ_URN],
       member.[HIERARCHY_PARENT_URN] AS [PARENT_RESOURCE_ID],
       member.[ITEM_BIZ_URN] AS   [CHILD_RESOURCE_ID],
       CAST('00001700-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [PARENT_RESOURCE_TYPE_ID],
       CAST('00001700-1000-0000-0000-000000000010' AS UNIQUEIDENTIFIER) AS [CHILD_RESOURCE_TYPE_ID],
       member.[EFFECTIVE_FROM],
       member.[EFFECTIVE_TO],        
       member.[MODIFIED_DATE],
       member.[MODIFIED_BY_ID],
       member.[CREATION_DATE],
       member.[CREATED_BY_ID],
       member.[DELETED],
       member.[HIDDEN],
       member.[SYSTEM],
       member.[LATEST],
       member.[CHANGE_STAMP],
       datagc.[GENERATION_COUNT],
       datagc.[CREATE_GENERATION_COUNT],
       datagc.[LAST_OPERATION]
        
FROM [dbo].[TS_DIM_CATEGORY_GC] datagc 
    
LEFT JOIN [dbo].[TB_DIM_CATEGORY] member
ON member.ITEM_URN = datagc.ITEM_URN

WHERE datagc.[ITEM_URN] > 0
AND member.[ROOT_CATEGORY_BIZ_URN] > 0;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_CATEGORY_SUB_CATEGORY_MEMBER_GC]
	TO [portalapp_role]
GO
