SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_CLU_RESOURCE_FOLDER_ITEM_MAPPING_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS RESOURCE_ID,
        clu.RESOURCE_FOLDER_MAPPING_ID AS CHILD_RESOURCE_ID,
        clu.ITEM_BIZ_URN AS PARENT_RESOURCE_ID,
        clu.ITEM_TYPE_URN,
        clu.PRIORITY,
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION],
        CAST('14D9AF56-0045-4BAF-B3E1-C27D2547E2FD' AS UNIQUEIDENTIFIER) AS CHILD_RESOURCE_TYPE_ID, -- MT_CLUSTER_RESOURCE_FOLDER_MAPPING
        CAST(itemType.ITEM_TYPE_ID AS UNIQUEIDENTIFIER) AS PARENT_RESOURCE_TYPE_ID -- ITEM
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
INNER JOIN [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT OUTER JOIN [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING] clu ON clu.RESOURCE_FOLDER_ITEM_MAPPING_ID = datagc.GUID_KEY
LEFT OUTER JOIN [dbo].[TE_DIM_ITEM_TYPE] itemType ON itemType.ITEM_TYPE_URN = clu.ITEM_TYPE_URN
WHERE   tablegc.TABLE_NAME = 'TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING';
GO
GRANT SELECT
	ON [dbo].[VW_CLU_RESOURCE_FOLDER_ITEM_MAPPING_GC]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[VW_CLU_RESOURCE_FOLDER_ITEM_MAPPING_GC]
	TO [portal_database_configuration_read_role]
GO
GRANT SELECT
	ON [dbo].[VW_CLU_RESOURCE_FOLDER_ITEM_MAPPING_GC]
	TO [portal_database_configuration_role]
GO
