SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VW_DIM_TIME_STD_CUBE
AS
SELECT  t.TIME_URN,
        t.INTERNAL_NAME AS TIME_KEY,
        t.NAME AS TIME_NAME,
        t.HOUR,
        t.MINUTE,
        t.TIME_VALUE,
        t.TIME_FORMULA,
        t.TIME_OPTIONS,
        t.SHIFT,
        t.EVENING,
        m.FIVE_MINUTE_URN,
        m.INTERNAL_NAME AS FIVE_MINUTE_KEY,
        m.NAME AS FIVE_MINUTE_NAME,
        m.MINUTE AS FIVE_MINUTE,
        m.PERIOD_START AS FIVE_MINUTE_START,
        m.PERIOD_END AS FIVE_MINUTE_END,
        m.TIME_FORMULA AS FIVE_MINUTE_FORMULA,
        m.TIME_OPTIONS AS FIVE_MINUTE_OPTIONS,
        q.QUARTER_HOUR_URN,
        q.INTERNAL_NAME AS QUARTER_HOUR_KEY,
        q.NAME AS QUARTER_HOUR_NAME,
        q.MINUTE AS QUARTER_HOUR,
        q.PERIOD_START AS QUARTER_HOUR_START,
        q.PERIOD_END AS QUARTER_HOUR_END,
        q.TIME_FORMULA AS QUARTER_HOUR_FORMULA,
        q.TIME_OPTIONS AS QUARTER_HOUR_OPTIONS,
        h.HALF_HOUR_URN,
        h.INTERNAL_NAME AS HALF_HOUR_KEY,
        h.NAME AS HALF_HOUR_NAME,
        h.MINUTE AS HALF_HOUR,
        h.PERIOD_START AS HALF_HOUR_START,
        h.PERIOD_END AS HALF_HOUR_END,
        h.TIME_FORMULA AS HALF_HOUR_FORMULA,
        h.TIME_OPTIONS AS HALF_HOUR_OPTIONS,
        r.HOUR_URN,
        r.INTERNAL_NAME AS HOUR_KEY,
        r.NAME AS HOUR_NAME,
        r.PERIOD_START AS HOUR_START,
        r.PERIOD_END AS HOUR_END,
        r.TIME_FORMULA AS HOUR_FORMULA,
        r.TIME_OPTIONS AS HOUR_OPTIONS
FROM    dbo.TB_DIM_TIME t
JOIN    dbo.TB_DIM_TIME_5M m ON m.FIVE_MINUTE_URN = t.FIVE_MINUTE_URN
JOIN    dbo.TB_DIM_TIME_QH q ON q.QUARTER_HOUR_URN = m.QUARTER_HOUR_URN
JOIN    dbo.TB_DIM_TIME_HH h ON h.HALF_HOUR_URN = q.HALF_HOUR_URN
JOIN    dbo.TB_DIM_TIME_H r ON r.HOUR_URN = h.HOUR_URN;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_TIME_STD_CUBE]
	TO [portalapp_role]
GO
