SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VW_DIM_KB_SESSION_OUTCOME_CUBE
AS
SELECT  SESSION_OUTCOME_URN,
        CAST(SESSION_OUTCOME_NAME AS NVARCHAR(50)) AS SESSION_OUTCOME_NAME,
        CAST(SESSION_OUTCOME_DESCRIPTION AS NVARCHAR(500)) AS SESSION_OUTCOME_DESCRIPTION
FROM    ( VALUES (1, 'Manual Logout', 'Manual Logout'), (2, 'Timeout', 'Timeout'),
        (3, 'Force Shutdown', 'Force Shutdown') ) a ( [SESSION_OUTCOME_URN], [SESSION_OUTCOME_NAME], [SESSION_OUTCOME_DESCRIPTION] );
GO
GRANT SELECT
	ON [dbo].[VW_DIM_KB_SESSION_OUTCOME_CUBE]
	TO [portalapp_role]
GO
