SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_VA_SESSION]
AS
    SELECT  *,
            1 AS [Row Count]
    FROM    [dbo].[VW_PARTITIONED_FCT_VA_SESSION];
GO
GRANT SELECT
	ON [dbo].[VW_FCT_VA_SESSION]
	TO [portalreporting_role]
GO
