SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_CMS_AGENT_INTERVAL_CUBE]
AS
SELECT  [PARTITION_URN],
        [PARTITION_GLOBAL_URN],
        [PARTITION_ID],
        [AGENT_URN],
        [ACD_URN],
        [SKILLGROUP_URN],
        [LOC_ID],
        [CLUSTER_RESOURCE_URN],
        x.[DATE_UTC_URN],
        x.[TIME_UTC_URN],
        tzd.[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],
        -1 AS [FLEXIBLE_DIMENSION_0],
        -1 AS [FLEXIBLE_DIMENSION_1],
        -1 AS [FLEXIBLE_DIMENSION_2],
        -1 AS [FLEXIBLE_DIMENSION_3],
        -1 AS [FLEXIBLE_DIMENSION_4],
        CAST(ABN_CALLS AS BIGINT) AS [Abn_calls],
        CAST(ABN_TIME AS BIGINT) AS [Abn_Time],
        CAST(ACCEPTED_INTRS AS BIGINT) AS [Accepted_Intrs],
        CAST(ACD_RELEASE AS BIGINT) AS [Acd_Release],
        CAST(ACD_AUX_OUT_CALLS AS BIGINT) AS [Acd_Aux_Out_Calls],
        CAST(ACD_CALLS AS BIGINT) AS [Acd_Calls],
        CAST(ACD_CALLS_R1 AS BIGINT) AS [Acd_Calls_R1],
        CAST(ACD_CALLS_R2 AS BIGINT) AS [Acd_Calls_R2],
        CAST(ACD_TIME AS BIGINT) AS [Acd_Time],
        CAST(ACW_IN_CALLS AS BIGINT) AS [Acw_In_Calls],
        CAST(ACW_IN_TIME AS BIGINT) AS [Acw_In_Time],
        CAST(ACW_OUT_ADJ_CALLS AS BIGINT) AS [Acw_Out_Adj_Calls],
        CAST(ACW_OUT_CALLS AS BIGINT) AS [Acw_Out_Calls],
        CAST(ACW_OUT_OFF_CALLS AS BIGINT) AS [Acw_Out_Off_Calls],
        CAST(ACW_OUT_OFF_TIME AS BIGINT) AS [Acw_Out_Off_Time],
        CAST(ACW_OUT_TIME AS BIGINT) AS [Acw_Out_Time],
        CAST(ACW_TIME AS BIGINT) AS [Acw_Time],
        CAST(ANS_RING_TIME AS BIGINT) AS [Ans_Ring_Time],
        CAST(ASSISTS AS BIGINT) AS [Assists],
        CAST(AUX_IN_CALLS AS BIGINT) AS [Aux_In_Calls],
        CAST(AUX_IN_TIME AS BIGINT) AS [Aux_In_Time],
        CAST(AUX_OUT_ADJ_CALLS AS BIGINT) AS [Aux_Out_Adj_Calls],
        CAST(AUX_OUT_CALLS AS BIGINT) AS [Aux_Out_Calls],
        CAST(AUX_OUT_OFF_CALLS AS BIGINT) AS [Aux_Out_Off_Calls],
        CAST(AUX_OUT_OFF_TIME AS BIGINT) AS [Aux_Out_Off_Time],
        CAST(AUX_OUT_TIME AS BIGINT) AS [Aux_Out_Time],
        CAST(CONFERENCE AS BIGINT) AS [Conference],
        CAST(DA_ABN_CALLS AS BIGINT) AS [DA_Abn_Calls],
        CAST(DA_ABN_TIME AS BIGINT) AS [DA_Abn_Time],
        CAST(DA_ACD_CALLS AS BIGINT) AS [DA_Acd_Calls],
        CAST(DA_ACD_TIME AS BIGINT) AS [DA_Acd_Time],
        CAST(DA_ACW_IN_CALLS AS BIGINT) AS [DA_Acw_In_Calls],
        CAST(DA_ACW_IN_TIME AS BIGINT) AS [DA_Acw_In_Time],
        CAST(DA_ACW_OADJ_CALLS AS BIGINT) AS [DA_Acw_oadj_Calls],
        CAST(DA_ACW_O_CALLS AS BIGINT) AS [DA_Acw_O_Calls],
        CAST(DA_ACW_O_OFF_CALLS AS BIGINT) AS [DA_Acw_O_Off_Calls],
        CAST(DA_ACW_O_OFF_TIME AS BIGINT) AS [DA_Acw_O_Off_Time],
        CAST(DA_ACW_O_TIME AS BIGINT) AS [DA_Acw_O_Time],
        CAST(DA_ACW_TIME AS BIGINT) AS [DA_Acw_Time],
        CAST(DA_ANS_TIME AS BIGINT) AS [DA_Ans_Time],
        CAST(DA_OTHER_CALLS AS BIGINT) AS [DA_Other_Calls],
        CAST(DA_OTHER_TIME AS BIGINT) AS [DA_Other_Time],
        CAST(DA_RELEASE AS BIGINT) AS [DA_Release],
        CAST(HOLD_ABN_CALLS AS BIGINT) AS [Hold_Abn_Calls],
        CAST(HOLD_ACD_TIME AS BIGINT) AS [Hold_Acd_Time],
        CAST(HOLD_CALLS AS BIGINT) AS [Hold_Calls],
        CAST(HOLD_TIME AS BIGINT) AS [Hold_Time],
        CAST(I_ACD_AUX_IN_TIME AS BIGINT) AS [I_Acd_Aux_In_Time],
        CAST(I_ACD_AUX_OUT_TIME AS BIGINT) AS [I_Acd_Aux_Out_Time],
        CAST(I_ACD_OTHER_TIME AS BIGINT) AS [I_Acd_Other_Time],
        CAST(I_ACD_TIME AS BIGINT) AS [I_Acd_Time],
        CAST(I_ACW_IN_TIME AS BIGINT) AS [I_Acw_In_Time],
        CAST(I_ACW_OUT_TIME AS BIGINT) AS [I_Acw_Out_Time],
        CAST(I_ACW_TIME AS BIGINT) AS [I_Acw_Time],
        CAST(I_AUX_IN_TIME AS BIGINT) AS [I_Aux_In_Time],
        CAST(I_AUX_OUT_TIME AS BIGINT) AS [I_Aux_Out_Time],
        CAST(I_AUX_STBY_TIME AS BIGINT) AS [I_Aux_Stby_Time],
        CAST(I_AUX_TIME AS BIGINT) AS [I_Aux_Time],
        CAST(I_AVAIL_TIME AS BIGINT) AS [I_Avail_Time],
        CAST(I_DA_ACD_TIME AS BIGINT) AS [I_DA_Acd_Time],
        CAST(I_DA_ACWTIME AS BIGINT) AS [I_DA_AcwTime],
        CAST(I_OTHER_STBY_TIME AS BIGINT) AS [I_Other_Stby_Time],
        CAST(I_OTHER_TIME AS BIGINT) AS [I_Other_Time],
        CAST(I_RING_TIME AS BIGINT) AS [I_Ring_Time],
        CAST(I_STAFF_TIME AS BIGINT) AS [I_Staff_Time],
        CAST(INCOMPLETE AS BIGINT) AS [Incomplete],
        CAST(INTR_NOTIFIES AS BIGINT) AS [Intr_Notifies],
        CAST(NO_ANS_REDIR AS BIGINT) AS [No_Ans_Redir],
        CAST(O_ACD_CALLS AS BIGINT) AS [O_Acd_Calls],
        CAST(O_ACD_TIME AS BIGINT) AS [O_Acd_Time],
        CAST(O_ACW_TIME AS BIGINT) AS [O_Acw_Time],
        CAST(PHANTOM_ABNS AS BIGINT) AS [Phantom_Abns],
        CAST(REJECTED_INTRS AS BIGINT) AS [Rejected_Intrs],
        CAST(RING_CALLS AS BIGINT) AS [Ring_Calls],
        CAST(RING_TIME AS BIGINT) AS [Ring_Time],
        CAST(TI_AUX_TIME AS BIGINT) AS [TI_Aux_Time],
        CAST(TI_AVAIL_TIME AS BIGINT) AS [TI_Avail_Time],
        CAST(TI_OTHER_TIME AS BIGINT) AS [TI_Other_Time],
        CAST(TI_STAFF_TIME AS BIGINT) AS [TI_Staff_Time],
        CAST(TRANSFERRED AS BIGINT) AS [Transferred],
        CAST(TALK_TIME_IN AS BIGINT) AS [Talk_Time_In],
        CAST(TALK_TIME_CALLS AS BIGINT) AS [Talk_Time_Calls],
        CAST(EXT_TALK_TIME_OUT AS BIGINT) AS [Ext_Talk_Time_Out],
        CAST(EXT_TALK_CALLS_OUT AS BIGINT) AS [Ext_Talk_Calls_Out],
        CAST(TOTAL_ACD_CALLS AS BIGINT) AS [Total_Acd_Calls],
        CAST(TOTAL_ACD_TIME AS BIGINT) AS [Total_Acd_Time],
        CAST(TOTAL_ACW_TIME AS BIGINT) AS [Total_Acw_Time],
        CAST([RSV_level] AS BIGINT) AS [RSV_level],
        CAST([Intr_Deliveries] AS BIGINT) AS [Intr_Deliveries],
        CAST([Icr_Pull_Calls] AS BIGINT) AS [Icr_Pull_Calls],
        CAST([Icr_Pull_Time] AS BIGINT) AS [Icr_Pull_Time],
        CAST([Da_Icr_Pull_Calls] AS BIGINT) AS [Da_Icr_Pull_Calls],
        CAST([Da_Icr_Pull_Time] AS BIGINT) AS [Da_Icr_Pull_Time],
        CAST([TI_Aux_Time0] AS BIGINT) AS [TI_Aux_Time0],
        CAST([TI_Aux_Time1] AS BIGINT) AS [TI_Aux_Time1],
        CAST([TI_Aux_Time2] AS BIGINT) AS [TI_Aux_Time2],
        CAST([TI_Aux_Time3] AS BIGINT) AS [TI_Aux_Time3],
        CAST([TI_Aux_Time4] AS BIGINT) AS [TI_Aux_Time4],
        CAST([TI_Aux_Time5] AS BIGINT) AS [TI_Aux_Time5],
        CAST([TI_Aux_Time6] AS BIGINT) AS [TI_Aux_Time6],
        CAST([TI_Aux_Time7] AS BIGINT) AS [TI_Aux_Time7],
        CAST([TI_Aux_Time8] AS BIGINT) AS [TI_Aux_Time8],
        CAST([TI_Aux_Time9] AS BIGINT) AS [TI_Aux_Time9],
        CAST([TI_Aux_Time10] AS BIGINT) AS [TI_Aux_Time10],
        CAST([TI_Aux_Time11] AS BIGINT) AS [TI_Aux_Time11],
        CAST([TI_Aux_Time12] AS BIGINT) AS [TI_Aux_Time12],
        CAST([TI_Aux_Time13] AS BIGINT) AS [TI_Aux_Time13],
        CAST([TI_Aux_Time14] AS BIGINT) AS [TI_Aux_Time14],
        CAST([TI_Aux_Time15] AS BIGINT) AS [TI_Aux_Time15],
        CAST([TI_Aux_Time16] AS BIGINT) AS [TI_Aux_Time16],
        CAST([TI_Aux_Time17] AS BIGINT) AS [TI_Aux_Time17],
        CAST([TI_Aux_Time18] AS BIGINT) AS [TI_Aux_Time18],
        CAST([TI_Aux_Time19] AS BIGINT) AS [TI_Aux_Time19],
        CAST([TI_Aux_Time20] AS BIGINT) AS [TI_Aux_Time20],
        CAST([TI_Aux_Time21] AS BIGINT) AS [TI_Aux_Time21],
        CAST([TI_Aux_Time22] AS BIGINT) AS [TI_Aux_Time22],
        CAST([TI_Aux_Time23] AS BIGINT) AS [TI_Aux_Time23],
        CAST([TI_Aux_Time24] AS BIGINT) AS [TI_Aux_Time24],
        CAST([TI_Aux_Time25] AS BIGINT) AS [TI_Aux_Time25],
        CAST([TI_Aux_Time26] AS BIGINT) AS [TI_Aux_Time26],
        CAST([TI_Aux_Time27] AS BIGINT) AS [TI_Aux_Time27],
        CAST([TI_Aux_Time28] AS BIGINT) AS [TI_Aux_Time28],
        CAST([TI_Aux_Time29] AS BIGINT) AS [TI_Aux_Time29],
        CAST([TI_Aux_Time30] AS BIGINT) AS [TI_Aux_Time30],
        CAST([TI_Aux_Time31] AS BIGINT) AS [TI_Aux_Time31],
        CAST([TI_Aux_Time32] AS BIGINT) AS [TI_Aux_Time32],
        CAST([TI_Aux_Time33] AS BIGINT) AS [TI_Aux_Time33],
        CAST([TI_Aux_Time34] AS BIGINT) AS [TI_Aux_Time34],
        CAST([TI_Aux_Time35] AS BIGINT) AS [TI_Aux_Time35],
        CAST([TI_Aux_Time36] AS BIGINT) AS [TI_Aux_Time36],
        CAST([TI_Aux_Time37] AS BIGINT) AS [TI_Aux_Time37],
        CAST([TI_Aux_Time38] AS BIGINT) AS [TI_Aux_Time38],
        CAST([TI_Aux_Time39] AS BIGINT) AS [TI_Aux_Time39],
        CAST([TI_Aux_Time40] AS BIGINT) AS [TI_Aux_Time40],
        CAST([TI_Aux_Time41] AS BIGINT) AS [TI_Aux_Time41],
        CAST([TI_Aux_Time42] AS BIGINT) AS [TI_Aux_Time42],
        CAST([TI_Aux_Time43] AS BIGINT) AS [TI_Aux_Time43],
        CAST([TI_Aux_Time44] AS BIGINT) AS [TI_Aux_Time44],
        CAST([TI_Aux_Time45] AS BIGINT) AS [TI_Aux_Time45],
        CAST([TI_Aux_Time46] AS BIGINT) AS [TI_Aux_Time46],
        CAST([TI_Aux_Time47] AS BIGINT) AS [TI_Aux_Time47],
        CAST([TI_Aux_Time48] AS BIGINT) AS [TI_Aux_Time48],
        CAST([TI_Aux_Time49] AS BIGINT) AS [TI_Aux_Time49],
        CAST([TI_Aux_Time50] AS BIGINT) AS [TI_Aux_Time50],
        CAST([TI_Aux_Time51] AS BIGINT) AS [TI_Aux_Time51],
        CAST([TI_Aux_Time52] AS BIGINT) AS [TI_Aux_Time52],
        CAST([TI_Aux_Time53] AS BIGINT) AS [TI_Aux_Time53],
        CAST([TI_Aux_Time54] AS BIGINT) AS [TI_Aux_Time54],
        CAST([TI_Aux_Time55] AS BIGINT) AS [TI_Aux_Time55],
        CAST([TI_Aux_Time56] AS BIGINT) AS [TI_Aux_Time56],
        CAST([TI_Aux_Time57] AS BIGINT) AS [TI_Aux_Time57],
        CAST([TI_Aux_Time58] AS BIGINT) AS [TI_Aux_Time58],
        CAST([TI_Aux_Time59] AS BIGINT) AS [TI_Aux_Time59],
        CAST([TI_Aux_Time60] AS BIGINT) AS [TI_Aux_Time60],
        CAST([TI_Aux_Time61] AS BIGINT) AS [TI_Aux_Time61],
        CAST([TI_Aux_Time62] AS BIGINT) AS [TI_Aux_Time62],
        CAST([TI_Aux_Time63] AS BIGINT) AS [TI_Aux_Time63],
        CAST([TI_Aux_Time64] AS BIGINT) AS [TI_Aux_Time64],
        CAST([TI_Aux_Time65] AS BIGINT) AS [TI_Aux_Time65],
        CAST([TI_Aux_Time66] AS BIGINT) AS [TI_Aux_Time66],
        CAST([TI_Aux_Time67] AS BIGINT) AS [TI_Aux_Time67],
        CAST([TI_Aux_Time68] AS BIGINT) AS [TI_Aux_Time68],
        CAST([TI_Aux_Time69] AS BIGINT) AS [TI_Aux_Time69],
        CAST([TI_Aux_Time70] AS BIGINT) AS [TI_Aux_Time70],
        CAST([TI_Aux_Time71] AS BIGINT) AS [TI_Aux_Time71],
        CAST([TI_Aux_Time72] AS BIGINT) AS [TI_Aux_Time72],
        CAST([TI_Aux_Time73] AS BIGINT) AS [TI_Aux_Time73],
        CAST([TI_Aux_Time74] AS BIGINT) AS [TI_Aux_Time74],
        CAST([TI_Aux_Time75] AS BIGINT) AS [TI_Aux_Time75],
        CAST([TI_Aux_Time76] AS BIGINT) AS [TI_Aux_Time76],
        CAST([TI_Aux_Time77] AS BIGINT) AS [TI_Aux_Time77],
        CAST([TI_Aux_Time78] AS BIGINT) AS [TI_Aux_Time78],
        CAST([TI_Aux_Time79] AS BIGINT) AS [TI_Aux_Time79],
        CAST([TI_Aux_Time80] AS BIGINT) AS [TI_Aux_Time80],
        CAST([TI_Aux_Time81] AS BIGINT) AS [TI_Aux_Time81],
        CAST([TI_Aux_Time82] AS BIGINT) AS [TI_Aux_Time82],
        CAST([TI_Aux_Time83] AS BIGINT) AS [TI_Aux_Time83],
        CAST([TI_Aux_Time84] AS BIGINT) AS [TI_Aux_Time84],
        CAST([TI_Aux_Time85] AS BIGINT) AS [TI_Aux_Time85],
        CAST([TI_Aux_Time86] AS BIGINT) AS [TI_Aux_Time86],
        CAST([TI_Aux_Time87] AS BIGINT) AS [TI_Aux_Time87],
        CAST([TI_Aux_Time88] AS BIGINT) AS [TI_Aux_Time88],
        CAST([TI_Aux_Time89] AS BIGINT) AS [TI_Aux_Time89],
        CAST([TI_Aux_Time90] AS BIGINT) AS [TI_Aux_Time90],
        CAST([TI_Aux_Time91] AS BIGINT) AS [TI_Aux_Time91],
        CAST([TI_Aux_Time92] AS BIGINT) AS [TI_Aux_Time92],
        CAST([TI_Aux_Time93] AS BIGINT) AS [TI_Aux_Time93],
        CAST([TI_Aux_Time94] AS BIGINT) AS [TI_Aux_Time94],
        CAST([TI_Aux_Time95] AS BIGINT) AS [TI_Aux_Time95],
        CAST([TI_Aux_Time96] AS BIGINT) AS [TI_Aux_Time96],
        CAST([TI_Aux_Time97] AS BIGINT) AS [TI_Aux_Time97],
        CAST([TI_Aux_Time98] AS BIGINT) AS [TI_Aux_Time98],
        CAST([TI_Aux_Time99] AS BIGINT) AS [TI_Aux_Time99],
        CAST([EVENT1] AS BIGINT) AS [Event1],
        CAST([EVENT2] AS BIGINT) AS [Event2],
        CAST([EVENT3] AS BIGINT) AS [Event3],
        CAST([EVENT4] AS BIGINT) AS [Event4],
        CAST([EVENT5] AS BIGINT) AS [Event5],
        CAST([EVENT6] AS BIGINT) AS [Event6],
        CAST([EVENT7] AS BIGINT) AS [Event7],
        CAST([EVENT8] AS BIGINT) AS [Event8],
        CAST([EVENT9] AS BIGINT) AS [Event9],
        CAST(EXTENSION AS BIGINT) AS [Extension],
        [Row Count] AS [Row Count]
FROM    [dbo].[VW_SUM_CMS_AGENT_INTERVAL] x
JOIN    [dbo].[VW_DIM_TIME_STD_CUBE] t ON x.[TIME_UTC_URN] = t.[TIME_URN]
JOIN    [dbo].[TS_ADM_TIME_ZONE_DATA] tzd ON tzd.[DATE_UTC_URN] = x.[DATE_UTC_URN]
                                             AND tzd.[TIME_UTC_URN] = t.[QUARTER_HOUR_URN];
GO
GRANT SELECT
	ON [dbo].[VW_SUM_CMS_AGENT_INTERVAL_CUBE]
	TO [portalapp_role]
GO
