SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[VW_SYS_MON_SPACE_USED]
AS
    SELECT  [CLUSTER_RESOURCE_URN],
            [TYPE],
            MAX([CALCULATION_DATE]) AS [CALCULATION_DATE],
            SUM(ISNULL([BASE_ROW_COUNT] * [BASE_SPACE_PER_ROW], 0) + ISNULL([PKEY_ROW_COUNT] * [PKEY_SPACE_PER_ROW], 0)) AS [ESTIMATED_SPACE_CONSUMED]
    FROM    [dbo].[TS_SYS_TABLE_SPACE_USED]
    GROUP BY [CLUSTER_RESOURCE_URN],
            [TYPE];
GO
GRANT SELECT
	ON [dbo].[VW_SYS_MON_SPACE_USED]
	TO [portalapp_role]
GO
