SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_IVR_CALL_EVENT]
AS
SELECT  *,
        1 AS [Row Count]
FROM    dbo.VW_PARTITIONED_FCT_IVR_CALL_EVENT;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_IVR_CALL_EVENT]
	TO [portalreporting_role]
GO
