SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_CMS_SKILLGROUP_INTERVAL_CUBE]
AS
SELECT  [PARTITION_URN],
        [PARTITION_GLOBAL_URN],
        [PARTITION_ID],
        [ACD_URN],
        [SKILLGROUP_URN],
        [CLUSTER_RESOURCE_URN],
        x.[DATE_UTC_URN],
        x.[TIME_UTC_URN],
        tzd.[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],
        -1 AS [FLEXIBLE_DIMENSION_0],
        -1 AS [FLEXIBLE_DIMENSION_1],
        -1 AS [FLEXIBLE_DIMENSION_2],
        -1 AS [FLEXIBLE_DIMENSION_3],
        -1 AS [FLEXIBLE_DIMENSION_4],
        CAST(I_STAFF_TIME AS BIGINT) AS [I_Staff_Time],
        CAST(I_AVAIL_TIME AS BIGINT) AS [I_Avail_Time],
        CAST(I_ACD_TIME AS BIGINT) AS [I_Acd_Time],
        CAST(I_ACW_TIME AS BIGINT) AS [I_Acw_Time],
        CAST(I_ACW_OUT_TIME AS BIGINT) AS [I_Acw_Out_Time],
        CAST(I_ACW_IN_TIME AS BIGINT) AS [I_Acw_In_Time],
        CAST(I_AUX_TIME AS BIGINT) AS [I_Aux_Time],
        CAST(I_AUX_OUT_TIME AS BIGINT) AS [I_Aux_Out_Time],
        CAST(I_AUX_IN_TIME AS BIGINT) AS [I_Aux_In_Time],
        CAST(I_OTHER_TIME AS BIGINT) AS [I_Other_Time],
        CAST(MAX_STAFFED AS BIGINT) AS [Max_Staffed],
        CAST(ACW_IN_CALLS AS BIGINT) AS [Acw_In_Calls],
        CAST(ACW_IN_TIME AS BIGINT) AS [Acw_In_Time],
        CAST(AUX_IN_CALLS AS BIGINT) AS [Aux_In_Calls],
        CAST(AUX_IN_TIME AS BIGINT) AS [Aux_In_Time],
        CAST(ACW_OUT_CALLS AS BIGINT) AS [Acw_Out_Calls],
        CAST(ACW_OUT_TIME AS BIGINT) AS [Acw_Out_Time],
        CAST(ACW_OUT_OFF_CALLS AS BIGINT) AS [Acw_Out_Off_Calls],
        CAST(ACW_OUT_OFF_TIME AS BIGINT) AS [Acw_Out_Off_Time],
        CAST(ACW_OUT_ADJ_CALLS AS BIGINT) AS [Acw_Out_Adj_Calls],
        CAST(AUX_OUT_CALLS AS BIGINT) AS [Aux_Out_Calls],
        CAST(AUX_OUT_TIME AS BIGINT) AS [Aux_Out_Time],
        CAST(AUX_OUT_OFF_CALLS AS BIGINT) AS [Aux_Out_Off_Calls],
        CAST(AUX_OUT_OFF_TIME AS BIGINT) AS [Aux_Out_Off_Time],
        CAST(AUX_OUT_ADJ_CALLS AS BIGINT) AS [Aux_Out_Adj_Calls],
        CAST(IN_FLOW_CALLS AS BIGINT) AS [In_Flow_Calls],
        CAST(ACD_CALLS AS BIGINT) AS [Acd_Calls],
        CAST(ANS_TIME AS BIGINT) AS [Ans_Time],
        CAST(ACD_TIME AS BIGINT) AS [Acd_Time],
        CAST(ACW_TIME AS BIGINT) AS [Acw_Time],
        CAST(O_ACD_CALLS AS BIGINT) AS [O_Acd_Calls],
        CAST(O_ACD_TIME AS BIGINT) AS [O_Acd_Time],
        CAST(O_ACW_TIME AS BIGINT) AS [O_Acw_Time],
        CAST(ACD_CALLS1 AS BIGINT) AS [Acd_Calls1],
        CAST(ACD_CALLS2 AS BIGINT) AS [Acd_Calls2],
        CAST(ACD_CALLS3 AS BIGINT) AS [Acd_Calls3],
        CAST(ACD_CALLS4 AS BIGINT) AS [Acd_Calls4],
        CAST(ACD_CALLS5 AS BIGINT) AS [Acd_Calls5],
        CAST(ACD_CALLS6 AS BIGINT) AS [Acd_Calls6],
        CAST(ACD_CALLS7 AS BIGINT) AS [Acd_Calls7],
        CAST(ACD_CALLS8 AS BIGINT) AS [Acd_Calls8],
        CAST(ACD_CALLS9 AS BIGINT) AS [Acd_Calls9],
        CAST(ACD_CALLS10 AS BIGINT) AS [Acd_Calls10],
        CAST(BACKUP_CALLS AS BIGINT) AS [Backup_Calls],
        CAST(HOLD_CALLS AS BIGINT) AS [Hold_Calls],
        CAST(HOLD_TIME AS BIGINT) AS [Hold_Time],
        CAST(HOLD_ABN_CALLS AS BIGINT) AS [Hold_Abn_Calls],
        CAST(TRANSFERRED AS BIGINT) AS [Transferred],
        CAST(CONFERENCE AS BIGINT) AS [Conference],
        CAST(ABN_CALLS AS BIGINT) AS [Abn_Calls],
        CAST(ABN_TIME AS BIGINT) AS [Abn_Time],
        CAST(ABN_CALLS1 AS BIGINT) AS [Abn_Calls1],
        CAST(ABN_CALLS2 AS BIGINT) AS [Abn_Calls2],
        CAST(ABN_CALLS3 AS BIGINT) AS [Abn_Calls3],
        CAST(ABN_CALLS4 AS BIGINT) AS [Abn_Calls4],
        CAST(ABN_CALLS5 AS BIGINT) AS [Abn_Calls5],
        CAST(ABN_CALLS6 AS BIGINT) AS [Abn_Calls6],
        CAST(ABN_CALLS7 AS BIGINT) AS [Abn_Calls7],
        CAST(ABN_CALLS8 AS BIGINT) AS [Abn_Calls8],
        CAST(ABN_CALLS9 AS BIGINT) AS [Abn_Calls9],
        CAST(ABN_CALLS10 AS BIGINT) AS [Abn_Calls10],
        CAST(DE_QUE_CALLS AS BIGINT) AS [DE_Que_Calls],
        CAST(DE_QUE_TIME AS BIGINT) AS [De_Que_Time],
        CAST(BUSY_CALLS AS BIGINT) AS [Busy_Calls],
        CAST(BUSY_TIME AS BIGINT) AS [Busy_Time],
        CAST(DISC_CALLS AS BIGINT) AS [Disc_Calls],
        CAST(DISC_TIME AS BIGINT) AS [Disc_Time],
        CAST(OUT_FLOW_CALLS AS BIGINT) AS [Out_Flow_Calls],
        CAST(OUT_FLOW_TIME AS BIGINT) AS [Out_Flow_Time],
        CAST(INTERFLOW_CALLS AS BIGINT) AS [Interflow_Calls],
        CAST(LOW_CALLS AS BIGINT) AS [Low_Calls],
        CAST(MED_CALLS AS BIGINT) AS [Med_Calls],
        CAST(HIGH_CALLS AS BIGINT) AS [High_Calls],
        CAST(TOP_CALLS AS BIGINT) AS [Top_Calls],
        CAST(ACCEPTABLE AS BIGINT) AS [Acceptable],
        CAST(SERVICE_LEVEL AS BIGINT) AS [Service_Level],
        CAST(PERIOD1 AS BIGINT) AS [Period1],
        CAST(PERIOD2 AS BIGINT) AS [Period2],
        CAST(PERIOD3 AS BIGINT) AS [Period3],
        CAST(PERIOD4 AS BIGINT) AS [Period4],
        CAST(PERIOD5 AS BIGINT) AS [Period5],
        CAST(PERIOD6 AS BIGINT) AS [Period6],
        CAST(PERIOD7 AS BIGINT) AS [Period7],
        CAST(PERIOD8 AS BIGINT) AS [Period8],
        CAST(PERIOD9 AS BIGINT) AS [Period9],
        CAST(MAX_IN_QUEUE AS BIGINT) AS [Max_In_Queue],
        CAST(MAX_OCW_TIME AS BIGINT) AS [Max_Ocw_Time],
        CAST(CALLS_OFFERED AS BIGINT) AS [Calls_Offered],
        CAST(PERIOD_CHG AS BIGINT) AS [Period_Chg],
        CAST(SVC_LEVEL_CHG AS BIGINT) AS [Svc_Level_Chg],
        CAST(I_RING_TIME AS BIGINT) AS [I_Ring_Time],
        CAST(RING_TIME AS BIGINT) AS [Ring_Time],
        CAST(RING_CALLS AS BIGINT) AS [Ring_Calls],
        CAST(ABN_RING_CALLS AS BIGINT) AS [Abn_Ring_Calls],
        CAST(O_ABN_CALLS AS BIGINT) AS [O_Abn_Calls],
        CAST(O_OTHER_CALLS AS BIGINT) AS [O_Other_Calls],
        CAST(DA_ACW_IN_CALLS AS BIGINT) AS [DA_Acw_In_Calls],
        CAST(DA_ACW_IN_TIME AS BIGINT) AS [DA_Acw_In_Time],
        CAST(DA_ACW_O_CALLS AS BIGINT) AS [DA_Acw_O_Calls],
        CAST(DA_ACW_O_TIME AS BIGINT) AS [DA_Acw_O_Time],
        CAST(NO_ANS_REDIR AS BIGINT) AS [No_Ans_Redir],
        CAST(ACD_AUX_OUT_CALLS AS BIGINT) AS [Acd_Aux_Out_Calls],
        CAST(I_ACD_AUX_OUT_TIME AS BIGINT) AS [I_Acd_Aux_Out_Time],
        CAST(I_ACD_AUX_IN_TIME AS BIGINT) AS [I_Acd_Aux_In_Time],
        CAST(I_ACD_OTHER_TIME AS BIGINT) AS [I_Acd_Other_Time],
        CAST(PHANTOM_ABNS AS BIGINT) AS [Phantom_Abns],
        CAST(OTHER_CALLS AS BIGINT) AS [Other_Calls],
        CAST(OTHER_TIME AS BIGINT) AS [Other_Time],
        CAST(SLVL_ABNS AS BIGINT) AS [Slvl_Abns],
        CAST(SLVL_OUT_FLOWS AS BIGINT) AS [Slvl_Out_Flows],
        CAST(I_ARRIVED AS BIGINT) AS [I_Arrived],
        CAST(I_DA_ACD_TIME AS BIGINT) AS [I_DA_Acd_Time],
        CAST(I_DA_ACW_TIME AS BIGINT) AS [I_DA_Acw_Time],
        CAST(I_T_AVAIL_TIME AS BIGINT) AS [I_T_Avail_Time],
        CAST(I_T_AUX_TIME AS BIGINT) AS [I_T_Aux_Time],
        CAST(MAXTOP AS BIGINT) AS [Maxtop],
        CAST(I_NORM_TIME AS BIGINT) AS [I_Norm_Time],
        CAST(I_OL1_TIME AS BIGINT) AS [I_OL1_Time],
        CAST(I_OL2_TIME AS BIGINT) AS [I_OL2_Time],
        CAST(I_T_OTHER_TIME AS BIGINT) AS [I_T_Other_Time],
        CAST(MAX_TOT_PERCENTS AS BIGINT) AS [Max_Tot_Percents],
        CAST(ACD_CALLS_R1 AS BIGINT) AS [Acd_Calls_R1],
        CAST(ACD_CALLS_R2 AS BIGINT) AS [Acd_Calls_R2],
        CAST(I_ACD_TIME_R1 AS BIGINT) AS [I_Acd_Time_R1],
        CAST(I_ACD_TIME_R2 AS BIGINT) AS [I_Acd_Time_R2],
        CAST(I_ACW_TIME_R1 AS BIGINT) AS [I_Acw_Time_R1],
        CAST(I_ACW_TIME_R2 AS BIGINT) AS [I_Acw_Time_R2],
        CAST(I_RING_TIME_R1 AS BIGINT) AS [I_Ring_Time_R1],
        CAST(I_RING_TIME_R2 AS BIGINT) AS [I_Ring_Time_R2],
        CAST(I_OTHER_TIME_R1 AS BIGINT) AS [I_Other_Time_R1],
        CAST(I_OTHER_TIME_R2 AS BIGINT) AS [I_Other_Time_R2],
        CAST(I_AUX_TIME_R1 AS BIGINT) AS [I_Aux_Time_R1],
        CAST(I_AUX_TIME_R2 AS BIGINT) AS [I_Aux_Time_R2],
        CAST(I_OTHER_STBY_TIME_R1 AS BIGINT) AS [I_Other_Stby_Time_R1],
        CAST(I_OTHER_STBY_TIME_R2 AS BIGINT) AS [I_Other_Stby_Time_R2],
        CAST(I_AUX_STBY_TIME_R1 AS BIGINT) AS [I_Aux_Stby_Time_R1],
        CAST(I_AUX_STBY_TIME_R2 AS BIGINT) AS [I_Aux_Stby_Time_R2],
        CAST(I_BEHIND_TIME AS BIGINT) AS [I_Behind_Time],
        CAST(I_AUTO_RESERVE_TIME AS BIGINT) AS [I_Auto_Reserve_Time],
        CAST(TARGET_PERCENT AS BIGINT) AS [Target_Percent],
        CAST(TARGET_PCT_CHG AS BIGINT) AS [Target_Pct_Chg],
        CAST(TARGET_SECONDS AS BIGINT) AS [Target_Seconds],
        CAST(TARGET_SEC_CHG AS BIGINT) AS [Target_Sec_Chg],
        CAST(TARGET_ACD_CALLS AS BIGINT) AS [Target_Acd_Calls],
        CAST(TARGET_ABNS AS BIGINT) AS [Target_Abns],
        CAST(TARGET_OUT_FLOWS AS BIGINT) AS [Target_Out_Flows],
        CAST(INTR_DELIVERIES AS BIGINT) AS [Intr_Deliveries],
        CAST(AG_SURP_DELIVERIES AS BIGINT) AS [Ag_Surp_Deliveries],
        CAST(AG_SURP_PREF_CALLS AS BIGINT) AS [Ag_Surp_Pref_Calls],
        CAST(AG_SURP_NPREF_CALLS AS BIGINT) AS [Ag_Surp_NPref_Calls],
        CAST(CALL_SURP_DELIVERIES AS BIGINT) AS [Call_Surp_Deliveries],
        CAST(ICR_PULL_CALLS AS BIGINT) AS [ICR_Pull_Calls],
        CAST(ICR_PULL_TIME AS BIGINT) AS [ICR_Pull_Time],
        CAST(ICR_PULL_RING_CALLS AS BIGINT) AS [ICR_Pull_Ring_Calls],
        CAST(REDIRECT_CALLS AS BIGINT) AS [Redirect_Calls],
        CAST(TALK_TIME_IN AS BIGINT) AS [Talk_Time_In],
        CAST(TALK_TIME_CALLS AS BIGINT) AS [Talk_Time_Calls],
        CAST(EXT_TALK_TIME_OUT AS BIGINT) AS [Ext_Talk_Time_Out],
        CAST(EXT_TALK_CALLS_OUT AS BIGINT) AS [Ext_Talk_Calls_Out],
        CAST(MAIN_ACD_CALLS AS BIGINT) AS [Main_Acd_Calls],
        CAST(ASSISTS AS BIGINT) AS [Assists],
        [Row Count] AS [Row Count]
FROM    [dbo].[VW_SUM_CMS_SKILLGROUP_INTERVAL] x
JOIN    [dbo].[VW_DIM_TIME_STD_CUBE] t ON x.[TIME_UTC_URN] = t.[TIME_URN]
JOIN    [dbo].[TS_ADM_TIME_ZONE_DATA] tzd ON tzd.[DATE_UTC_URN] = x.[DATE_UTC_URN]
                                             AND tzd.[TIME_UTC_URN] = t.[QUARTER_HOUR_URN];
GO
GRANT SELECT
	ON [dbo].[VW_SUM_CMS_SKILLGROUP_INTERVAL_CUBE]
	TO [portalapp_role]
GO
