SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_CLU_RESOURCE_FOLDER_MAPPING_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS RESOURCE_ID,
        clu.[FOLDER_ID] AS PARENT_RESOURCE_ID,
        clu.[RESOURCE_ID] AS CHILD_RESOURCE_ID,
        clu.[DEFAULT_IMPORT_LOCATION],
        clu.[REMOTE_TENANT_BUSINESS_URN],
        clu.[MAPPING_TYPE],
        clu.[XML_DATA],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION],
        CAST('0BD86837-0E52-4116-B8FD-857F6BE3CBD6' AS UNIQUEIDENTIFIER) AS CHILD_RESOURCE_TYPE_ID, -- IT_CLUSTER_RESOURCE_ID
        CAST('46B4A5CF-434D-4688-96B5-D950ACEEE178' AS UNIQUEIDENTIFIER) AS PARENT_RESOURCE_TYPE_ID -- IT_FOLDER
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_CLU_RESOURCE_FOLDER_MAPPING] clu ON clu.MAPPING_ID = datagc.GUID_KEY
WHERE   tablegc.TABLE_NAME = 'TB_CLU_RESOURCE_FOLDER_MAPPING';
GO
GRANT SELECT
	ON [dbo].[VW_CLU_RESOURCE_FOLDER_MAPPING_GC]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[VW_CLU_RESOURCE_FOLDER_MAPPING_GC]
	TO [portal_database_configuration_read_role]
GO
GRANT SELECT
	ON [dbo].[VW_CLU_RESOURCE_FOLDER_MAPPING_GC]
	TO [portal_database_configuration_role]
GO
