SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_IVR_CALL_15]
AS
SELECT  *
FROM    dbo.VW_PARTITIONED_SUM_IVR_CALL_15;
GO
GRANT SELECT
	ON [dbo].[VW_SUM_IVR_CALL_15]
	TO [portalreporting_role]
GO
