SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_PRECISION_QUEUE_MEDIA_ROUTING_DOMAIN_ICM_PROV]
AS
SELECT  pqmrd.CLUSTER_RESOURCE_ID,
        pqmrd.PKEY_MAP_URN AS PQMRD_PKEY_MAP_URN,
        CASE WHEN pqmrd.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > pqmrd.PKEY_EFFECTIVE_TO THEN 'P'
             ELSE pqmrd.STATUS
        END AS PQMRD_STATUS,
        CASE WHEN pqmrd.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > pqmrd.PKEY_EFFECTIVE_TO
             THEN CAST(1 AS BIT)
             ELSE CAST(0 AS BIT)
        END AS PQMRD_EXPIRED,
        pqmrd.PKEY_CHANGE_STAMP AS PQMRD_PKEY_CHANGE_STAMP,
        pqmrd.SOURCE_CHANGE_STAMP AS PQMRD_SOURCE_CHANGE_STAMP,
        pqmrd.MEMBER_URN AS PQMRD_MEMBER_URN,
        pqmrd.MEMBER_BIZ_URN AS PQMRD_MEMBER_BIZ_URN,
        pqmrd.PARENT_ITEM_BIZ_URN AS PQMRD_PARENT_ITEM_BIZ_URN,
        pqmrd.CHILD_ITEM_BIZ_URN AS PQMRD_CHILD_ITEM_BIZ_URN,
        pqmrd.PKEY1 AS PQMRD_PKEY1,
        pqmrd.PKEY2 AS PQMRD_PKEY2,
        mrd.PKEY1 AS MEDIA_ROUTING_DOMAIN_ID
FROM    dbo.VW_DIM_PRECISION_QUEUE_MEDIA_ROUTING_DOMAIN_MEMBER_PKEY pqmrd
JOIN    VW_DIM_MEDIA_ROUTING_DOMAIN_PKEY mrd ON pqmrd.PARENT_ITEM_BIZ_URN = mrd.ITEM_BIZ_URN
                                          AND mrd.LATEST = 1
                                          AND mrd.PKEY_LATEST = 1
WHERE   pqmrd.EFFECTIVE_FROM <= GETUTCDATE()
        AND pqmrd.STATUS <> 'D';
GO
GRANT SELECT
	ON [dbo].[VW_DIM_PRECISION_QUEUE_MEDIA_ROUTING_DOMAIN_ICM_PROV]
	TO [portalapp_role]
GO
