SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_SUM_IVR_APPLICATION_WEEKLY]
AS
SELECT  *
FROM    dbo.TB_SUM_IVR_APPLICATION_WEEKLY;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_SUM_IVR_APPLICATION_WEEKLY]
	TO [portalreporting_role]
GO
