SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[VW_SYS_MON_ETL_COMPONENT_SUMMARY]
AS
    SELECT  DATEADD(MI, DATEDIFF_BIG(MI, 0, [stst].[EXECUTION_END_DATETIME]) / 15 * 15, 0) AS [EXECUTION_END_DATETIME],
            [comp].[NAME] AS [COMPONENT_NAME],
            ISNULL([secondaryRes].[NAME], [res].[NAME]) AS [CLUSTER_NAME],
            MAX(DATEDIFF_BIG(ss, [stst].[MAX_DESTINATION_DATETIME], [stst].[MAX_SOURCE_DATETIME])) AS [LAG_SECONDS],
            MAX(DATEDIFF_BIG(DAY, [stst].[MAX_DESTINATION_DATETIME], [stst].[MAX_SOURCE_DATETIME])) AS [LAG_DAYS]
    FROM    [dbo].[TB_ETL_COMPONENT_INSTANCE] [inst]
    INNER JOIN [dbo].[TB_ETL_COMPONENT] [comp] ON [comp].[COMPONENT_ID] = [inst].[COMPONENT_ID]
    LEFT OUTER JOIN [dbo].[TB_ETL_COMPONENT_INSTANCE_EXECUTION] [stst] ON [stst].[INSTANCE_URN] = [inst].[INSTANCE_URN]
    INNER JOIN [dbo].[TB_CLU_RESOURCE] [res] ON [res].[RESOURCE_ID] = [inst].[CLUSTER_ID]
    INNER JOIN [dbo].[TE_ADM_CLUSTER_RESOURCE_TYPE] [ct] ON [ct].[CLUSTER_RESOURCE_TYPE_ID] = [res].[RESOURCE_TYPE_ID]
    LEFT OUTER JOIN [dbo].[TB_CLU_RESOURCE] [secondaryRes] ON [secondaryRes].[RESOURCE_ID] = [stst].[SECONDARY_SOURCE_CLUSTER_ID]
    LEFT OUTER JOIN [dbo].[TE_ADM_CLUSTER_RESOURCE_TYPE] [secondaryType] ON [secondaryType].[CLUSTER_RESOURCE_TYPE_ID] = [secondaryRes].[RESOURCE_TYPE_ID]
    GROUP BY DATEADD(MI, DATEDIFF_BIG(MI, 0, [stst].[EXECUTION_END_DATETIME]) / 15 * 15, 0),
            [comp].[NAME],
            ISNULL([secondaryRes].[NAME], [res].[NAME]);
GO
GRANT SELECT
	ON [dbo].[VW_SYS_MON_ETL_COMPONENT_SUMMARY]
	TO [portalapp_role]
GO
