SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_AGENT_SKILLGROUP_LOGOUT_CUBE] 
AS 
    SELECT * 
    FROM dbo.VW_FCT_AGENT_SKILLGROUP_LOGOUT;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_AGENT_SKILLGROUP_LOGOUT_CUBE]
	TO [portalapp_role]
GO
