SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE      VIEW dbo.VW_SEC_USER_GLOBAL_TASKS
--WITH SCHEMABINDING
AS
SELECT DISTINCT
        u.USER_ID,
        t.INTERNAL_NAME,
        t.CODE
FROM    VW_SEC_GLOBAL_ROLE_TASK_MAPPING AS t
JOIN    dbo.TB_SEC_POLICY_USER_ROLE pur ON pur.ROLE_ID = t.ROLE_ID
JOIN    dbo.TB_SEC_USER u ON u.USER_ID = pur.USER_ID
WHERE   u.USER_TYPE = 'U'
        AND u.DELETED = 0
        AND u.ENABLED = 1
UNION
SELECT DISTINCT
        u.USER_ID,
        t.INTERNAL_NAME,
        t.CODE
FROM    VW_SEC_GLOBAL_ROLE_TASK_MAPPING AS t
JOIN    dbo.TB_SEC_POLICY_USER_ROLE pur ON pur.ROLE_ID = t.ROLE_ID
JOIN    dbo.TB_SEC_USER g ON g.USER_ID = pur.USER_ID
JOIN    dbo.TB_SEC_GROUP_MEMBER gm ON gm.PARENT_ID = g.USER_ID
JOIN    dbo.TB_SEC_USER u ON u.USER_ID = gm.CHILD_ID
WHERE   g.USER_TYPE = 'G'
        AND u.DELETED = 0
        AND u.ENABLED = 1
        AND g.DELETED = 0
        AND g.ENABLED = 1;
GO
GRANT SELECT
	ON [dbo].[VW_SEC_USER_GLOBAL_TASKS]
	TO [portalapp_role]
GO
