SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_WFM_FORECAST]
--WITH ENCRYPTION
AS
   SELECT  * FROM dbo.VW_PARTITIONED_FCT_WFM_FORECAST;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_WFM_FORECAST]
	TO [portalreporting_role]
GO
