SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_ACTIVITY_ROUTING]
AS
   SELECT * FROM [dbo].[TB_FCT_ACTIVITY_ROUTING];
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_ACTIVITY_ROUTING]
	TO [portalreporting_role]
GO
