SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_FISCAL_YEAR_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[INT_KEY] AS RESOURCE_ID,
        dimFiscalYear.[NAME],
        dimFiscalYear.[START_DATE_TIME],
        dimFiscalYear.[END_DATE_TIME],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_DIM_FISCAL_YEAR] dimFiscalYear ON dimFiscalYear.FISCAL_YEAR_URN = datagc.INT_KEY
WHERE   tablegc.TABLE_NAME = 'TB_DIM_FISCAL_YEAR';
GO
GRANT SELECT
	ON [dbo].[VW_DIM_FISCAL_YEAR_GC]
	TO [portalapp_role]
GO
