SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VW_DIM_CODE_HIERARCHY
AS
SELECT  g1.INTERNAL_NAME AS PARENT_CODE_GROUP_INTERNAL_NAME,
        g1.NAME AS PARENT_CODE_GROUP_NAME,
        g1.ITEM_BIZ_URN AS PARENT_CODE_GROUP_URN,
        c1.INTERNAL_NAME AS PARENT_CODE_INTERNAL_NAME,
        c1.NAME AS PARENT_CODE_NAME,
        c1.ITEM_BIZ_URN AS PARENT_CODE_URN,
        g2.INTERNAL_NAME AS CHILD_CODE_GROUP_INTERNAL_NAME,
        g2.NAME AS CHILD_CODE_GROUP_NAME,
        g2.ITEM_BIZ_URN AS CHILD_CODE_GROUP_URN,
        c2.INTERNAL_NAME AS CHILD_CODE_INTERNAL_NAME,
        c2.NAME AS CHILD_CODE_NAME,
        c2.ITEM_BIZ_URN AS CHILD_CODE_URN
FROM    TB_DIM_CODE c1
JOIN    TB_DIM_CODE_CODE_GROUP_MEMBER m1 ON m1.CHILD_ITEM_BIZ_URN = c1.ITEM_BIZ_URN
                                            AND m1.LATEST = 1
JOIN    TB_DIM_CODE_GROUP g1 ON g1.ITEM_BIZ_URN = m1.PARENT_ITEM_BIZ_URN
                                AND g1.LATEST = 1
JOIN    TB_DIM_CODE_HIERARCHY h ON h.PARENT_CODE_URN = c1.ITEM_BIZ_URN
JOIN    TB_DIM_CODE c2 ON c2.ITEM_BIZ_URN = h.CHILD_CODE_URN
                          AND c2.LATEST = 1
JOIN    TB_DIM_CODE_CODE_GROUP_MEMBER m2 ON m2.CHILD_ITEM_BIZ_URN = c2.ITEM_BIZ_URN
                                            AND m2.LATEST = 1
JOIN    TB_DIM_CODE_GROUP g2 ON g2.ITEM_BIZ_URN = m2.PARENT_ITEM_BIZ_URN
                                AND g2.LATEST = 1
WHERE   c1.LATEST = 1;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_CODE_HIERARCHY]
	TO [portalapp_role]
GO
