SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_CLU_CLUSTER_RESOURCE_CUBE]
AS
SELECT  c.[RESOURCE_URN] AS [CLUSTER_RESOURCE_URN],
        c.[NAME] AS [CLUSTER_RESOURCE_NAME],
        COALESCE(t.[NAME], t.[INTERNAL_NAME]) AS [CLUSTER_RESOURCE_TYPE_NAME],
        COALESCE(c.[VERSION], '') AS [VERSION],
        COALESCE(REPLACE(REPLACE(REPLACE(c.[DESCRIPTION], CHAR(9), ''),
                                 CHAR(13), ''), CHAR(10), ''), '') COLLATE Latin1_General_100_CI_AS_SC AS [CLUSTER_RESOURCE_DESCRPTION],
        t.[MIN_RESOURCES] AS [MIN_RESOURCES],
        t.[MAX_RESOURCES] AS [MAX_RESOURCES],
        t.[MIN_RESOURCE_INSTANCES] AS [MIN_RESOURCE_INSTANCES],
        t.[MAX_RESOURCE_INSTANCES] AS [MAX_RESOURCE_INSTANCES],
        t.[IMPORT_SUPPORTED] AS [IMPORT_SUPPORTED]
FROM    [dbo].[TB_CLU_RESOURCE] c
JOIN    [dbo].[TE_ADM_CLUSTER_RESOURCE_TYPE] t ON c.RESOURCE_TYPE_ID = t.CLUSTER_RESOURCE_TYPE_ID
UNION
SELECT  -1 AS [CLUSTER_RESOURCE_URN],
        'Unknown' AS [CLUSTER_RESOURCE_NAME],
        'Unknown' AS [CLUSTER_RESOURCE_TYPE_NAME],
        '' AS [VERSION],
        'Cluster Resource value is not known' AS [CLUSTER_RESOURCE_DESCRPTION],
        0 AS [MIN_RESOURCES],
        NULL AS [MAX_RESOURCES],
        0 AS [MIN_RESOURCE_INSTANCES],
        0 AS [MAX_RESOURCE_INSTANCES],
        0 AS [IMPORT_SUPPORTED]
UNION
SELECT  -2 AS [CLUSTER_RESOURCE_URN],
        'None' AS [CLUSTER_RESOURCE_NAME],
        'None' AS [CLUSTER_RESOURCE_TYPE_NAME],
        '' AS [VERSION],
        'Cluster Resource does not exist' AS [CLUSTER_RESOURCE_DESCRPTION],
        0 AS [MIN_RESOURCES],
        NULL AS [MAX_RESOURCES],
        0 AS [MIN_RESOURCE_INSTANCES],
        0 AS [MAX_RESOURCE_INSTANCES],
        0 AS [IMPORT_SUPPORTED];
GO
GRANT SELECT
	ON [dbo].[VW_CLU_CLUSTER_RESOURCE_CUBE]
	TO [portalapp_role]
GO
