SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_HIERARCHY_LEVEL_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[INT_KEY] AS RESOURCE_ID,
        hierarchyLevel.[HIERARCHY_BUSINESS_URN],
        hierarchyLevel.[NAME],
        hierarchyLevel.[DESCRIPTION],
        hierarchyLevel.[CARDINALITY],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_DIM_HIERARCHY_LEVEL] hierarchyLevel ON hierarchyLevel.HIERARCHY_LEVEL_URN = datagc.INT_KEY
WHERE   tablegc.TABLE_NAME = 'TB_DIM_HIERARCHY_LEVEL';
GO
GRANT SELECT
	ON [dbo].[VW_DIM_HIERARCHY_LEVEL_GC]
	TO [portalapp_role]
GO
