SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_WFM_AGENT_SCHEDULE]
--WITH ENCRYPTION
AS
SELECT  *
FROM    dbo.TB_FCT_WFM_AGENT_SCHEDULE;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_WFM_AGENT_SCHEDULE]
	TO [portalreporting_role]
GO
