SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_ACTIVITY_CLASSIFICATION]
AS
    SELECT  *,
            1 AS [Row Count]
    FROM    [dbo].[VW_PARTITIONED_FCT_ACTIVITY_CLASSIFICATION];
GO
GRANT SELECT
	ON [dbo].[VW_FCT_ACTIVITY_CLASSIFICATION]
	TO [portalreporting_role]
GO
