SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_KNOWLEDGE_ARTICLE_READ_CONFIRMATION]
AS
SELECT  *
FROM    [dbo].[TB_FCT_KNOWLEDGE_ARTICLE_READ_CONFIRMATION];
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_KNOWLEDGE_ARTICLE_READ_CONFIRMATION]
	TO [portalreporting_role]
GO
