SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].VW_PARTITIONED_FCT_CMS_AGENT_STATE_TRACE
AS
SELECT  *
FROM    dbo.TB_FCT_CMS_AGENT_STATE_TRACE;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_CMS_AGENT_STATE_TRACE]
	TO [portalreporting_role]
GO
