SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_CMS_SKILLGROUP_INTERVAL]
AS
SELECT  *,
        1 AS [Row Count]
FROM    dbo.VW_PARTITIONED_SUM_CMS_SKILLGROUP_INTERVAL;
GO
GRANT SELECT
	ON [dbo].[VW_SUM_CMS_SKILLGROUP_INTERVAL]
	TO [portalapp_role]
GO
