SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_GHE_ANSWER_TYPE_CUBE]  
AS  
SELECT  CAST([ANSWER_TYPE_URN] AS INT) AS [ANSWER_TYPE_URN],  
        CAST([ANSWER_TYPE_NAME] AS NVARCHAR(50)) AS [ANSWER_TYPE_NAME],  
        CAST([ANSWER_TYPE_DESCRIPTION] AS NVARCHAR(500)) AS [ANSWER_TYPE_DESCRIPTION]  
FROM    ( VALUES ( -1, 'Unknown', 'Unknown'), ( 1, 'List', 'List'),    
        ( 2, 'Text', 'Text')
        ) [a] ( [ANSWER_TYPE_URN], [ANSWER_TYPE_NAME], [ANSWER_TYPE_DESCRIPTION] );
GO
GRANT SELECT
	ON [dbo].[VW_DIM_GHE_ANSWER_TYPE_CUBE]
	TO [portalapp_role]
GO
