SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_PERIPHERAL_INTERVAL]
AS
SELECT  [SUMMARIZED_URN],
        [DATE_UTC_URN],
        [TIME_UTC_URN],
        [DATE_URN],
        [TIME_URN],
        [PERIPHERAL_URN],
        [MEDIA_ROUTING_DOMAIN_URN],
        [CLUSTER_RESOURCE_URN],
        [DATE_TIME],
        [TIME_ZONE],
        [ACTIVE_PERIPHERAL_DATA_TIME],
        [ACTIVE_ROUTING_CLIENT_TIME],
        [ACTIVE_PERIPHERAL_TIME],
        [ACTIVE_CTI_SERVER_TIME],
        [CALLS_OFFERED],
        [SERVICE_LEVEL_CALLS_OFFERED],
        [SERVICE_LEVEL_CALLS],
        [SERVICE_LEVEL_ABAND],
        [SERVICE_LEVEL],
        [NUMBER_OF_SAMPLES],
        [MAX_CALLS_IN_PROGRESS],
        [TOTAL_CALLS_IN_PROGRESS_SAMPLES],
        [SERVICE_LEVEL_TYPE],
        [MAX_NUMBER_LOGGED_ON_AGENTS],
        [REPORTING_HALF_HOUR],
        [REPORTING_INTERVAL],
        [PARTITION_ID],
        1 AS [Row Count]
FROM    dbo.VW_PARTITIONED_SUM_PERIPHERAL_INTERVAL;
GO
GRANT SELECT
	ON [dbo].[VW_SUM_PERIPHERAL_INTERVAL]
	TO [portalreporting_role]
GO
