SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SCH_PROVISIONING_JOB_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS RESOURCE_ID,
        t.[FOLDER_ID] AS CONTAINER_ID,
        g.[TARGET_RESOURCE_SET_ID],
        g.[RESOURCE_PROVISIONING_TEMPLATE_ID],
        g.[LAST_EXECUTION_DATE],
        t.[TYPE],
        t.[NAME],
        t.[DESCRIPTION],
        t.[ENABLED],
        t.[DELETED],
        t.[ASSIGNED_TO_USER_ID],
        t.[FAILURE_COUNT],
        t.[CALENDAR_ID],
        t.[CREATION_DATE_TIME] AS CREATION_DATE,
        t.[MODIFIED_DATE_TIME] AS MODIFIED_DATE,
        t.[CREATED_BY_USER_ID] AS CREATED_BY_ID,
        t.[MODIFIED_BY_USER_ID] AS MODIFIED_BY_ID,
        t.[CHANGE_STAMP],
        t.[CUSTOM_XML_DATA],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_SCH_PROVISIONING_JOB] g ON g.ID = datagc.GUID_KEY
JOIN [dbo].[TB_SCH_TASK] t ON t.TASK_ID = g.ID
WHERE   tablegc.TABLE_NAME = 'TB_SCH_PROVISIONING_JOB';
GO
GRANT SELECT
	ON [dbo].[VW_SCH_PROVISIONING_JOB_GC]
	TO [portalapp_role]
GO
