SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SEC_GROUP_GROUP_MEMBER_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS [RESOURCE_ID],
        groupMember.[PARENT_ID] AS PARENT_RESOURCE_ID,
        groupMember.[CHILD_ID] AS CHILD_RESOURCE_ID,
        groupMember.[CALCULATED],
        groupMember.[CALCULATED_PARENT_ID],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION],
        CAST('E1C14D2E-7DF8-45ec-87CC-2687BA0A7CA2' AS UNIQUEIDENTIFIER) AS CHILD_RESOURCE_TYPE_ID, -- IT_GROUP
        CAST('E1C14D2E-7DF8-45ec-87CC-2687BA0A7CA2' AS UNIQUEIDENTIFIER) AS PARENT_RESOURCE_TYPE_ID -- IT_GROUP
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_SEC_GROUP_MEMBER] groupMember ON groupMember.MEMBER_ID = datagc.GUID_KEY
LEFT JOIN [dbo].[TB_SEC_USER] secUser ON secUser.USER_ID = groupMember.CHILD_ID
                                         AND secUser.USER_TYPE = 'G'
WHERE   tablegc.TABLE_NAME = 'TB_SEC_GROUP_GROUP_MEMBER';
GO
GRANT SELECT
	ON [dbo].[VW_SEC_GROUP_GROUP_MEMBER_GC]
	TO [portalapp_role]
GO
