SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_IVR_CALL_ICM_MAP]
AS
SELECT  *  FROM    dbo.VW_PARTITIONED_FCT_IVR_CALL_ICM_MAP;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_IVR_CALL_ICM_MAP]
	TO [portalreporting_role]
GO
