SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_CLU_RESOURCE_INSTANCE_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS RESOURCE_ID,
        clu.[RESOURCE_INSTANCE_ID],
        clu.[RESOURCE_ID] AS CLUSTER_RESOURCE_ID,
        clu.[IS_PUBLISHER],
        clu.[SYSTEM],
        clu.[XML_DATA],
        clu.[NAME],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_CLU_RESOURCE_INSTANCE] clu ON clu.RESOURCE_INSTANCE_ID = datagc.GUID_KEY
WHERE   tablegc.TABLE_NAME = 'TB_CLU_RESOURCE_INSTANCE';
GO
GRANT SELECT
	ON [dbo].[VW_CLU_RESOURCE_INSTANCE_GC]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[VW_CLU_RESOURCE_INSTANCE_GC]
	TO [portal_database_configuration_read_role]
GO
GRANT SELECT
	ON [dbo].[VW_CLU_RESOURCE_INSTANCE_GC]
	TO [portal_database_configuration_role]
GO
