SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_CHAT_SKILLGROUP_HH_CUBE]
--WITH ENCRYPTION
AS
SELECT  *
FROM    VW_SUM_CHAT_SKILLGROUP_HH;
GO
GRANT SELECT
	ON [dbo].[VW_SUM_CHAT_SKILLGROUP_HH_CUBE]
	TO [portalapp_role]
GO
