SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_HIERARCHY_STRUCTURE]
AS
SELECT  *
FROM    TB_DIM_AGENT;
/*
SELECT  hierarchy.INTERNAL_NAME AS HIERARCHY_INTERNAL_NAME,
        hierarchy.NAME AS HIERARCHY_NAME,
        hierarchy.ITEM_URN AS HIERARCHY_URN,
        hierarchy.EFFECTIVE_FROM AS HIERARCHY_EFFECTIVE_FROM,
        hierarchy.EFFECTIVE_TO AS HIERARCHY_EFFECTIVE_TO,
        hierarchy.DELETED AS HIERARCHY_DELETED,
        hierarchy.LATEST AS HIERARCHY_LATEST,
        node.INTERNAL_NAME AS NODE_INTERNAL_NAME,
        node.NAME AS NODE_NAME,
        node.ITEM_URN AS NODE_URN,
        node.HIERARCHY_PARENT_URN AS HIERARCHY_PARENT_URN,
        node.EFFECTIVE_FROM AS NODE_EFFECTIVE_FROM,
        node.EFFECTIVE_TO AS NODE_EFFECTIVE_TO,
        node.DELETED AS NODE_DELETED,
        node.LATEST AS NODE_LATEST,
        node.PARENT_URN AS NODE_PARENT_URN
FROM    VW_DIM_HIERARCHY AS hierarchy
JOIN    VW_DIM_HIERARCHY_NODE AS node ON hierarchy.PARENT_URN = node.HIERARCHY_BUSINESS_URN
                                            AND node.EFFECTIVE_FROM BETWEEN hierarchy.EFFECTIVE_FROM AND hierarchy.EFFECTIVE_TO;
*/
GO
GRANT SELECT
	ON [dbo].[VW_DIM_HIERARCHY_STRUCTURE]
	TO [portalapp_role]
GO
