SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_GHE_CLUSTER_GHE_CLUSTER_GROUP_MEMBER_CUBE]
WITH SCHEMABINDING
AS
SELECT  i.[MEMBER_URN],
        i.[MEMBER_BIZ_URN],
        CAST('9C60C5D4-400C-47E2-AD9A-BCDA2244B79B' AS UNIQUEIDENTIFIER) AS [MEMBER_TYPE_ID],
        i.[PARENT_ITEM_BIZ_URN],
        i.[CHILD_ITEM_BIZ_URN],
        i.[EFFECTIVE_FROM],
        i.[EFFECTIVE_TO],
        i.[DELETED],
        i.[HIDDEN],
        i.[SYSTEM],
        i.[LATEST],
        i.[CHANGE_STAMP],
        1 AS [Row Count]
FROM    [dbo].[TB_DIM_GHE_CLUSTER_GHE_CLUSTER_GROUP_MEMBER] i;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_GHE_CLUSTER_GHE_CLUSTER_GROUP_MEMBER_CUBE]
	TO [portalapp_role]
GO
