SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_EMAIL_CASE_SNAPSHOT]
AS
SELECT  *
FROM    [dbo].[TB_FCT_EMAIL_CASE_SNAPSHOT];
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_EMAIL_CASE_SNAPSHOT]
	TO [portalreporting_role]
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_EMAIL_CASE_SNAPSHOT]
	TO [portal_default_mediator_role]
GO
