SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_SUM_IVR_APPLICATION_15]
AS
SELECT  *
FROM    dbo.TB_SUM_IVR_APPLICATION_15;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_SUM_IVR_APPLICATION_15]
	TO [portalreporting_role]
GO
