SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VW_ADM_TABLE_GENERATION_COUNT
WITH SCHEMABINDING
AS
SELECT  TABLE_GENERATION_COUNT_URN,
        TABLE_NAME,
        GENERATION_COUNT,
        MODIFIED_DATE
FROM    dbo.TS_ADM_TABLE_GENERATION_COUNT;
GO
GRANT SELECT
	ON [dbo].[VW_ADM_TABLE_GENERATION_COUNT]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[VW_ADM_TABLE_GENERATION_COUNT]
	TO [portal_database_configuration_read_role]
GO
GRANT SELECT
	ON [dbo].[VW_ADM_TABLE_GENERATION_COUNT]
	TO [portal_database_configuration_role]
GO
