SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_KB_SEARCH_STRING_CUBE]
WITH SCHEMABINDING
AS
SELECT  [ITEM_URN],
        [TENANT_BIZ_URN],
        [TENANT_NAME],
        [SEARCH_STRING]
FROM    [dbo].[VW_DIM_KB_SEARCH_STRING];
GO
GRANT SELECT
	ON [dbo].[VW_DIM_KB_SEARCH_STRING_CUBE]
	TO [portalapp_role]
GO
