SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_ADM_PROPERTY_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS RESOURCE_ID,
        admProperty.[PROPERTY_KEY] AS INTERNAL_NAME,
        admProperty.[PROPERTY_VALUE],
        admProperty.[MODIFIED_DATE],
        admProperty.[SYSTEM],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_ADM_PROPERTY] admProperty ON admProperty.PROPERTY_ID = datagc.GUID_KEY
WHERE   tablegc.TABLE_NAME = 'TB_ADM_PROPERTY';
GO
GRANT SELECT
	ON [dbo].[VW_ADM_PROPERTY_GC]
	TO [portalapp_role]
GO
