SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[VW_DIM_GHE_QUESTION_GHE_ANSWER_MEMBER]
WITH SCHEMABINDING
AS
    SELECT
        i.[MEMBER_URN],
        i.[MEMBER_BIZ_URN],
        CAST('645ac84a-d580-4c9c-ad36-3ec15a86e82c' AS UNIQUEIDENTIFIER) AS [MEMBER_TYPE_ID],
        i.[PARENT_ITEM_BIZ_URN],
        i.[CHILD_ITEM_BIZ_URN],
        i.[EFFECTIVE_FROM],
        i.[EFFECTIVE_TO],
        i.[DELETED],
        i.[HIDDEN],
        i.[SYSTEM],
        i.[LATEST],
        i.[CHANGE_STAMP]
    FROM [dbo].[TB_DIM_GHE_QUESTION_GHE_ANSWER_MEMBER] i;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_GHE_QUESTION_GHE_ANSWER_MEMBER]
	TO [portalapp_role]
GO
