SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_CMS_VDN_INTERVAL_CUBE]
AS
SELECT  [PARTITION_URN],
        [PARTITION_GLOBAL_URN],
        [PARTITION_ID],
        [ACD_URN],
        [VDN_URN],
        [VECTOR_URN],
        [CLUSTER_RESOURCE_URN],
        x.[DATE_UTC_URN],
        x.[TIME_UTC_URN],
        tzd.[OLAP_DATETIME_UTC] AS [DATETIME_UTC_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_0] AS [TIME_ZONE_0_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_1] AS [TIME_ZONE_1_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_2] AS [TIME_ZONE_2_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_3] AS [TIME_ZONE_3_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_4] AS [TIME_ZONE_4_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_5] AS [TIME_ZONE_5_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_6] AS [TIME_ZONE_6_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_7] AS [TIME_ZONE_7_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_8] AS [TIME_ZONE_8_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_9] AS [TIME_ZONE_9_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_10] AS [TIME_ZONE_10_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_11] AS [TIME_ZONE_11_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_12] AS [TIME_ZONE_12_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_13] AS [TIME_ZONE_13_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_14] AS [TIME_ZONE_14_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_15] AS [TIME_ZONE_15_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_16] AS [TIME_ZONE_16_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_17] AS [TIME_ZONE_17_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_18] AS [TIME_ZONE_18_URN],
        tzd.[OLAP_DATETIME_TIMEZONE_19] AS [TIME_ZONE_19_URN],
        -1 AS [FLEXIBLE_DIMENSION_0],
        -1 AS [FLEXIBLE_DIMENSION_1],
        -1 AS [FLEXIBLE_DIMENSION_2],
        -1 AS [FLEXIBLE_DIMENSION_3],
        -1 AS [FLEXIBLE_DIMENSION_4],
        CAST(IN_FLOW_CALLS AS BIGINT) AS [In_Flow_Calls],
        CAST(ANS_TIME AS BIGINT) AS [Ans_Time],
        CAST(ACD_CALLS AS BIGINT) AS [Acd_Calls],
        CAST(ACD_TIME AS BIGINT) AS [Acd_Time],
        CAST(BACKUP_CALLS AS BIGINT) AS [Backup_Calls],
        CAST(TRANSFERRED AS BIGINT) AS [Transferred],
        CAST(ABN_CALLS AS BIGINT) AS [Abn_Calls],
        CAST(ABN_TIME AS BIGINT) AS [Abn_Time],
        CAST(ABN_QUE_CALLS AS BIGINT) AS [Abn_Que_Calls],
        CAST(BUSY_CALLS AS BIGINT) AS [Busy_Calls],
        CAST(BUSY_TIME AS BIGINT) AS [Busy_Time],
        CAST(DISC_CALLS AS BIGINT) AS [Disc_Calls],
        CAST(DISC_TIME AS BIGINT) AS [Disc_Time],
        CAST(OTHER_CALLS AS BIGINT) AS [Other_Calls],
        CAST(OTHER_TIME AS BIGINT) AS [Other_Time],
        CAST(OUT_FLOW_CALLS AS BIGINT) AS [Out_Flow_Calls],
        CAST(OUT_FLOW_TIME AS BIGINT) AS [Out_Flow_Time],
        CAST(INTERFLOW_CALLS AS BIGINT) AS [Interflow_Calls],
        CAST(LOOKFLOW_CALLS AS BIGINT) AS [Lookflow_Calls],
        CAST(LOOK_ATTEMPTS AS BIGINT) AS [Look_Attempts],
        CAST(ADJ_ROUTED AS BIGINT) AS [Adj_Routed],
        CAST(ADJ_ATTEMPTS AS BIGINT) AS [Adj_Attempts],
        CAST(IN_TIME AS BIGINT) AS [In_Time],
        CAST(IN_CALLS AS BIGINT) AS [In_Calls],
        CAST(CONNECT_CALLS AS BIGINT) AS [Connect_Calls],
        CAST(CONNECT_TIME AS BIGINT) AS [Connect_Time],
        CAST(ACCEPTABLE AS BIGINT) AS [Acceptable],
        CAST(ACW_TIME AS BIGINT) AS [Acw_Time],
        CAST(ANS_CONN_CALLS1 AS BIGINT) AS [Ans_Conn_Calls1],
        CAST(ANS_CONN_CALLS2 AS BIGINT) AS [Ans_Conn_Calls2],
        CAST(ANS_CONN_CALLS3 AS BIGINT) AS [Ans_Conn_Calls3],
        CAST(ANS_CONN_CALLS4 AS BIGINT) AS [Ans_Conn_Calls4],
        CAST(ANS_CONN_CALLS5 AS BIGINT) AS [Ans_Conn_Calls5],
        CAST(ANS_CONN_CALLS6 AS BIGINT) AS [Ans_Conn_Calls6],
        CAST(ANS_CONN_CALLS7 AS BIGINT) AS [Ans_Conn_Calls7],
        CAST(ANS_CONN_CALLS8 AS BIGINT) AS [Ans_Conn_Calls8],
        CAST(ANS_CONN_CALLS9 AS BIGINT) AS [Ans_Conn_Calls9],
        CAST(ANS_CONN_CALLS10 AS BIGINT) AS [Ans_Conn_Calls10],
        CAST(ABN_CALLS1 AS BIGINT) AS [Abn_Calls1],
        CAST(ABN_CALLS2 AS BIGINT) AS [Abn_Calls2],
        CAST(ABN_CALLS3 AS BIGINT) AS [Abn_Calls3],
        CAST(ABN_CALLS4 AS BIGINT) AS [Abn_Calls4],
        CAST(ABN_CALLS5 AS BIGINT) AS [Abn_Calls5],
        CAST(ABN_CALLS6 AS BIGINT) AS [Abn_Calls6],
        CAST(ABN_CALLS7 AS BIGINT) AS [Abn_Calls7],
        CAST(ABN_CALLS8 AS BIGINT) AS [Abn_Calls8],
        CAST(ABN_CALLS9 AS BIGINT) AS [Abn_Calls9],
        CAST(ABN_CALLS10 AS BIGINT) AS [Abn_Calls10],
        CAST(PERIOD1 AS BIGINT) AS [Period1],
        CAST(PERIOD2 AS BIGINT) AS [Period2],
        CAST(PERIOD3 AS BIGINT) AS [Period3],
        CAST(PERIOD4 AS BIGINT) AS [Period4],
        CAST(PERIOD5 AS BIGINT) AS [Period5],
        CAST(PERIOD6 AS BIGINT) AS [Period6],
        CAST(PERIOD7 AS BIGINT) AS [Period7],
        CAST(PERIOD8 AS BIGINT) AS [Period8],
        CAST(PERIOD9 AS BIGINT) AS [Period9],
        CAST(SVC_LEVEL_CHG AS BIGINT) AS [Svc_Level_Chg],
        CAST(PERIOD_CHG AS BIGINT) AS [Period_Chg],
        CAST(ABN_RING_CALLS AS BIGINT) AS [Abn_Ring_Calls],
        CAST(RING_TIME AS BIGINT) AS [Ring_Time],
        CAST(RING_CALLS AS BIGINT) AS [Ring_Calls],
        CAST(HOLD_ABN_CALLS AS BIGINT) AS [Hold_Abn_Calls],
        CAST(HOLD_CALLS AS BIGINT) AS [Hold_Calls],
        CAST(HOLD_TIME AS BIGINT) AS [Hold_Time],
        CAST(MAX_OCW_TIME AS BIGINT) AS [Max_Ocw_Time],
        CAST(MAX_WAITING AS BIGINT) AS [Max_Waiting],
        CAST(CONN_TALK_TIME AS BIGINT) AS [Conn_Talk_Time],
        CAST(NO_ANS_REDIR AS BIGINT) AS [No_Ans_Redir],
        [SKILL1] AS [Skill1],
        [SKILL2] AS [Skill2],
        [SKILL3] AS [Skill3],
        CAST(SKILL_CALLS1 AS BIGINT) AS [skill_Calls1],
        CAST(SKILL_CALLS2 AS BIGINT) AS [skill_Calls2],
        CAST(SKILL_CALLS3 AS BIGINT) AS [skill_Calls3],
        CAST(SKILL_TIME1 AS BIGINT) AS [Skill_Time1],
        CAST(SKILL_TIME2 AS BIGINT) AS [Skill_Time2],
        CAST(SKILL_TIME3 AS BIGINT) AS [Skill_Time3],
        CAST(SKILL_ACW_TIME1 AS BIGINT) AS [Skill_Acw_Time1],
        CAST(SKILL_ACW_TIME2 AS BIGINT) AS [Skill_Acw_Time2],
        CAST(SKILL_ACW_TIME3 AS BIGINT) AS [Skill_Acw_Time3],
        CAST(INCOMPLETE AS BIGINT) AS [Incomplete],
        CAST(HOLD_ACD_CALLS AS BIGINT) AS [Hold_Acd_Calls],
        CAST(HOLD_ACD_TIME AS BIGINT) AS [Hold_Acd_Time],
        CAST(PHANTOM_ABNS AS BIGINT) AS [Phantom_Abns],
        CAST(RETURN_CALLS AS BIGINT) AS [Return_Calls],
        CAST(VDISC_CALLS AS BIGINT) AS [VDisc_Calls],
        CAST(SLVL_ABNS AS BIGINT) AS [Slvl_Abns],
        CAST(SLVL_OUTFLOWS AS BIGINT) AS [Slvl_Outflows],
        CAST(I_ARRIVED AS BIGINT) AS [I_Arrived],
        CAST(BSR_PLAN AS BIGINT) AS [Bsr_Plan],
        CAST(DEFLECT_CALLS AS BIGINT) AS [Deflect_Calls],
        CAST(NET_DISC_CALLS AS BIGINT) AS [Net_Disc_Calls],
        CAST(NET_IN_CALLS AS BIGINT) AS [Net_In_Calls],
        CAST(NET_IN_TIME AS BIGINT) AS [Net_In_time],
        CAST(NET_POLLS AS BIGINT) AS [Net_Polls],
        CAST(ACD_CALLS_R1 AS BIGINT) AS [Acd_Calls_R1],
        CAST(ACD_CALLS_R2 AS BIGINT) AS [Acd_Calls_R2],
        CAST(AG_SURP_DELIVERIES AS BIGINT) AS [Ag_Surp_Deliveries],
        CAST(AG_SURP_PREF_CALLS AS BIGINT) AS [Ag_Surp_Pref_Calls],
        CAST(AG_SURP_NPREF_CALLS AS BIGINT) AS [Ag_Surp_NPref_Calls],
        CAST(CALL_SURP_DELIVERIES AS BIGINT) AS [Call_Surp_Deliveries],
        CAST(ICR_PULL_CALLS AS BIGINT) AS [ICR_Pull_Calls],
        CAST(ICR_PULL_TIME AS BIGINT) AS [ICR_Pull_Time],
        CAST(ICR_PULL_QUE_CALLS AS BIGINT) AS [ICR_Pull_Que_Calls],
        CAST(ICR_PULL_RING_CALLS AS BIGINT) AS [ICR_Pull_Ring_Calls],
        CAST(BUSY_DISCONNECT AS BIGINT) AS [Busy_Disconnect],
        CAST(MAIN_ACD_CALLS AS BIGINT) AS [Main_Acd_Calls],
        CAST(SERVICE_LEVEL AS BIGINT) AS [Service_level],
        [Row Count] AS [Row Count]
FROM    [dbo].[VW_SUM_CMS_VDN_INTERVAL] x
JOIN    [dbo].[VW_DIM_TIME_STD_CUBE] t ON x.TIME_UTC_URN = t.[TIME_URN]
JOIN    [dbo].[TS_ADM_TIME_ZONE_DATA] tzd ON tzd.[DATE_UTC_URN] = x.DATE_UTC_URN
                                             AND tzd.[TIME_UTC_URN] = t.[QUARTER_HOUR_URN];
GO
GRANT SELECT
	ON [dbo].[VW_SUM_CMS_VDN_INTERVAL_CUBE]
	TO [portalapp_role]
GO
