SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_SUM_CAMPAIGN_QUERY_RULE_INTERVAL]
AS
SELECT  [SUMMARIZED_URN],
        [DATE_URN],
        [TIME_URN],
        [DATE_UTC_URN],
        [TIME_UTC_URN],
        [CAMPAIGN_URN],
        [QUERY_RULE_URN],
        [CLUSTER_RESOURCE_URN],
        [DATE_TIME],
        [TIME_ZONE],
        [ABANDON_DETECT],
        [ABANDON_TO_IVR],
        [AGENT_CLOSED_DETECT],
        [AGENT_REJECTED_DETECT],
        [ANSWERING_MACHINE_DETECT],
        [BUSY_DETECT],
        [CALLBACK_COUNT],
        [CANCELLED_DETECT],
        [CONTACTS_ATTEMPTED],
        [CUSTOMER_ABANDON_DETECT],
        [CUSTOMER_NOT_HOME],
        [FAX_DETECT],
        [NETWORK_ANS_MACHINE_DETECT],
        [NO_ANSWER_DETECT],
        [NO_DIAL_TONE_DETECT],
        [NO_RINGBACK_DETECT],
        [PERSONAL_CALLBACK_COUNT],
        [WRONG_NUMBER_COUNT],
        [VOICE_DETECT],
        [SIT_TONE_DETECT],
        [TALK_TIME],
        [WRAPUP_TIME],
        [CAMPAIGN_OUT_OF_NUMBERS],
        [LOW_NOISE_VOLUME],
        [QUERY_RULE_ACTIVE_TIME],
        [REPORTING_HALF_HOUR],
        [REPORTING_INTERVAL],
        [PARTITION_ID],
        1 AS [Row Count]
FROM    dbo.VW_PARTITIONED_SUM_CAMPAIGN_QUERY_RULE_INTERVAL;
GO
GRANT SELECT
	ON [dbo].[VW_SUM_CAMPAIGN_QUERY_RULE_INTERVAL]
	TO [portalreporting_role]
GO
