SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_PRECISION_QUEUE_BUCKET_INTERVALS_ICM_PROV]
AS
SELECT  pqbi.CLUSTER_RESOURCE_ID,
        pqbi.PKEY_MAP_URN AS PQBI_PKEY_MAP_URN,
        CASE WHEN pqbi.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > pqbi.PKEY_EFFECTIVE_TO THEN 'P'
             ELSE pqbi.STATUS
        END AS PQBI_STATUS,
        CASE WHEN pqbi.STATUS NOT IN ( 'D', 'E' )
                  AND GETUTCDATE() > pqbi.PKEY_EFFECTIVE_TO
             THEN CAST(1 AS BIT)
             ELSE CAST(0 AS BIT)
        END AS PQBI_EXPIRED,
        pqbi.PKEY_CHANGE_STAMP AS PQBI_PKEY_CHANGE_STAMP,
        pqbi.SOURCE_CHANGE_STAMP AS PQBI_SOURCE_CHANGE_STAMP,
        pqbi.MEMBER_URN AS PQBI_MEMBER_URN,
        pqbi.MEMBER_BIZ_URN AS PQBI_MEMBER_BIZ_URN,
        pqbi.PARENT_ITEM_BIZ_URN AS PQBI_PARENT_ITEM_BIZ_URN,
        pqbi.CHILD_ITEM_BIZ_URN AS PQBI_CHILD_ITEM_BIZ_URN,
        pqbi.PKEY1 AS PQBI_PKEY1,
        pqbi.PKEY2 AS PQBI_PKEY2,
        bi.PKEY1 AS BUCKET_INTERVAL_ID
FROM    VW_DIM_PRECISION_QUEUE_BUCKET_INTERVAL_MEMBER_PKEY pqbi
JOIN    VW_DIM_BUCKET_INTERVAL_PKEY bi ON pqbi.PARENT_ITEM_BIZ_URN = bi.ITEM_BIZ_URN
                                          AND bi.LATEST = 1
                                          AND bi.PKEY_LATEST = 1
WHERE   pqbi.EFFECTIVE_FROM <= GETUTCDATE()
        AND pqbi.STATUS <> 'D';
GO
GRANT SELECT
	ON [dbo].[VW_DIM_PRECISION_QUEUE_BUCKET_INTERVALS_ICM_PROV]
	TO [portalapp_role]
GO
