SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DIM_CODE_CONSTRAINT_TYPE_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS RESOURCE_ID,
        c.[CODE_CONSTRAINT_TYPE_ID],
        c.[NAME],
        c.[INTERNAL_NAME],
        c.[DESCRIPTION],
        c.[BASE_DATA_TYPE],
        c.[HIDDEN],
        c.[ENABLED],
        c.[SYSTEM],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TE_DIM_CODE_CONSTRAINT_TYPE] c ON c.CODE_CONSTRAINT_TYPE_ID = datagc.GUID_KEY
WHERE   tablegc.TABLE_NAME = 'TE_DIM_CODE_CONSTRAINT_TYPE';
GO
GRANT SELECT
	ON [dbo].[VW_DIM_CODE_CONSTRAINT_TYPE_GC]
	TO [portalapp_role]
GO
