SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_AGENT_SKILLGROUP_LOGOUT]
AS
    SELECT  * FROM dbo.TB_FCT_AGENT_SKILLGROUP_LOGOUT;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_AGENT_SKILLGROUP_LOGOUT]
	TO [portalreporting_role]
GO
