SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[VW_SYS_MON_ETL_COMPONENT_DETAIL]
AS
    SELECT  [inst].[INSTANCE_URN],
            CONVERT(DATETIME, [stst].[EXECUTION_END_DATETIME]) AS [EXECUTION_END_DATETIME],
            [comp].[NAME] AS [COMPONENT_NAME],
            [comp].[COMPONENT_ID],
            [comp].[ENABLED] AS [COMPONENT_ENABLED],
            CASE WHEN [comp].[PIPELINE_TYPE] = 'S' THEN 'Reader'
                 WHEN [comp].[PIPELINE_TYPE] = 'T' THEN 'Transform'
                 ELSE 'Destination'
            END AS [PIPELINE_TYPE],
            ISNULL([secondaryRes].[RESOURCE_ID], [res].[RESOURCE_ID]) AS [RESOURCE_ID],
            ISNULL([secondaryRes].[NAME], [res].[NAME]) AS [CLUSTER_NAME],
            ISNULL([secondaryType].[NAME], [ct].[NAME]) AS [CLUSTER_TYPE],
            [inst].[ENABLED] AS [INSTANCE_ENABLED],
            [inst].[EXECUTION_UPDATE_INTERVAL] * 60 AS [EXECUTION_UPDATE_INTERVAL],
            CONVERT(DATETIME, [inst].[LAST_EXECUTION_WRITTEN]) AS [LAST_EXECUTION_WRITTEN],
            DATEDIFF_BIG(ss, [inst].[LAST_EXECUTION_WRITTEN], GETUTCDATE()) AS [SECONDS_SINCE_LAST_EXECUTION_HISTORY_WRITTEN],
            CONVERT(DATETIME, ISNULL([stst].[MAX_SOURCE_DATETIME], '1900-01-01')) AS [MAX_SOURCE_DATETIME],
            CONVERT(DATETIME, ISNULL([stst].[MAX_DESTINATION_DATETIME], '1900-01-01')) AS [MAX_DESTINATION_DATETIME],
            DATEDIFF_BIG(ss, [stst].[MAX_DESTINATION_DATETIME], [stst].[MAX_SOURCE_DATETIME]) AS [LAG_SECONDS],
            DATEDIFF_BIG(DAY, [stst].[MAX_DESTINATION_DATETIME], [stst].[MAX_SOURCE_DATETIME]) AS [LAG_DAYS]
    FROM    [dbo].[TB_ETL_COMPONENT_INSTANCE] [inst]
    INNER JOIN [dbo].[TB_ETL_COMPONENT] [comp] ON [comp].[COMPONENT_ID] = [inst].[COMPONENT_ID]
    LEFT OUTER JOIN [dbo].[TB_ETL_COMPONENT_INSTANCE_EXECUTION] [stst] ON [stst].[INSTANCE_URN] = [inst].[INSTANCE_URN]
    INNER JOIN [dbo].[TB_CLU_RESOURCE] [res] ON [res].[RESOURCE_ID] = [inst].[CLUSTER_ID]
    INNER JOIN [dbo].[TE_ADM_CLUSTER_RESOURCE_TYPE] [ct] ON [ct].[CLUSTER_RESOURCE_TYPE_ID] = [res].[RESOURCE_TYPE_ID]
    LEFT OUTER JOIN [dbo].[TB_CLU_RESOURCE] [secondaryRes] ON [secondaryRes].[RESOURCE_ID] = [stst].[SECONDARY_SOURCE_CLUSTER_ID]
    LEFT OUTER JOIN [dbo].[TE_ADM_CLUSTER_RESOURCE_TYPE] [secondaryType] ON [secondaryType].[CLUSTER_RESOURCE_TYPE_ID] = [secondaryRes].[RESOURCE_TYPE_ID];
GO
GRANT SELECT
	ON [dbo].[VW_SYS_MON_ETL_COMPONENT_DETAIL]
	TO [portalapp_role]
GO
