SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_IVR_VXML_ELEMENT]
AS
SELECT  *,
        1 AS [Row Count]
FROM    dbo.VW_PARTITIONED_FCT_IVR_VXML_ELEMENT;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_IVR_VXML_ELEMENT]
	TO [portalreporting_role]
GO
