SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_ADM_RESOURCE_TEMPLATE_GC]
WITH SCHEMABINDING
AS
SELECT  datagc.[GUID_KEY] AS RESOURCE_ID,
        t.[FOLDER_ID] AS [CONTAINER_ID],
        t.[RESOURCE_TYPE_ID],
        t.[CLUSTER_RESOURCE_ID],
        t.[NAME],
        t.[DESCRIPTION],
        t.[CREATED_BY_ID],
        t.[MODIFIED_BY_ID],
        t.[CREATION_DATE],
        t.[MODIFIED_DATE],
        t.[DELETED],
        t.[CHANGE_STAMP],
        t.[TEMPLATE_DATA],
        t.[CUSTOM_XML_DATA],
        datagc.[GENERATION_COUNT],
        datagc.[CREATE_GENERATION_COUNT],
        datagc.[LAST_OPERATION]
FROM    [dbo].[TS_ADM_DATA_GENERATION_COUNT] datagc
JOIN    [dbo].[TS_ADM_TABLE_GENERATION_COUNT] tablegc ON tablegc.TABLE_GENERATION_COUNT_URN = datagc.TABLE_GENERATION_COUNT_URN
LEFT JOIN [dbo].[TB_ADM_RESOURCE_TEMPLATE] t ON t.ID = datagc.GUID_KEY
WHERE   tablegc.TABLE_NAME = 'TB_ADM_RESOURCE_TEMPLATE';
GO
GRANT SELECT
	ON [dbo].[VW_ADM_RESOURCE_TEMPLATE_GC]
	TO [portalapp_role]
GO
