SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_EMAIL]
--WITH ENCRYPTION
AS
SELECT  *
FROM    dbo.VW_PARTITIONED_FCT_EMAIL;
GO
GRANT SELECT
	ON [dbo].[VW_FCT_EMAIL]
	TO [portalreporting_role]
GO
