SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[VW_DIM_GHE_CLUSTER_GHE_CLUSTER_GROUP_MEMBER]
WITH SCHEMABINDING
AS
    SELECT
        i.[MEMBER_URN],
        i.[MEMBER_BIZ_URN],
        CAST('9c60c5d4-400c-47e2-ad9a-bcda2244b79b' AS UNIQUEIDENTIFIER) AS [MEMBER_TYPE_ID],
        i.[PARENT_ITEM_BIZ_URN],
        i.[CHILD_ITEM_BIZ_URN],
        i.[EFFECTIVE_FROM],
        i.[EFFECTIVE_TO],
        i.[DELETED],
        i.[HIDDEN],
        i.[SYSTEM],
        i.[LATEST],
        i.[CHANGE_STAMP]
    FROM [dbo].[TB_DIM_GHE_CLUSTER_GHE_CLUSTER_GROUP_MEMBER] i;
GO
GRANT SELECT
	ON [dbo].[VW_DIM_GHE_CLUSTER_GHE_CLUSTER_GROUP_MEMBER]
	TO [portalapp_role]
GO
