SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].VW_PARTITIONED_FCT_CMS_CALL_RECORD
AS
SELECT  *
FROM    dbo.TB_FCT_CMS_CALL_RECORD;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_CMS_CALL_RECORD]
	TO [portalreporting_role]
GO
