SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_CUCM_CDR_CUBE]
AS
    SELECT     * FROM [dbo].[VW_FCT_CUCM_CDR];
GO
GRANT SELECT
	ON [dbo].[VW_FCT_CUCM_CDR_CUBE]
	TO [portalapp_role]
GO
