SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VW_ADM_OBJECT_LOCK_STATE
AS
SELECT  l.OBJECT_LOCK_ID,
        l.OBJECT_NAME,
        l.LOCKED_AT,
        ses.SESSION_COMPUTER,
        COALESCE(ses.SESSION_USER_NAME, 'Unknown') AS USER_NAME,
        l.SESSION_ID,
        l.NESTED_LOCK_COUNT
FROM    dbo.TB_ADM_OBJECT_LOCK l
JOIN    dbo.TB_ADM_SESSION ses ON ses.SESSION_ID = l.SESSION_ID;
GO
GRANT SELECT
	ON [dbo].[VW_ADM_OBJECT_LOCK_STATE]
	TO [portalapp_role]
GO
