SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_FCT_EVNT_HIST_CASE_MGMT_CUBE]
AS
SELECT * FROM [dbo].[VW_FCT_EVNT_HIST_CASE_MGMT];
GO
GRANT SELECT
	ON [dbo].[VW_FCT_EVNT_HIST_CASE_MGMT_CUBE]
	TO [portalapp_role]
GO
