SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_FCT_PROVISIONING_REQUEST_ARCHIVE]
AS
SELECT  *
FROM    dbo.TB_FCT_PROVISIONING_REQUEST_ARCHIVE;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_PROVISIONING_REQUEST_ARCHIVE]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_PROVISIONING_REQUEST_ARCHIVE]
	TO [portalreporting_role]
GO
