SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_PARTITIONED_SUM_IVR_APPLICATION_DAILY]
AS
SELECT  *
FROM    dbo.TB_SUM_IVR_APPLICATION_DAILY;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_SUM_IVR_APPLICATION_DAILY]
	TO [portalreporting_role]
GO
