SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].VW_PARTITIONED_FCT_REPEAT_INTERACTION_EVENT
AS
SELECT  *
FROM    dbo.TB_FCT_REPEAT_INTERACTION_EVENT;
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_REPEAT_INTERACTION_EVENT]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[VW_PARTITIONED_FCT_REPEAT_INTERACTION_EVENT]
	TO [portalreporting_role]
GO
