SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY] (
		[ID]                      [uniqueidentifier] NOT NULL,
		[JOB_ID]                  [uniqueidentifier] NOT NULL,
		[EXECUTION_DATE]          [datetime] NOT NULL,
		[BATCH_ID]                [uniqueidentifier] NULL,
		[msrepl_tran_version]     [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TB_SCH_PROVISIONING_JOB_HISTORY]
		PRIMARY KEY
		CLUSTERED
		([ID])
	ON [ADMGROUP]
) ON [ADMGROUP]
GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	ADD
	CONSTRAINT [DF_TB_SCH_PROVISIONING_JOB_HISTORY_ID]
	DEFAULT (newid()) FOR [ID]
GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	ADD
	CONSTRAINT [DF_TB_SCH_PROVISIONING_JOB_HISTORY_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_HISTORY_TB_SCH_PROVISIONING_JOB_JOB_ID]
	FOREIGN KEY ([JOB_ID]) REFERENCES [dbo].[TB_SCH_PROVISIONING_JOB] ([ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	CHECK CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_HISTORY_TB_SCH_PROVISIONING_JOB_JOB_ID]

GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_HISTORY_TB_ADM_PROVISIONING_BATCH_BATCH_ID]
	FOREIGN KEY ([BATCH_ID]) REFERENCES [dbo].[TB_ADM_PROVISIONING_BATCH] ([ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	CHECK CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_HISTORY_TB_ADM_PROVISIONING_BATCH_BATCH_ID]

GO
GRANT DELETE
	ON [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY]
	TO [portalapp_role]
GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB_HISTORY] SET (LOCK_ESCALATION = TABLE)
GO
