SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER] (
		[STRATEGY_SCRIPT_MEMBER_ID]     [uniqueidentifier] NOT NULL,
		[STRATEGY_URN]                  [int] NOT NULL,
		[ROUTING_SCRIPT_URN]            [int] NOT NULL,
		[IVR_SCRIPT_URN]                [int] NOT NULL,
		[SORT_ORDER]                    [int] NOT NULL,
		[msrepl_tran_version]           [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TB_SGY_STRATEGY_SCRIPT_MEMBER]
		PRIMARY KEY
		CLUSTERED
		([STRATEGY_SCRIPT_MEMBER_ID])
	ON [ADMGROUP]
) ON [ADMGROUP]
GO
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	ADD
	CONSTRAINT [DF_TB_SGY_STRATEGY_SCRIPT_MEMBER_STRATEGY_SCRIPT_MEMBER_ID]
	DEFAULT (newid()) FOR [STRATEGY_SCRIPT_MEMBER_ID]
GO
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	ADD
	CONSTRAINT [DF_TB_SGY_STRATEGY_SCRIPT_MEMBER_ROUTING_SCRIPT_URN]
	DEFAULT ((-1)) FOR [ROUTING_SCRIPT_URN]
GO
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	ADD
	CONSTRAINT [DF_TB_SGY_STRATEGY_SCRIPT_MEMBER_IVR_SCRIPT_URN]
	DEFAULT ((-1)) FOR [IVR_SCRIPT_URN]
GO
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	ADD
	CONSTRAINT [DF_TB_SGY_STRATEGY_SCRIPT_MEMBER_SORT_ORDER]
	DEFAULT ((1)) FOR [SORT_ORDER]
GO
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	ADD
	CONSTRAINT [DF_TB_SGY_STRATEGY_SCRIPT_MEMBER_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	WITH NOCHECK
	ADD CONSTRAINT [FK_SGY_STRATEGY_SCRIPT_MEMBER_TB_DIM_ROUTING_SCRIPT]
	FOREIGN KEY ([ROUTING_SCRIPT_URN]) REFERENCES [dbo].[TB_DIM_ROUTING_SCRIPT] ([ITEM_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	CHECK CONSTRAINT [FK_SGY_STRATEGY_SCRIPT_MEMBER_TB_DIM_ROUTING_SCRIPT]

GO
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	WITH NOCHECK
	ADD CONSTRAINT [FK_SGY_STRATEGY_SCRIPT_MEMBER_DIM_IVR_SCRIPT]
	FOREIGN KEY ([IVR_SCRIPT_URN]) REFERENCES [dbo].[TB_DIM_IVR_SCRIPT] ([ITEM_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	CHECK CONSTRAINT [FK_SGY_STRATEGY_SCRIPT_MEMBER_DIM_IVR_SCRIPT]

GO
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_SGY_STRATEGY_SCRIPT_MEMBER_TB_DIM_STRATEGY]
	FOREIGN KEY ([STRATEGY_URN]) REFERENCES [dbo].[TB_DIM_STRATEGY] ([ITEM_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	CHECK CONSTRAINT [FK_TB_SGY_STRATEGY_SCRIPT_MEMBER_TB_DIM_STRATEGY]

GO
CREATE NONCLUSTERED INDEX [IX_TB_SGY_STRATEGY_SCRIPT_MEMBER_IVR_SCRIPT_URN]
	ON [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER] ([IVR_SCRIPT_URN])
	ON [ADMGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_SGY_STRATEGY_SCRIPT_MEMBER_ROUTING_SCRIPT_URN]
	ON [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER] ([ROUTING_SCRIPT_URN])
	ON [ADMGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_SGY_STRATEGY_SCRIPT_MEMBER_STRATEGY_URN]
	ON [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER] ([STRATEGY_URN])
	ON [ADMGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_SGY_STRATEGY_SCRIPT_MEMBER', 'COLUMN', N'STRATEGY_SCRIPT_MEMBER_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The strategy to which this script relates to.', 'SCHEMA', N'dbo', 'TABLE', N'TB_SGY_STRATEGY_SCRIPT_MEMBER', 'COLUMN', N'STRATEGY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The routing script to which the membership relates. May be -1 if it is not used in this membership.', 'SCHEMA', N'dbo', 'TABLE', N'TB_SGY_STRATEGY_SCRIPT_MEMBER', 'COLUMN', N'ROUTING_SCRIPT_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The IVR script to which the membership relates. May be -1 if it is not used in this membership.', 'SCHEMA', N'dbo', 'TABLE', N'TB_SGY_STRATEGY_SCRIPT_MEMBER', 'COLUMN', N'IVR_SCRIPT_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the order in which the members are displayed to the user for this strategy template.', 'SCHEMA', N'dbo', 'TABLE', N'TB_SGY_STRATEGY_SCRIPT_MEMBER', 'COLUMN', N'SORT_ORDER'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_SGY_STRATEGY_SCRIPT_MEMBER', 'COLUMN', N'msrepl_tran_version'
GO
GRANT DELETE
	ON [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER]
	TO [portalapp_role]
GO
ALTER TABLE [dbo].[TB_SGY_STRATEGY_SCRIPT_MEMBER] SET (LOCK_ESCALATION = TABLE)
GO
