SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TS_IMP_OLAP_DIMENSION_STATE] (
		[OLAP_DIMENSION_STATE_URN]        [int] IDENTITY(1, 4) NOT FOR REPLICATION NOT NULL,
		[OLAP_OBJECT_CLUSTER_MAP_URN]     [int] NOT NULL,
		[TABLE_GENERATION_COUNT_URN]      [int] NOT NULL,
		[LAST_GENERATION_COUNT]           [bigint] NOT NULL,
		CONSTRAINT [UN_TS_IMP_OLAP_DIMENSION_STATE_OLAP_OBJECT_CLUSTER_MAP_URN_TABLE_GENERATION_COUNT_URN]
		UNIQUE
		NONCLUSTERED
		([OLAP_OBJECT_CLUSTER_MAP_URN], [TABLE_GENERATION_COUNT_URN])
		ON [STGGROUP],
		CONSTRAINT [PK_TS_IMP_OLAP_DIMENSION_STATE]
		PRIMARY KEY
		CLUSTERED
		([OLAP_DIMENSION_STATE_URN])
	ON [STGGROUP]
) ON [STGGROUP]
GO
ALTER TABLE [dbo].[TS_IMP_OLAP_DIMENSION_STATE]
	ADD
	CONSTRAINT [DF_TS_IMP_OLAP_DIMENSION_STATE_LAST_GENERATION_COUNT]
	DEFAULT ((-1)) FOR [LAST_GENERATION_COUNT]
GO
ALTER TABLE [dbo].[TS_IMP_OLAP_DIMENSION_STATE]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TS_IMP_OLAP_DIMENSION_STATE_TB_ADM_OLAP_OBJECT_CLUSTER_MAP]
	FOREIGN KEY ([OLAP_OBJECT_CLUSTER_MAP_URN]) REFERENCES [dbo].[TB_ADM_OLAP_OBJECT_CLUSTER_MAP] ([OLAP_OBJECT_CLUSTER_MAP_URN])
	ON DELETE CASCADE
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TS_IMP_OLAP_DIMENSION_STATE]
	CHECK CONSTRAINT [FK_TS_IMP_OLAP_DIMENSION_STATE_TB_ADM_OLAP_OBJECT_CLUSTER_MAP]

GO
ALTER TABLE [dbo].[TS_IMP_OLAP_DIMENSION_STATE]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TS_IMP_OLAP_DIMENSION_STATE_TS_ADM_TABLE_GENERATION_COUNT]
	FOREIGN KEY ([TABLE_GENERATION_COUNT_URN]) REFERENCES [dbo].[TS_ADM_TABLE_GENERATION_COUNT] ([TABLE_GENERATION_COUNT_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TS_IMP_OLAP_DIMENSION_STATE]
	CHECK CONSTRAINT [FK_TS_IMP_OLAP_DIMENSION_STATE_TS_ADM_TABLE_GENERATION_COUNT]

GO
CREATE NONCLUSTERED INDEX [IX_TS_IMP_OLAP_DIMENSION_STATE_TABLE_GENERATION_COUNT_URN]
	ON [dbo].[TS_IMP_OLAP_DIMENSION_STATE] ([TABLE_GENERATION_COUNT_URN])
	ON [STGGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a staging table that is used by the olap processor when processing dimensions. It stores the generation count of each olap dimension table following the last process', 'SCHEMA', N'dbo', 'TABLE', N'TS_IMP_OLAP_DIMENSION_STATE', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'This field is the primary key for this table.', 'SCHEMA', N'dbo', 'TABLE', N'TS_IMP_OLAP_DIMENSION_STATE', 'COLUMN', N'OLAP_DIMENSION_STATE_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This field indicates the Dimension OLAP Object on an OLAP cluster resource that requires processing. This is the foreign key from TB_ADM_OLAP_OBJECT.', 'SCHEMA', N'dbo', 'TABLE', N'TS_IMP_OLAP_DIMENSION_STATE', 'COLUMN', N'OLAP_OBJECT_CLUSTER_MAP_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This field is the table generation count record to which the LAST_GENERATION_COUNT value is from.', 'SCHEMA', N'dbo', 'TABLE', N'TS_IMP_OLAP_DIMENSION_STATE', 'COLUMN', N'TABLE_GENERATION_COUNT_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This field is the table generation count the last time the dimension was processed.', 'SCHEMA', N'dbo', 'TABLE', N'TS_IMP_OLAP_DIMENSION_STATE', 'COLUMN', N'LAST_GENERATION_COUNT'
GO
GRANT INSERT
	ON [dbo].[TS_IMP_OLAP_DIMENSION_STATE]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TS_IMP_OLAP_DIMENSION_STATE]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TS_IMP_OLAP_DIMENSION_STATE]
	TO [portalapp_role]
GO
ALTER TABLE [dbo].[TS_IMP_OLAP_DIMENSION_STATE] SET (LOCK_ESCALATION = TABLE)
GO
