SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER] (
		[MEMBER_URN]              [int] IDENTITY(1, 4) NOT FOR REPLICATION NOT NULL,
		[PARENT_ITEM_URN]         [int] NOT NULL,
		[CHILD_ITEM_URN]          [int] NOT NULL,
		[msrepl_tran_version]     [uniqueidentifier] NOT NULL,
		CONSTRAINT [UN_TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
		UNIQUE
		NONCLUSTERED
		([PARENT_ITEM_URN], [CHILD_ITEM_URN])
		ON [DIMINDEXGROUP],
		CONSTRAINT [PK_TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
		PRIMARY KEY
		CLUSTERED
		([MEMBER_URN])
	ON [DIMGROUP]
) ON [DIMGROUP]
GO
ALTER TABLE [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	ADD
	CONSTRAINT [DF_TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER_TB_DIM_CHANNEL_ADDRESS]
	FOREIGN KEY ([CHILD_ITEM_URN]) REFERENCES [dbo].[TB_DIM_CHANNEL_ADDRESS] ([ITEM_URN])
	ON DELETE CASCADE
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	CHECK CONSTRAINT [FK_TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER_TB_DIM_CHANNEL_ADDRESS]

GO
ALTER TABLE [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER_TB_DIM_CONTACT]
	FOREIGN KEY ([PARENT_ITEM_URN]) REFERENCES [dbo].[TB_DIM_CONTACT] ([ITEM_URN])
	ON DELETE CASCADE
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	CHECK CONSTRAINT [FK_TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER_TB_DIM_CONTACT]

GO
CREATE NONCLUSTERED INDEX [IX_TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER_CHILD_ITEM_URN]
	ON [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER] ([CHILD_ITEM_URN])
	ON [DIMINDEXGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This table defines the different channels any contact may reach the enterprise or reached by the enterprise.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary key identifier for the record.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER', 'COLUMN', N'MEMBER_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a foreign key to CONTACT_URN in TB_DIM_CONTACT indicating the customer contact.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER', 'COLUMN', N'PARENT_ITEM_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a foreign key to CHANNEL_ADDRESS_URN in TB_DIM_CHANNEL_ADDRESS indicating the channel address for the contact.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER', 'COLUMN', N'CHILD_ITEM_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER', 'COLUMN', N'msrepl_tran_version'
GO
GRANT DELETE
	ON [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	TO [portal_default_mediator_role]
GO
GRANT SELECT
	ON [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER]
	TO [portal_default_mediator_role]
GO
ALTER TABLE [dbo].[TB_DIM_CHANNEL_ADDRESS_CONTACT_MEMBER] SET (LOCK_ESCALATION = TABLE)
GO
