SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT] (
		[COMPONENT_ID]             [uniqueidentifier] NOT NULL ROWGUIDCOL,
		[RESOURCE_INSTANCE_ID]     [uniqueidentifier] NOT NULL,
		[COMPONENT_TYPE_ID]        [uniqueidentifier] NOT NULL,
		[SERVER_ID]                [uniqueidentifier] NOT NULL,
		[ENABLED]                  [bit] NOT NULL,
		[SYSTEM]                   [bit] NOT NULL,
		[XML_DATA]                 [xml](DOCUMENT [dbo].[ColumnCollection]) NULL,
		[msrepl_tran_version]      [uniqueidentifier] NOT NULL,
		CONSTRAINT [UN_TB_CLU_RESOURCE_INSTANCE_COMPONENT_RESOURCE_INSTANCE_ID_COMPONENT_TYPE_ID]
		UNIQUE
		NONCLUSTERED
		([RESOURCE_INSTANCE_ID], [COMPONENT_TYPE_ID])
		ON [ADMINDEXGROUP],
		CONSTRAINT [PK_TB_CLU_RESOURCE_INSTANCE_COMPONENT]
		PRIMARY KEY
		CLUSTERED
		([COMPONENT_ID])
	ON [ADMGROUP]
) ON [ADMGROUP] TEXTIMAGE_ON [ADMGROUP]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	ADD
	CONSTRAINT [DF_TB_CLU_RESOURCE_INSTANCE_COMPONENT_COMPONENT_ID]
	DEFAULT (newid()) FOR [COMPONENT_ID]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	ADD
	CONSTRAINT [DF_TB_CLU_RESOURCE_INSTANCE_COMPONENT_ENABLED]
	DEFAULT ((1)) FOR [ENABLED]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	ADD
	CONSTRAINT [DF_TB_CLU_RESOURCE_INSTANCE_COMPONENT_SYSTEM]
	DEFAULT ((0)) FOR [SYSTEM]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	ADD
	CONSTRAINT [DF_TB_CLU_RESOURCE_INSTANCE_COMPONENT_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_CLU_RESOURCE_INSTANCE_COMPONENT_TB_CLU_RESOURCE_INSTANCE]
	FOREIGN KEY ([RESOURCE_INSTANCE_ID]) REFERENCES [dbo].[TB_CLU_RESOURCE_INSTANCE] ([RESOURCE_INSTANCE_ID])
	ON DELETE CASCADE
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	CHECK CONSTRAINT [FK_TB_CLU_RESOURCE_INSTANCE_COMPONENT_TB_CLU_RESOURCE_INSTANCE]

GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_CLU_RESOURCE_INSTANCE_COMPONENT_TB_CLU_SERVER]
	FOREIGN KEY ([SERVER_ID]) REFERENCES [dbo].[TB_CLU_SERVER] ([SERVER_ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	CHECK CONSTRAINT [FK_TB_CLU_RESOURCE_INSTANCE_COMPONENT_TB_CLU_SERVER]

GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_CLU_RESOURCE_INSTANCE_COMPONENT_COMPONENT_TYPE_ID]
	FOREIGN KEY ([COMPONENT_TYPE_ID]) REFERENCES [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE] ([COMPONENT_TYPE_ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	CHECK CONSTRAINT [FK_TB_CLU_RESOURCE_INSTANCE_COMPONENT_COMPONENT_TYPE_ID]

GO
CREATE NONCLUSTERED INDEX [IX_TB_CLU_RESOURCE_INSTANCE_COMPONENT_COMPONENT_TYPE_ID]
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT] ([COMPONENT_TYPE_ID])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_CLU_RESOURCE_INSTANCE_COMPONENT_SERVER_ID]
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT] ([SERVER_ID])
	ON [ADMINDEXGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This table stores the endpoints associated with a specific physical resource.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_INSTANCE_COMPONENT', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary key identifier for the record.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_INSTANCE_COMPONENT', 'COLUMN', N'COMPONENT_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the id of the physical resource. This is a foreign key to TB_CLU_RESOURCE_INSTANCE.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_INSTANCE_COMPONENT', 'COLUMN', N'RESOURCE_INSTANCE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key from TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE. Identifies this component type.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_INSTANCE_COMPONENT', 'COLUMN', N'COMPONENT_TYPE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the id of the physical server. This is a foreign key to TB_CLU_SERVER.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_INSTANCE_COMPONENT', 'COLUMN', N'SERVER_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a flag indicating whether the endpoint is enabled or not. Value of 1 indicates enabled.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_INSTANCE_COMPONENT', 'COLUMN', N'ENABLED'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a flag indicating whether the endpoint is owned by system or not. Value of 1 indicates system owned endpoint.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_INSTANCE_COMPONENT', 'COLUMN', N'SYSTEM'
GO
EXEC sp_addextendedproperty N'MS_Description', N'XML data block for this item.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_INSTANCE_COMPONENT', 'COLUMN', N'XML_DATA'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_INSTANCE_COMPONENT', 'COLUMN', N'msrepl_tran_version'
GO
GRANT DELETE
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	TO [portalapp_role]
GO
GRANT DELETE
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	TO [portal_database_configuration_role]
GO
GRANT INSERT
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	TO [portal_database_configuration_role]
GO
GRANT SELECT
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	TO [portal_database_configuration_role]
GO
GRANT UPDATE
	ON [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT]
	TO [portal_database_configuration_role]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_INSTANCE_COMPONENT] SET (LOCK_ESCALATION = TABLE)
GO
