SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TB_REP_REFERENCE_DATA] (
		[REFERENCE_ID]            [uniqueidentifier] NOT NULL ROWGUIDCOL,
		[FOLDER_ID]               [uniqueidentifier] NOT NULL,
		[CATEGORY]                [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
		[NAME]                    [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
		[INTERNAL_NAME]           [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
		[SEQUENCE]                [int] NOT NULL,
		[DESCRIPTION]             [nvarchar](500) COLLATE Latin1_General_CI_AS NOT NULL,
		[STRING_VAL]              [nvarchar](500) COLLATE Latin1_General_CI_AS NULL,
		[BIGINT_VAL]              [bigint] NULL,
		[INT_VAL]                 [int] NULL,
		[FLOAT_VAL]               [float] NULL,
		[DATETIME_VAL]            [datetime] NULL,
		[ENABLED]                 [bit] NOT NULL,
		[HIDDEN]                  [bit] NOT NULL,
		[SYSTEM]                  [bit] NOT NULL,
		[msrepl_tran_version]     [uniqueidentifier] NOT NULL,
		CONSTRAINT [UN_TB_REP_REFERENCE_DATA]
		UNIQUE
		NONCLUSTERED
		([FOLDER_ID], [CATEGORY], [INTERNAL_NAME], [SEQUENCE])
		ON [PRIMARY],
		CONSTRAINT [PK_TB_REP_REFERENCE_DATA]
		PRIMARY KEY
		CLUSTERED
		([REFERENCE_ID])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	ADD
	CONSTRAINT [DF_TB_REP_REFERENCE_DATA_REFERENCE_ID]
	DEFAULT (newid()) FOR [REFERENCE_ID]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	ADD
	CONSTRAINT [DF_TB_REP_REFERENCE_DATA_SEQUENCE]
	DEFAULT ((0)) FOR [SEQUENCE]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	ADD
	CONSTRAINT [DF_TB_REP_REFERENCE_DATA_CATEGORY]
	DEFAULT (N'') FOR [CATEGORY]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	ADD
	CONSTRAINT [DF_TB_REP_REFERENCE_DATA_DESCRIPTION]
	DEFAULT (N'') FOR [DESCRIPTION]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	ADD
	CONSTRAINT [DF_TB_REP_REFERENCE_DATA_ENABLED]
	DEFAULT ((1)) FOR [ENABLED]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	ADD
	CONSTRAINT [DF_TB_REP_REFERENCE_DATA_HIDDEN]
	DEFAULT ((0)) FOR [HIDDEN]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	ADD
	CONSTRAINT [DF_TB_REP_REFERENCE_DATA_SYSTEM]
	DEFAULT ((0)) FOR [SYSTEM]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	ADD
	CONSTRAINT [DF_TB_REP_REFERENCE_DATA_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_REP_REFERENCE_DATA_TB_SEC_FOLDER]
	FOREIGN KEY ([FOLDER_ID]) REFERENCES [dbo].[TB_SEC_FOLDER] ([FOLDER_ID])
	ON DELETE CASCADE
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA]
	CHECK CONSTRAINT [FK_TB_REP_REFERENCE_DATA_TB_SEC_FOLDER]

GO
EXEC sp_addextendedproperty N'MS_Description', N'This table is not used. This is deprecated and will be removed from future versions. Hence it is not documented.', 'SCHEMA', N'dbo', 'TABLE', N'TB_REP_REFERENCE_DATA', NULL, NULL
GO
GRANT DELETE
	ON [dbo].[TB_REP_REFERENCE_DATA]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_REP_REFERENCE_DATA]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_REP_REFERENCE_DATA]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_REP_REFERENCE_DATA]
	TO [portalapp_role]
GO
ALTER TABLE [dbo].[TB_REP_REFERENCE_DATA] SET (LOCK_ESCALATION = TABLE)
GO
