SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TB_DIM_RS_STATUS_CODE] (
		[STATUS_CODE_URN]         [int] IDENTITY(1, 4) NOT FOR REPLICATION NOT NULL,
		[NAME]                    [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
		[INTERNAL_NAME]           [nvarchar](50) COLLATE Latin1_General_CI_AS NULL,
		[msrepl_tran_version]     [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TB_DIM_RS_STATUS_CODE]
		PRIMARY KEY
		CLUSTERED
		([STATUS_CODE_URN])
	ON [DIMGROUP]
) ON [DIMGROUP]
GO
ALTER TABLE [dbo].[TB_DIM_RS_STATUS_CODE]
	ADD
	CONSTRAINT [DF_TB_DIM_RS_STATUS_CODE_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This table stores all the status codes generated by the SQL server reporting services for execution of any report. The data in this table is populated during the import of report execution logs.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_RS_STATUS_CODE', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary key identifier for the record.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_RS_STATUS_CODE', 'COLUMN', N'STATUS_CODE_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a display name for the status code.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_RS_STATUS_CODE', 'COLUMN', N'NAME'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the systems internal name for the status code.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_RS_STATUS_CODE', 'COLUMN', N'INTERNAL_NAME'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_RS_STATUS_CODE', 'COLUMN', N'msrepl_tran_version'
GO
ALTER TABLE [dbo].[TB_DIM_RS_STATUS_CODE] SET (LOCK_ESCALATION = TABLE)
GO
