SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TB_SCH_PROVISIONING_JOB] (
		[ID]                                    [uniqueidentifier] NOT NULL,
		[TARGET_RESOURCE_SET_ID]                [uniqueidentifier] NOT NULL,
		[RESOURCE_PROVISIONING_TEMPLATE_ID]     [uniqueidentifier] NOT NULL,
		[LAST_EXECUTION_DATE]                   [datetime] NULL,
		[msrepl_tran_version]                   [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TB_SCH_PROVISIONING_JOB]
		PRIMARY KEY
		CLUSTERED
		([ID])
	ON [ADMGROUP]
) ON [ADMGROUP]
GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB]
	ADD
	CONSTRAINT [DF_TB_SCH_PROVISIONING_JOB_ID]
	DEFAULT (newid()) FOR [ID]
GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB]
	ADD
	CONSTRAINT [DF_TB_SCH_PROVISIONING_JOB_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_TB_ADM_RESOURCE_TARGET_RESOURCE_SET_ID]
	FOREIGN KEY ([TARGET_RESOURCE_SET_ID]) REFERENCES [dbo].[TB_ADM_RESOURCE_SET] ([ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB]
	CHECK CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_TB_ADM_RESOURCE_TARGET_RESOURCE_SET_ID]

GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_TB_ADM_RESOURCE_PROVISIONING_TEMPLATE_RESOURCE_PROVISIONING_TEMPLATE_ID]
	FOREIGN KEY ([RESOURCE_PROVISIONING_TEMPLATE_ID]) REFERENCES [dbo].[TB_ADM_RESOURCE_PROVISIONING_TEMPLATE] ([ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB]
	CHECK CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_TB_ADM_RESOURCE_PROVISIONING_TEMPLATE_RESOURCE_PROVISIONING_TEMPLATE_ID]

GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_TB_SCH_TASK_ID]
	FOREIGN KEY ([ID]) REFERENCES [dbo].[TB_SCH_TASK] ([TASK_ID])
	ON DELETE CASCADE
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB]
	CHECK CONSTRAINT [FK_TB_SCH_PROVISIONING_JOB_TB_SCH_TASK_ID]

GO
GRANT DELETE
	ON [dbo].[TB_SCH_PROVISIONING_JOB]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_SCH_PROVISIONING_JOB]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_SCH_PROVISIONING_JOB]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_SCH_PROVISIONING_JOB]
	TO [portalapp_role]
GO
ALTER TABLE [dbo].[TB_SCH_PROVISIONING_JOB] SET (LOCK_ESCALATION = TABLE)
GO
