SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT] (
		[PROVISIONING_GENERATION_COUNT_ID]     [uniqueidentifier] NOT NULL ROWGUIDCOL,
		[ITEM_TYPE_ID]                         [uniqueidentifier] NULL,
		[MEMBER_TYPE_ID]                       [uniqueidentifier] NULL,
		[CLUSTER_RESOURCE_ID]                  [uniqueidentifier] NOT NULL,
		[GENERATION_COUNT]                     [bigint] NOT NULL,
		[CREATION_DATE]                        [datetime] NOT NULL,
		[MODIFIED_DATE]                        [datetime] NOT NULL,
		CONSTRAINT [UN_TS_ADM_PROVISIONING_GENERATION_COUNT]
		UNIQUE
		NONCLUSTERED
		([ITEM_TYPE_ID], [MEMBER_TYPE_ID], [CLUSTER_RESOURCE_ID])
		ON [DIMINDEXGROUP],
		CONSTRAINT [PK_TS_ADM_PROVISIONING_GENERATION_COUNT]
		PRIMARY KEY
		CLUSTERED
		([PROVISIONING_GENERATION_COUNT_ID])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	ADD
	CONSTRAINT [DF_TS_ADM_PROVISIONING_GENERATION_COUNT_PROVISIONING_GENERATION_COUNT_ID]
	DEFAULT (newid()) FOR [PROVISIONING_GENERATION_COUNT_ID]
GO
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	ADD
	CONSTRAINT [DF_TS_ADM_PROVISIONING_GENERATION_COUNT_GENERATION_COUNT]
	DEFAULT ((0)) FOR [GENERATION_COUNT]
GO
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	ADD
	CONSTRAINT [DF_TS_ADM_PROVISIONING_GENERATION_COUNT_CREATION_DATE]
	DEFAULT (getutcdate()) FOR [CREATION_DATE]
GO
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	ADD
	CONSTRAINT [DF_TS_ADM_PROVISIONING_GENERATION_COUNT_MODIFIED_DATE]
	DEFAULT (getutcdate()) FOR [MODIFIED_DATE]
GO
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TS_ADM_PROVISIONING_GENERATION_COUNT_TE_DIM_ITEM_TYPE]
	FOREIGN KEY ([ITEM_TYPE_ID]) REFERENCES [dbo].[TE_DIM_ITEM_TYPE] ([ITEM_TYPE_ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	CHECK CONSTRAINT [FK_TS_ADM_PROVISIONING_GENERATION_COUNT_TE_DIM_ITEM_TYPE]

GO
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TS_ADM_PROVISIONING_GENERATION_COUNT_TE_DIM_MEMBER_TYPE]
	FOREIGN KEY ([MEMBER_TYPE_ID]) REFERENCES [dbo].[TE_DIM_MEMBER_TYPE] ([MEMBER_TYPE_ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	CHECK CONSTRAINT [FK_TS_ADM_PROVISIONING_GENERATION_COUNT_TE_DIM_MEMBER_TYPE]

GO
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TS_ADM_PROVISIONING_GENERATION_COUNT_TB_CLU_RESOURCE]
	FOREIGN KEY ([CLUSTER_RESOURCE_ID]) REFERENCES [dbo].[TB_CLU_RESOURCE] ([RESOURCE_ID])
	ON DELETE CASCADE
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	CHECK CONSTRAINT [FK_TS_ADM_PROVISIONING_GENERATION_COUNT_TB_CLU_RESOURCE]

GO
CREATE NONCLUSTERED INDEX [IX_TS_ADM_PROVISIONING_GENERATION_COUNT_MEMBER_TYPE_ID]
	ON [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT] ([MEMBER_TYPE_ID])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_TS_ADM_PROVISIONING_GENERATION_COUNT_CLUSTER_RESOURCE_ID]
	ON [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT] ([CLUSTER_RESOURCE_ID])
	ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This table is used to store the generation count of member/item types when an update required provisioning.', 'SCHEMA', N'dbo', 'TABLE', N'TS_ADM_PROVISIONING_GENERATION_COUNT', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'The Primary key for this table.', 'SCHEMA', N'dbo', 'TABLE', N'TS_ADM_PROVISIONING_GENERATION_COUNT', 'COLUMN', N'PROVISIONING_GENERATION_COUNT_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The item type that the generation count corresponds to.', 'SCHEMA', N'dbo', 'TABLE', N'TS_ADM_PROVISIONING_GENERATION_COUNT', 'COLUMN', N'ITEM_TYPE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The member type that the generation count corresponds to.', 'SCHEMA', N'dbo', 'TABLE', N'TS_ADM_PROVISIONING_GENERATION_COUNT', 'COLUMN', N'MEMBER_TYPE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This cluster resource id of the remote equipment for which the provisioning change is for', 'SCHEMA', N'dbo', 'TABLE', N'TS_ADM_PROVISIONING_GENERATION_COUNT', 'COLUMN', N'CLUSTER_RESOURCE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The provisioning changed induced incrementing change stamp for the member/item type and cluster resource id', 'SCHEMA', N'dbo', 'TABLE', N'TS_ADM_PROVISIONING_GENERATION_COUNT', 'COLUMN', N'GENERATION_COUNT'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a UTC date time stamp indicating when the record was created.', 'SCHEMA', N'dbo', 'TABLE', N'TS_ADM_PROVISIONING_GENERATION_COUNT', 'COLUMN', N'CREATION_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a UTC date time stamp indicating when the record was last modified.', 'SCHEMA', N'dbo', 'TABLE', N'TS_ADM_PROVISIONING_GENERATION_COUNT', 'COLUMN', N'MODIFIED_DATE'
GO
GRANT DELETE
	ON [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT]
	TO [portalapp_role]
GO
ALTER TABLE [dbo].[TS_ADM_PROVISIONING_GENERATION_COUNT] SET (LOCK_ESCALATION = TABLE)
GO
