SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TB_DIM_CODE_HIERARCHY] (
		[CODE_HIERARCHY_URN]      [int] IDENTITY(1, 4) NOT FOR REPLICATION NOT NULL,
		[PARENT_CODE_URN]         [int] NOT NULL,
		[CHILD_CODE_URN]          [int] NOT NULL,
		[msrepl_tran_version]     [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TB_DIM_CODE_HIERARCHY]
		PRIMARY KEY
		CLUSTERED
		([CODE_HIERARCHY_URN])
	ON [DIMGROUP]
) ON [DIMGROUP]
GO
ALTER TABLE [dbo].[TB_DIM_CODE_HIERARCHY]
	ADD
	CONSTRAINT [DF_TB_DIM_CODE_HIERARCHY_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_DIM_CODE_HIERARCHY]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_DIM_CODE_HIERARCHY_TB_DIM_CODE_PARENT]
	FOREIGN KEY ([PARENT_CODE_URN]) REFERENCES [dbo].[TB_DIM_CODE] ([ITEM_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_DIM_CODE_HIERARCHY]
	CHECK CONSTRAINT [FK_TB_DIM_CODE_HIERARCHY_TB_DIM_CODE_PARENT]

GO
ALTER TABLE [dbo].[TB_DIM_CODE_HIERARCHY]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_DIM_CODE_HIERARCHY_TB_DIM_CODE_CHILD]
	FOREIGN KEY ([CHILD_CODE_URN]) REFERENCES [dbo].[TB_DIM_CODE] ([ITEM_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_DIM_CODE_HIERARCHY]
	CHECK CONSTRAINT [FK_TB_DIM_CODE_HIERARCHY_TB_DIM_CODE_CHILD]

GO
CREATE NONCLUSTERED INDEX [IX_TB_DIM_CODE_HIERARCHY_CHILD_CODE_URN]
	ON [dbo].[TB_DIM_CODE_HIERARCHY] ([CHILD_CODE_URN])
	ON [DIMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_DIM_CODE_HIERARCHY_PARENT_CODE_URN]
	ON [dbo].[TB_DIM_CODE_HIERARCHY] ([PARENT_CODE_URN])
	ON [DIMINDEXGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This table stores code hierarchies.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CODE_HIERARCHY', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary key identifier for the record. This is an auto generated number.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CODE_HIERARCHY', 'COLUMN', N'CODE_HIERARCHY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the URN from TB_DIM_CODE of the parent code', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CODE_HIERARCHY', 'COLUMN', N'PARENT_CODE_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the URN from TB_DIM_CODE of the child code', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CODE_HIERARCHY', 'COLUMN', N'CHILD_CODE_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_DIM_CODE_HIERARCHY', 'COLUMN', N'msrepl_tran_version'
GO
GRANT DELETE
	ON [dbo].[TB_DIM_CODE_HIERARCHY]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_DIM_CODE_HIERARCHY]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_DIM_CODE_HIERARCHY]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_DIM_CODE_HIERARCHY]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_DIM_CODE_HIERARCHY]
	TO [portalrs_role]
GO
ALTER TABLE [dbo].[TB_DIM_CODE_HIERARCHY] SET (LOCK_ESCALATION = TABLE)
GO
