SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS] (
		[INSTANCE_STATUS_URN]             [int] IDENTITY(1, 4) NOT FOR REPLICATION NOT NULL,
		[INSTANCE_URN]                    [int] NOT NULL,
		[SECONDARY_SOURCE_CLUSTER_ID]     [uniqueidentifier] NULL,
		[LAST_EXECUTED_DATETIME]          [datetime2](7) NOT NULL,
		[MAX_SOURCE_DATETIME]             [datetime] NULL,
		[MAX_DESTINATION_DATETIME]        [datetime] NULL,
		[msrepl_tran_version]             [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TB_ETL_COMPONENT_INSTANCE_STATUS]
		PRIMARY KEY
		CLUSTERED
		([INSTANCE_STATUS_URN])
	ON [ADMGROUP]
) ON [ADMGROUP]
GO
ALTER TABLE [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	ADD
	CONSTRAINT [DF_TB_ETL_COMPONENT_INSTANCE_STATUS_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ETL_COMPONENT_INSTANCE_STATUS_TB_ETL_COMPONENT_INSTANCE_INSTANCE_URN]
	FOREIGN KEY ([INSTANCE_URN]) REFERENCES [dbo].[TB_ETL_COMPONENT_INSTANCE] ([INSTANCE_URN])
	ON DELETE CASCADE
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	CHECK CONSTRAINT [FK_TB_ETL_COMPONENT_INSTANCE_STATUS_TB_ETL_COMPONENT_INSTANCE_INSTANCE_URN]

GO
ALTER TABLE [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ETL_COMPONENT_INSTANCE_STATUS_TB_CLU_RESOURCE_SECONDARY_SOURCE_CLUSTER_ID]
	FOREIGN KEY ([SECONDARY_SOURCE_CLUSTER_ID]) REFERENCES [dbo].[TB_CLU_RESOURCE] ([RESOURCE_ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	CHECK CONSTRAINT [FK_TB_ETL_COMPONENT_INSTANCE_STATUS_TB_CLU_RESOURCE_SECONDARY_SOURCE_CLUSTER_ID]

GO
CREATE NONCLUSTERED INDEX [IX_TB_ETL_COMPONENT_INSTANCE_STATUS_INSTANCE_URN]
	ON [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS] ([INSTANCE_URN])
	INCLUDE ([MAX_SOURCE_DATETIME], [MAX_DESTINATION_DATETIME], [SECONDARY_SOURCE_CLUSTER_ID])
	ON [ADMGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This table contains information allowing for ETL monitoring', 'SCHEMA', N'dbo', 'TABLE', N'TB_ETL_COMPONENT_INSTANCE_STATUS', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary key identifier for the record.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ETL_COMPONENT_INSTANCE_STATUS', 'COLUMN', N'INSTANCE_STATUS_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the URN as in TB_ETL_COMPONENT_INSTANCE indicating the ETL component instance for which this current instance status applies to', 'SCHEMA', N'dbo', 'TABLE', N'TB_ETL_COMPONENT_INSTANCE_STATUS', 'COLUMN', N'INSTANCE_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is identifier of the logical resource as in TB_CLU_RESOURCE that corresponds to the source for which the component instance originally read from.  If NULL, refer to the CLUSTER_ID on TB_ETL_COMPONENT_INSTANCE', 'SCHEMA', N'dbo', 'TABLE', N'TB_ETL_COMPONENT_INSTANCE_STATUS', 'COLUMN', N'SECONDARY_SOURCE_CLUSTER_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the denormalised last execution datetime of the component instance.  More detail can be found in TB_ETL_COMPONENT_INSTANCE_EXECUTION.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ETL_COMPONENT_INSTANCE_STATUS', 'COLUMN', N'LAST_EXECUTED_DATETIME'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the denormalised maximum written datetime on the source.  More detail can be found in TB_ETL_COMPONENT_INSTANCE_EXECUTION.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ETL_COMPONENT_INSTANCE_STATUS', 'COLUMN', N'MAX_SOURCE_DATETIME'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the denormalised maximum written datetime on the destination.  More detail can be found in TB_ETL_COMPONENT_INSTANCE_EXECUTION.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ETL_COMPONENT_INSTANCE_STATUS', 'COLUMN', N'MAX_DESTINATION_DATETIME'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ETL_COMPONENT_INSTANCE_STATUS', 'COLUMN', N'msrepl_tran_version'
GO
GRANT DELETE
	ON [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	TO [portalapp_role]
GO
GRANT DELETE
	ON [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	TO [portal_default_mediator_role]
GO
GRANT INSERT
	ON [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	TO [portal_default_mediator_role]
GO
GRANT SELECT
	ON [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	TO [portal_default_mediator_role]
GO
GRANT UPDATE
	ON [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS]
	TO [portal_default_mediator_role]
GO
ALTER TABLE [dbo].[TB_ETL_COMPONENT_INSTANCE_STATUS] SET (LOCK_ESCALATION = TABLE)
GO
