SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE] (
		[COMPONENT_TYPE_ID]            [uniqueidentifier] NOT NULL ROWGUIDCOL,
		[RESOURCE_TYPE_ID]             [uniqueidentifier] NOT NULL,
		[NAME]                         [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
		[INTERNAL_NAME]                [nvarchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
		[DESCRIPTION]                  [nvarchar](500) COLLATE Latin1_General_CI_AS NOT NULL,
		[REQUIRED]                     [bit] NOT NULL,
		[CONNECTION_TYPE_ID]           [uniqueidentifier] NULL,
		[MAX_INSTANCES_PER_SERVER]     [int] NULL,
		[SYSTEM]                       [bit] NOT NULL,
		[DELETED]                      [bit] NOT NULL,
		[msrepl_tran_version]          [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
		PRIMARY KEY
		CLUSTERED
		([COMPONENT_TYPE_ID])
	ON [ADMGROUP]
) ON [ADMGROUP]
GO
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	ADD
	CONSTRAINT [DF_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	ADD
	CONSTRAINT [DF_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_COMPONENT_TYPE_ID]
	DEFAULT (newid()) FOR [COMPONENT_TYPE_ID]
GO
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	ADD
	CONSTRAINT [DF_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_DESCRIPTION]
	DEFAULT (N'') FOR [DESCRIPTION]
GO
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	ADD
	CONSTRAINT [DF_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_REQUIRED]
	DEFAULT ((0)) FOR [REQUIRED]
GO
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	ADD
	CONSTRAINT [DF_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_SYSTEM]
	DEFAULT ((0)) FOR [SYSTEM]
GO
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	ADD
	CONSTRAINT [DF_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_DELETED]
	DEFAULT ((0)) FOR [DELETED]
GO
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_RESOURCE_TYPE_ID]
	FOREIGN KEY ([RESOURCE_TYPE_ID]) REFERENCES [dbo].[TE_ADM_CLUSTER_RESOURCE_TYPE] ([CLUSTER_RESOURCE_TYPE_ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	CHECK CONSTRAINT [FK_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_RESOURCE_TYPE_ID]

GO
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_CONNECTION_TYPE_ID]
	FOREIGN KEY ([CONNECTION_TYPE_ID]) REFERENCES [dbo].[TE_CLU_CONNECTION_TYPE] ([CONNECTION_TYPE_ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	CHECK CONSTRAINT [FK_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_CONNECTION_TYPE_ID]

GO
CREATE NONCLUSTERED INDEX [IX_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_RESOURCE_TYPE_ID]
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE] ([RESOURCE_TYPE_ID])
	ON [ADMGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE_CONNECTION_TYPE_ID]
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE] ([CONNECTION_TYPE_ID])
	ON [ADMGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This table holds information about all the possible cluster resource types for resources (in TB_CLU_RESOURCE) in the system.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary key identifier for the record.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'COMPONENT_TYPE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The id of the cluster resource type this component belongs to.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'RESOURCE_TYPE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the display name for the cluster resource component type.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'NAME'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the systems internal name for the cluster resource component type.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'INTERNAL_NAME'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a brief description for the cluster resource component type.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'DESCRIPTION'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this component is required or optional. Required components will be auto-created by the configuration tool.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'REQUIRED'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The id of the connection type that this component supports. This is a foreign key to TE_CLU_CONNECTION_TYPE.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'CONNECTION_TYPE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The maximum number of instances of this component type allowed on a single server.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'MAX_INSTANCES_PER_SERVER'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates that this item was created by the installer.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'SYSTEM'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Indicates if this item is deleted.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'DELETED'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE', 'COLUMN', N'msrepl_tran_version'
GO
DENY DELETE
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portalapp_role]
GO
DENY INSERT
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portalapp_role]
GO
DENY UPDATE
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portalrs_role]
GO
GRANT SELECT
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portal_database_configuration_read_role]
GO
GRANT DELETE
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portal_database_configuration_role]
GO
GRANT INSERT
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portal_database_configuration_role]
GO
GRANT SELECT
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portal_database_configuration_role]
GO
GRANT UPDATE
	ON [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE]
	TO [portal_database_configuration_role]
GO
ALTER TABLE [dbo].[TE_CLU_RESOURCE_INSTANCE_COMPONENT_TYPE] SET (LOCK_ESCALATION = TABLE)
GO
