SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION] (
		[CUSTOM_ATTRIBUTE_LOCALIZATION_URN]     [int] IDENTITY(1, 4) NOT FOR REPLICATION NOT NULL,
		[CUSTOM_ATTRIBUTE_URN]                  [int] NOT NULL,
		[CULTURE_URN]                           [int] NOT NULL,
		[LOCALIZED_VALUE]                       [nvarchar](1024) COLLATE Latin1_General_CI_AS NOT NULL,
		[CREATED_BY_ID]                         [uniqueidentifier] NOT NULL,
		[MODIFIED_BY_ID]                        [uniqueidentifier] NOT NULL,
		[CREATION_DATE]                         [datetime] NOT NULL,
		[MODIFIED_DATE]                         [datetime] NOT NULL,
		[msrepl_tran_version]                   [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
		PRIMARY KEY
		CLUSTERED
		([CUSTOM_ATTRIBUTE_LOCALIZATION_URN])
	ON [ADMGROUP]
) ON [ADMGROUP]
GO
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	ADD
	CONSTRAINT [DF_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_CREATION_DATE]
	DEFAULT (getutcdate()) FOR [CREATION_DATE]
GO
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	ADD
	CONSTRAINT [DF_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_MODIFIED_DATE]
	DEFAULT (getutcdate()) FOR [MODIFIED_DATE]
GO
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	ADD
	CONSTRAINT [DF_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_TB_SEC_USER_CREATED_BY_ID]
	FOREIGN KEY ([CREATED_BY_ID]) REFERENCES [dbo].[TB_SEC_USER] ([USER_ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	CHECK CONSTRAINT [FK_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_TB_SEC_USER_CREATED_BY_ID]

GO
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_TB_SEC_USER_MODIFIED_BY_ID]
	FOREIGN KEY ([MODIFIED_BY_ID]) REFERENCES [dbo].[TB_SEC_USER] ([USER_ID])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	CHECK CONSTRAINT [FK_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_TB_SEC_USER_MODIFIED_BY_ID]

GO
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_TB_ADM_CUSTOM_ATTRIBUTE_ATTRIBUTE_URN]
	FOREIGN KEY ([CUSTOM_ATTRIBUTE_URN]) REFERENCES [dbo].[TB_ADM_CUSTOM_ATTRIBUTE] ([CUSTOM_ATTRIBUTE_URN])
	ON DELETE CASCADE
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	CHECK CONSTRAINT [FK_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_TB_ADM_CUSTOM_ATTRIBUTE_ATTRIBUTE_URN]

GO
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_TE_ADM_CULTURE_CULTURE_URN]
	FOREIGN KEY ([CULTURE_URN]) REFERENCES [dbo].[TE_ADM_CULTURE] ([CULTURE_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	CHECK CONSTRAINT [FK_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_TE_ADM_CULTURE_CULTURE_URN]

GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_CREATED_BY_ID]
	ON [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION] ([CREATED_BY_ID])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_CULTURE_URN]
	ON [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION] ([CULTURE_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_CUSTOM_ATTRIBUTE_URN]
	ON [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION] ([CUSTOM_ATTRIBUTE_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION_MODIFIED_BY_ID]
	ON [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION] ([MODIFIED_BY_ID])
	ON [ADMINDEXGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N' This table stores the localization information for the custom attributes defined in EGPL_CUSTOM_ATTRIBUTES.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary Key identifier for the record.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', 'COLUMN', N'CUSTOM_ATTRIBUTE_LOCALIZATION_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign Key to TB_ADM_CUSTOM_ATTRIBUTE.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', 'COLUMN', N'CUSTOM_ATTRIBUTE_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TE_ADM_CULTURE. Lookup from VW_ADM_CULTURE_LANGUAGE_CUBE based on CULTURE_NAME mapped with LANG_CODE from EGPL_L10N_CUSTOM_ENTRIES to return CULTURE_URN.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', 'COLUMN', N'CULTURE_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'String representing the localized value for the custom attribute.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', 'COLUMN', N'LOCALIZED_VALUE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the id as in TB_SEC_USER corresponding to the user who created the item.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', 'COLUMN', N'CREATED_BY_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the id as in TB_SEC_USER corresponding to the user who last modified the item.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', 'COLUMN', N'MODIFIED_BY_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the UTC date time stamp indicating when the item was created.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', 'COLUMN', N'CREATION_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the UTC date time stamp indicating when the item was last modified.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', 'COLUMN', N'MODIFIED_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION', 'COLUMN', N'msrepl_tran_version'
GO
GRANT DELETE
	ON [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION]
	TO [portalrs_role]
GO
ALTER TABLE [dbo].[TB_ADM_CUSTOM_ATTRIBUTE_LOCALIZATION] SET (LOCK_ESCALATION = TABLE)
GO
