SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TB_ADM_HIERARCHY_METADATA] (
		[HIERARCHY_METADATA_URN]                      [int] IDENTITY(1, 4) NOT FOR REPLICATION NOT NULL,
		[CLUSTER_RESOURCE_ID]                         [uniqueidentifier] NOT NULL,
		[OWNER_ID]                                    [uniqueidentifier] NULL,
		[HIERARCHY_METADATA_L10N_KEY_URN]             [int] NOT NULL,
		[HIERARCHY_METADATA_LEVEL_0_L10N_KEY_URN]     [int] NULL,
		[HIERARCHY_METADATA_LEVEL_1_L10N_KEY_URN]     [int] NULL,
		[HIERARCHY_METADATA_LEVEL_2_L10N_KEY_URN]     [int] NULL,
		[HIERARCHY_METADATA_LEVEL_3_L10N_KEY_URN]     [int] NULL,
		[HIERARCHY_METADATA_LEVEL_4_L10N_KEY_URN]     [int] NULL,
		[HIERARCHY_METADATA_LEVEL_5_L10N_KEY_URN]     [int] NULL,
		[HIERARCHY_METADATA_LEVEL_6_L10N_KEY_URN]     [int] NULL,
		[HIERARCHY_METADATA_LEVEL_7_L10N_KEY_URN]     [int] NULL,
		[HIERARCHY_METADATA_LEVEL_8_L10N_KEY_URN]     [int] NULL,
		[HIERARCHY_METADATA_LEVEL_9_L10N_KEY_URN]     [int] NULL,
		[CATEGORY_SUB_TYPE_ID]                        [int] NOT NULL,
		[DELETED]                                     [bit] NOT NULL,
		[HIDDEN]                                      [bit] NOT NULL,
		[SYSTEM]                                      [bit] NOT NULL,
		[LATEST]                                      [bit] NOT NULL,
		[CREATED_BY_ID]                               [uniqueidentifier] NOT NULL,
		[MODIFIED_BY_ID]                              [uniqueidentifier] NOT NULL,
		[CREATION_DATE]                               [datetime] NOT NULL,
		[MODIFIED_DATE]                               [datetime] NOT NULL,
		[msrepl_tran_version]                         [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TB_ADM_HIERARCHY_METADATA]
		PRIMARY KEY
		CLUSTERED
		([HIERARCHY_METADATA_URN])
	ON [ADMGROUP]
) ON [ADMGROUP]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	ADD
	CONSTRAINT [DF_TB_ADM_HIERARCHY_METADATA_CATEGORY_SUB_TYPE_ID]
	DEFAULT ((-1)) FOR [CATEGORY_SUB_TYPE_ID]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	ADD
	CONSTRAINT [DF_TB_ADM_HIERARCHY_METADATA_DELETED]
	DEFAULT ((0)) FOR [DELETED]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	ADD
	CONSTRAINT [DF_TB_ADM_HIERARCHY_METADATA_HIDDEN]
	DEFAULT ((0)) FOR [HIDDEN]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	ADD
	CONSTRAINT [DF_TB_ADM_HIERARCHY_METADATA_SYSTEM]
	DEFAULT ((0)) FOR [SYSTEM]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	ADD
	CONSTRAINT [DF_TB_ADM_HIERARCHY_METADATA_LATEST]
	DEFAULT ((1)) FOR [LATEST]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	ADD
	CONSTRAINT [DF_TB_ADM_HIERARCHY_METADATA_CREATION_DATE]
	DEFAULT (getutcdate()) FOR [CREATION_DATE]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	ADD
	CONSTRAINT [DF_TB_ADM_HIERARCHY_METADATA_MODIFIED_DATE]
	DEFAULT (getutcdate()) FOR [MODIFIED_DATE]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	ADD
	CONSTRAINT [DF_TB_ADM_HIERARCHY_METADATA_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_0_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_0_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_0_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_1_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_1_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_1_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_2_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_2_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_2_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_3_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_3_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_3_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_4_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_4_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_4_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_5_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_5_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_5_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_6_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_6_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_6_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_7_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_7_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_7_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_8_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_8_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_8_TB_ADM_L10N_KEY_URN]

GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_9_TB_ADM_L10N_KEY_URN]
	FOREIGN KEY ([HIERARCHY_METADATA_LEVEL_9_L10N_KEY_URN]) REFERENCES [dbo].[TB_ADM_L10N_KEY] ([L10N_KEY_URN])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA]
	CHECK CONSTRAINT [FK_TB_ADM_HIERARCHY_METADATA_9_TB_ADM_L10N_KEY_URN]

GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_0_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_0_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_1_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_1_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_2_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_2_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_3_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_3_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_4_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_4_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_5_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_5_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_6_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_6_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_7_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_7_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_8_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_8_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_ADM_HIERARCHY_METADATA_HIERARCHY_METADATA_LEVEL_9_L10N_KEY_URN]
	ON [dbo].[TB_ADM_HIERARCHY_METADATA] ([HIERARCHY_METADATA_LEVEL_9_L10N_KEY_URN])
	ON [ADMINDEXGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This table contains hierarchy metadata.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary key identifier for the record.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_CLU_RESOURCE identifying the source equipment where the hierachy metadata was imported from.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'CLUSTER_RESOURCE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_SEC_FOLDER identifying the tenant to which the hierachy associates to.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'OWNER_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_0_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_1_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_2_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_3_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_4_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_5_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_6_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_7_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_8_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to TB_ADM_L10N_KEY identifying the level localization', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIERARCHY_METADATA_LEVEL_9_L10N_KEY_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Urn representing the category sub type that this hierachy is a member of.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'CATEGORY_SUB_TYPE_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a flag indicating whether the item is deleted or not. Value 1 indicates deleted.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'DELETED'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a flag indicating whether the item is hidden or not. Value 1 indicates hidden.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'HIDDEN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a flag indicating whether the item is owned by the system or not. Value 1 indicates system owned item.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'SYSTEM'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is a flag indicating whether the item is latest or not. Value 1 indicates latest. For type 2 dimension change this value is set to 0 for parent items.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'LATEST'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the id as in TB_SEC_USER corresponding to the user who created the item.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'CREATED_BY_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the id as in TB_SEC_USER corresponding to the user who last modified the item.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'MODIFIED_BY_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the UTC date time stamp indicating when the item was created.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'CREATION_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'This is the UTC date time stamp indicating when the item was last modified.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'MODIFIED_DATE'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_ADM_HIERARCHY_METADATA', 'COLUMN', N'msrepl_tran_version'
GO
GRANT DELETE
	ON [dbo].[TB_ADM_HIERARCHY_METADATA]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_ADM_HIERARCHY_METADATA]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_ADM_HIERARCHY_METADATA]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_ADM_HIERARCHY_METADATA]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_ADM_HIERARCHY_METADATA]
	TO [portalrs_role]
GO
ALTER TABLE [dbo].[TB_ADM_HIERARCHY_METADATA] SET (LOCK_ESCALATION = TABLE)
GO
