SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING] (
		[RESOURCE_FOLDER_ITEM_MAPPING_ID]     [uniqueidentifier] NOT NULL,
		[RESOURCE_FOLDER_MAPPING_ID]          [uniqueidentifier] NOT NULL,
		[ITEM_BIZ_URN]                        [int] NOT NULL,
		[ITEM_TYPE_URN]                       [int] NOT NULL,
		[PRIORITY]                            [int] NOT NULL,
		[ENABLED]                             [bit] NOT NULL,
		[msrepl_tran_version]                 [uniqueidentifier] NOT NULL,
		CONSTRAINT [PK_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
		PRIMARY KEY
		CLUSTERED
		([RESOURCE_FOLDER_ITEM_MAPPING_ID])
	ON [ADMGROUP]
) ON [ADMGROUP]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	ADD
	CONSTRAINT [DF_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_RESOURCE_FOLDER_ITEM_MAPPING_ID]
	DEFAULT (newid()) FOR [RESOURCE_FOLDER_ITEM_MAPPING_ID]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	ADD
	CONSTRAINT [DF_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_PRIORITY]
	DEFAULT ((0)) FOR [PRIORITY]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	ADD
	CONSTRAINT [DF_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_ENABLED]
	DEFAULT ((1)) FOR [ENABLED]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	ADD
	CONSTRAINT [DF_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_msrepl_tran_version]
	DEFAULT (newid()) FOR [msrepl_tran_version]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	WITH NOCHECK
	ADD CONSTRAINT [FK_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_TB_CLU_RESOURCE_FOLDER_MAPPING]
	FOREIGN KEY ([RESOURCE_FOLDER_MAPPING_ID]) REFERENCES [dbo].[TB_CLU_RESOURCE_FOLDER_MAPPING] ([MAPPING_ID])
ALTER TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	CHECK CONSTRAINT [FK_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_TB_CLU_RESOURCE_FOLDER_MAPPING]

GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	WITH CHECK
	ADD CONSTRAINT [FK_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_TE_DIM_ITEM_TYPE]
	FOREIGN KEY ([ITEM_TYPE_URN]) REFERENCES [dbo].[TE_DIM_ITEM_TYPE] ([ITEM_TYPE_URN])
ALTER TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	CHECK CONSTRAINT [FK_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_TE_DIM_ITEM_TYPE]

GO
CREATE NONCLUSTERED INDEX [IX_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_RESOURCE_FOLDER_MAPPING_ID]
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING] ([RESOURCE_FOLDER_MAPPING_ID])
	ON [ADMINDEXGROUP]
GO
CREATE NONCLUSTERED INDEX [IX_TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING_ITEM_TYPE_URN]
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING] ([ITEM_TYPE_URN])
	ON [ADMINDEXGROUP]
GO
EXEC sp_addextendedproperty N'MS_Description', N'This table stores information about the items associated with a folder mapping.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', N'The primary key.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING', 'COLUMN', N'RESOURCE_FOLDER_ITEM_MAPPING_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Foreign key to the cluster folder mapping in TB_CLU_RESOURCE_FOLDER_MAPPING.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING', 'COLUMN', N'RESOURCE_FOLDER_MAPPING_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The business urn of the item mapped to the folder.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING', 'COLUMN', N'ITEM_BIZ_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'The type of the item defined in TE_DIM_ITEM_TYPE.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING', 'COLUMN', N'ITEM_TYPE_URN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'A integer indicating the precedence of this item mapping in relation to others on the same cluster resource. For future use.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING', 'COLUMN', N'PRIORITY'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Whether or not this mapping is currently enabled.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING', 'COLUMN', N'ENABLED'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Replication key identifier.', 'SCHEMA', N'dbo', 'TABLE', N'TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING', 'COLUMN', N'msrepl_tran_version'
GO
GRANT DELETE
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	TO [portalapp_role]
GO
GRANT INSERT
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	TO [portalapp_role]
GO
GRANT SELECT
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	TO [portalapp_role]
GO
GRANT UPDATE
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	TO [portalapp_role]
GO
GRANT DELETE
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	TO [portal_database_configuration_role]
GO
GRANT INSERT
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	TO [portal_database_configuration_role]
GO
GRANT SELECT
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	TO [portal_database_configuration_role]
GO
GRANT UPDATE
	ON [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING]
	TO [portal_database_configuration_role]
GO
ALTER TABLE [dbo].[TB_CLU_RESOURCE_FOLDER_ITEM_MAPPING] SET (LOCK_ESCALATION = TABLE)
GO
