SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROOM_CONTENTS] (
		[CONTENTS_KEY]     [decimal](38, 0) NOT NULL,
		[ROOM_KEY]         [decimal](38, 0) NULL,
		[NAME]             [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DESCRIPTION]      [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[QTY]              [int] NOT NULL,
		CONSTRAINT [SYS_C007385]
		PRIMARY KEY
		CLUSTERED
		([CONTENTS_KEY])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ROOM_CONTENTS]
	ADD
	CONSTRAINT [DF_ROOM_CONTENTS_QTY]
	DEFAULT ((1)) FOR [QTY]
GO
ALTER TABLE [dbo].[ROOM_CONTENTS] SET (LOCK_ESCALATION = TABLE)
GO
